// Recovered model: which method loads which sound asset.
//
// Source of truth: AUDIO_WIRING_MAP.md / audio_wiring_map.json - 161 shipped sound names, 136 of
// them located to the method that loads them (cstring -> __cfstring -> pool word -> ldr -> method). The
// table below is generated from that artifact, and the Python test re-derives it, so table and evidence
// cannot drift apart.
//
// The second array carries the part that decays. The artifact records a per-name boolean
// `replacement_referenced`, and that boolean was STALE when this header was written: it said 120 names
// were unwired, while measuring the current sources shows 59 wired and 77 still unwired.
// Rather than transcribe a number that goes wrong on its own, the list below is RE-MEASURED by
// tools/test_audio_wiring_model.py on every run: a TODO list with evidence, not a stored count.
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace blockheads::recovered::audio {

struct Wiring {
    std::string_view method;   // e.g. "World -[incrementalLoad]"
    std::string_view sound;    // e.g. "axe.wav"
};

inline constexpr std::array<Wiring, 275> kAudioWiring = {{
    {"AddCreditUI -[cloudTopupSucceeded]", "timeCrystalBuy.wav"},
    {"BlockAlertView -[buttonClicked:]", "click.wav"},
    {"BlockAlertView -[buttonDown:]", "clickDown.wav"},
    {"Blockhead -[abortCraft]", "tradeJobAbort.wav"},
    {"Blockhead -[addToJetFuel]", "fireShort.wav"},
    {"Blockhead -[collapseIfPossible]", "sighFemale.wav"},
    {"Blockhead -[collapseIfPossible]", "sighMale.wav"},
    {"Blockhead -[craftProgressUICompleteButtonTapped]", "fanfare.wav"},
    {"Blockhead -[dieForGood]", "blockheadDie.wav"},
    {"Blockhead -[die]", "die.wav"},
    {"Blockhead -[hurryCompletion:]", "shortTwinkle.wav"},
    {"Blockhead -[incrementDamageOfArmorClothing:]", "tear.wav"},
    {"Blockhead -[incrementUsageOfClothing]", "tear.wav"},
    {"Blockhead -[incrementUsageOfIceClothing]", "tear.wav"},
    {"Blockhead -[incrementUsageOfItem:indexToUse:wasAttack:multiplier:]", "toolBreak.wav"},
    {"Blockhead -[infoForPathRecalculation]", "noPath.wav"},
    {"Blockhead -[infoForPathRecalculation]", "noPath.wav"},
    {"Blockhead -[pickUpItemIfPossibleInTile:atPos:]", "littlePop.wav"},
    {"Blockhead -[pickUpItemIfPossibleInTile:atPos:]", "littlePop.wav"},
    {"Blockhead -[pickUpItemIfPossibleInTile:atPos:]", "pickupGem.wav"},
    {"Blockhead -[pickUpItemIfPossibleInTile:atPos:]", "pickupGem.wav"},
    {"Blockhead -[preDrawUpdate:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "regenerate.wav"},
    {"Blockhead -[preDrawUpdate:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "splash.wav"},
    {"Blockhead -[setPath:type:goalInteraction:extraData:]", "elevatorBell.wav"},
    {"Blockhead -[setPath:type:goalInteraction:extraData:]", "noPath.wav"},
    {"Blockhead -[sleepOnSpotIfPossible]", "sighFemale.wav"},
    {"Blockhead -[sleepOnSpotIfPossible]", "sighMale.wav"},
    {"Blockhead -[startTradeMission:tradePortal:]", "tpMission.wav"},
    {"Blockhead -[stopInteracting]", "yawnFemale.wav"},
    {"Blockhead -[stopInteracting]", "yawnMale.wav"},
    {"Blockhead -[sufferDamage:isSimulation:recoil:]", "manOuch.wav"},
    {"Blockhead -[sufferDamage:isSimulation:recoil:]", "womanOuch.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "bow.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "craftTool.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "craftWood.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "craftWorkbench.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "dig.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "elevatorBell.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "fanfare.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "glassSmash.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "jet.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "leaves.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "magnet.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "noPath.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "paint.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "pickaxe.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "pickupGem.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "place.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "place.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "place.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "punch.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "punchSmall.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "punchSmall.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "razor.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "snip.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "snowStep.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "spear.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "sword.wav"},
    {"Blockhead -[update:accurateDT:isSimulation:]", "tcMine.wav"},
    {"Blockhead -[updateGatherSpeedAndAnimationForCurrentInterationAndItem]", "sighFemale.wav"},
    {"Blockhead -[updateGatherSpeedAndAnimationForCurrentInterationAndItem]", "sighMale.wav"},
    {"Blockhead -[useCurrentItemIfPossible]", "crunch.wav"},
    {"Blockhead -[useCurrentItemIfPossible]", "drink.wav"},
    {"BlockheadUI -[alertView:didDismissWithButtonIndex:]", "shortTwinkle.wav"},
    {"CaveTroll -[die:]", "trollDie.wav"},
    {"CaveTroll -[preDrawUpdate:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "splash.wav"},
    {"CaveTroll -[preDrawUpdate:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "trollFound.wav"},
    {"CaveTroll -[reactToBeingFed]", "crunch.wav"},
    {"CaveTroll -[reactToBeingFed]", "troll.wav"},
    {"CaveTroll -[reactToBeingHit]", "trollOuch.wav"},
    {"CaveTroll -[startInteractingWithTileAtIndex:tile:interactionType:]", "troll.wav"},
    {"CaveTroll -[update:accurateDT:isSimulation:]", "punch.wav"},
    {"CaveTroll -[update:accurateDT:isSimulation:]", "snowStep.wav"},
    {"CaveTroll -[update:accurateDT:isSimulation:]", "troll.wav"},
    {"ChatView -[addChatMessage:displayNotification:]", "chatMessage.wav"},
    {"ChestUI -[button:]", "click.wav"},
    {"ChestUI -[moveTouch:]", "littlePop.wav"},
    {"ChestUI -[render:translation:pinchScale:]", "click.wav"},
    {"ChestUI -[startInventoryDragAtPos:]", "click.wav"},
    {"ChestUI -[updatePotentialDrag:fromDragSlot:dragItems:]", "littlePop.wav"},
    {"ClownFish -[die:]", "fishDie.wav"},
    {"ClownFish -[reactToBeingFed]", "crunch.wav"},
    {"ClownFish -[reactToBeingFed]", "fishRun.wav"},
    {"ClownFish -[reactToBeingHit]", "fishRun.wav"},
    {"CraftUI -[countSlider:]", "click.wav"},
    {"Dodo -[die:]", "dodoDie.wav"},
    {"Dodo -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "splash.wav"},
    {"Dodo -[jumpAndCluck]", "dodoCluck1.wav"},
    {"Dodo -[jumpAndCluck]", "dodoCluck2.wav"},
    {"Dodo -[jumpAndCluck]", "dodoCluck3.wav"},
    {"Dodo -[jumpAndCluck]", "dodoCluck4.wav"},
    {"Dodo -[reactToBeingFed]", "crunch.wav"},
    {"Dodo -[reactToBeingFed]", "dodo2.wav"},
    {"Dodo -[reactToBeingHit]", "cluck.wav"},
    {"Dodo -[successfulTame]", "dodoTame.wav"},
    {"Dodo -[update:accurateDT:isSimulation:]", "eggLay.wav"},
    {"Donkey -[loadDerivedStuff]", "babyUnicorn.wav"},
    {"Donkey -[loadDerivedStuff]", "donkeyEee.wav"},
    {"Donkey -[loadDerivedStuff]", "donkeyEeeLittle.wav"},
    {"Donkey -[loadDerivedStuff]", "donkeySnort.wav"},
    {"Donkey -[loadDerivedStuff]", "unicornDie.wav"},
    {"Donkey -[loadDerivedStuff]", "unicornprr.wav"},
    {"DonkeyLike -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "splash.wav"},
    {"DonkeyLike -[reactToBeingFed]", "crunch.wav"},
    {"DonkeyLike -[update:accurateDT:isSimulation:]", "eggLay.wav"},
    {"Door -[setOpen:direction:]", "doorClose.wav"},
    {"Door -[setOpen:direction:]", "doorOpen.wav"},
    {"Door -[setOpen:direction:]", "gateClose.wav"},
    {"Door -[setOpen:direction:]", "gateOpen.wav"},
    {"Door -[setOpen:direction:]", "ironDoorClose.wav"},
    {"Door -[setOpen:direction:]", "ironDoorOpen.wav"},
    {"DropBear -[doRemoteUpdate:]", "dropbeardrop.wav"},
    {"DropBear -[reactToBeingFed]", "crunch.wav"},
    {"DropBear -[reactToBeingHit]", "dropbear.wav"},
    {"DropBear -[successfulTame]", "dropbear.wav"},
    {"DropBear -[update:accurateDT:isSimulation:]", "dropbear.wav"},
    {"DropBear -[update:accurateDT:isSimulation:]", "dropbear.wav"},
    {"DropBear -[update:accurateDT:isSimulation:]", "dropbeardrop.wav"},
    {"DropBear -[update:accurateDT:isSimulation:]", "dropbeardrop.wav"},
    {"DynamicWorld -[createFreeBlockAtPosition:ofType:dataA:dataB:subItems:dynamicObjectSaveDict:hovers:playSound:priorityBlockhead:]", "craftCreate.wav"},
    {"DynamicWorld -[createFreeBlockAtPosition:ofType:dataA:dataB:subItems:dynamicObjectSaveDict:hovers:playSound:priorityBlockhead:]", "drop.wav"},
    {"DynamicWorld -[createFreeBlockAtPosition:ofType:dataA:dataB:subItems:dynamicObjectSaveDict:hovers:playSound:priorityBlockhead:]", "pop.wav"},
    {"DynamicWorld -[createFreeBlockAtPosition:ofType:dataA:dataB:subItems:dynamicObjectSaveDict:hovers:playSound:priorityBlockhead:]", "sale.wav"},
    {"DynamicWorld -[createTreasureChestOrTrollAtTile:atPos:loadTroll:loadTreasure:]", "trollFound.wav"},
    {"DynamicWorld -[loadNewBlockheadAtPos:craftableItemObject:uniqueID:]", "fanfare.wav"},
    {"DynamicWorld -[openElevatorAtPos:]", "elevatorDoor.wav"},
    {"DynamicWorld -[playTimeCrystalReceivedSoundAtPos:]", "tcPickup.wav"},
    {"DynamicWorld -[playTimeCrystalReceivedSoundAtPos:]", "timeCrystal.wav"},
    {"DynamicWorld -[teleportBlockhead:toWorkbench:]", "fanfare.wav"},
    {"DynamicWorld -[updateNetObjects]", "craftCreate.wav"},
    {"DynamicWorld -[updateNetObjects]", "drop.wav"},
    {"DynamicWorld -[updateNetObjects]", "pop.wav"},
    {"DynamicWorld -[updateNetObjects]", "sale.wav"},
    {"DynamicWorld -[updateNetObjects]", "timeCrystal.wav"},
    {"Egg -[hatch:]", "hatch.wav"},
    {"FishingRod -[directionalSwipe:]", "fishCast.wav"},
    {"FishingRod -[setHookedFish:]", "fishReelIn.wav"},
    {"FreeBlock -[hitLava]", "freeblockLavaHiss.wav"},
    {"FreeBlock -[update:accurateDT:isSimulation:]", "littlePop.wav"},
    {"FreeBlock -[update:accurateDT:isSimulation:]", "pickupGem.wav"},
    {"GameView -[actuallyDoExitWorldRightNowReallyNow]", "mountainKingLoop.mp4"},
    {"GameView -[checkForLikeAfterActivate]", "timeCrystalBuy.wav"},
    {"GameView -[cloudAuthenticateContainedCrystals:]", "timeCrystalBuy.wav"},
    {"GameView -[completeTransaction:]", "timeCrystalBuy.wav"},
    {"GameView -[completeTransaction:]", "timeCrystalBuy.wav"},
    {"GameView -[gameSoundFinshedFadingOut]", "mountainKingLoop.mp4"},
    {"GameView -[initOpenGL]", "mountainKingLoop.mp4"},
    {"GameView -[mainMenuSoundFinshedFadingOut]", "largo.mp4"},
    {"GameView -[restoreTransaction:]", "timeCrystalBuy.wav"},
    {"GameView -[rewardIncentivizedVideoCurrency:]", "timeCrystalBuy.wav"},
    {"HandCar -[loadDerivedStuff]", "rail.wav"},
    {"MJControl -[endTouch:]", "click.wav"},
    {"MJControl -[startTouch:]", "clickDown.wav"},
    {"NPC -[successfulTame]", "chimeUpgrade.wav"},
    {"PaintMixUI -[countSlider:]", "click.wav"},
    {"Scorpion -[die:]", "scorpionAttack.wav"},
    {"Scorpion -[reactToBeingFed]", "crunch.wav"},
    {"Scorpion -[reactToBeingFed]", "scorpionFire.wav"},
    {"Scorpion -[reactToBeingHit]", "scorpionFire.wav"},
    {"Scorpion -[update:accurateDT:isSimulation:]", "scorpion.wav"},
    {"Shark -[die:]", "fishDie.wav"},
    {"Shark -[reactToBeingFed]", "crunch.wav"},
    {"Shark -[reactToBeingFed]", "fishRun.wav"},
    {"Shark -[reactToBeingHit]", "fishRun.wav"},
    {"Shark -[remoteCreationDataUpdate:]", "jaws.wav"},
    {"Shark -[update:accurateDT:isSimulation:]", "jaws.wav"},
    {"Shark -[update:accurateDT:isSimulation:]", "sharkSplash.wav"},
    {"SteamTrain -[addToFuelForItem:]", "fireShort.wav"},
    {"SteamTrain -[addToFuelForItem:]", "trainWhistle.wav"},
    {"SteamTrain -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "steamHiss.wav"},
    {"SteamTrain -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "trainChug.wav"},
    {"SteamTrain -[remoteUpdate:]", "trainWhistle.wav"},
    {"TableSelectionAlertView -[buttonClicked:]", "click.wav"},
    {"TableSelectionAlertView -[buttonDown:]", "clickDown.wav"},
    {"TableViewUI -[slider:]", "click.wav"},
    {"TradePortal -[buyItem:atTotalPrice:count:]", "sale.wav"},
    {"TradePortal -[remoteUpdate:]", "upgrade.wav"},
    {"TradePortal -[sellItem:atTotalPrice:count:usageMultiplier:]", "sale.wav"},
    {"TradePortal -[upgradeToNextLevel]", "upgrade.wav"},
    {"TradingPostBuyUI -[countSlider:]", "click.wav"},
    {"TradingPostSellUI -[coinsButton:]", "sale.wav"},
    {"TradingPostSellUI -[moveTouch:]", "littlePop.wav"},
    {"TradingPostSellUI -[priceSlider:]", "click.wav"},
    {"TradingPostSellUI -[render:translation:pinchScale:]", "click.wav"},
    {"TradingPostSellUI -[sellButton:]", "click.wav"},
    {"TradingPostSellUI -[startInventoryDragAtPos:]", "click.wav"},
    {"TradingPostSellUI -[updatePotentialDrag:fromDragSlot:dragItems:]", "littlePop.wav"},
    {"UIManager -[hideAnyHideableUIDueToPanAtPoint:]", "click.wav"},
    {"UIManager -[playUIPopSound]", "menuPop.wav"},
    {"UIManager -[tap:]", "click.wav"},
    {"WearUI -[alertView:didDismissWithButtonIndex:]", "shortTwinkle.wav"},
    {"Weather -[initWithCache:world:worldTime:]", "rainHeavy.wav"},
    {"Weather -[initWithCache:world:worldTime:]", "rainLight.wav"},
    {"Weather -[initWithCache:world:worldTime:]", "rainUnderground.wav"},
    {"Weather -[initWithCache:world:worldTime:]", "wind.wav"},
    {"Weather -[loadCricketSounds]", "crickets1.wav"},
    {"Weather -[loadCricketSounds]", "crickets2.wav"},
    {"Workbench -[addToFuel:]", "fireShort.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "buzz1.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "eggExtractor.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "electricFurnace.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "electricMetalwork.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "fireLoop.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "fireLoopLow.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "furnace.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "portal.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "press.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "sluice.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "steam.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "steam.wav"},
    {"Workbench -[draw:projectionMatrix:modelViewMatrix:cameraMinXWorld:cameraMaxXWorld:cameraMinYWorld:cameraMaxYWorld:]", "stove.wav"},
    {"Workbench -[hurryCompletion:]", "shortTwinkle.wav"},
    {"Workbench -[remoteUpdate:]", "upgrade.wav"},
    {"Workbench -[upgradeToNextLevel]", "upgrade.wav"},
    {"World -[doCameraScreenshot]", "camera.wav"},
    {"World -[heartbeatDataRecieved:fromPeer:]", "slowdown.wav"},
    {"World -[heartbeatDataRecieved:fromPeer:]", "speedup.wav"},
    {"World -[incrementalLoad]", "cluck.wav"},
    {"World -[incrementalLoad]", "craftCreate.wav"},
    {"World -[incrementalLoad]", "crunch.wav"},
    {"World -[incrementalLoad]", "dodo2.wav"},
    {"World -[incrementalLoad]", "dodoCluck1.wav"},
    {"World -[incrementalLoad]", "dodoCluck2.wav"},
    {"World -[incrementalLoad]", "dodoCluck3.wav"},
    {"World -[incrementalLoad]", "dodoCluck4.wav"},
    {"World -[incrementalLoad]", "dodoTame.wav"},
    {"World -[incrementalLoad]", "donkeyEee.wav"},
    {"World -[incrementalLoad]", "donkeyEeeLittle.wav"},
    {"World -[incrementalLoad]", "donkeySnort.wav"},
    {"World -[incrementalLoad]", "drop.wav"},
    {"World -[incrementalLoad]", "dropbear.wav"},
    {"World -[incrementalLoad]", "freeblockLavaHiss.wav"},
    {"World -[incrementalLoad]", "hatch.wav"},
    {"World -[incrementalLoad]", "littlePop.wav"},
    {"World -[incrementalLoad]", "manDie.wav"},
    {"World -[incrementalLoad]", "manOuch.wav"},
    {"World -[incrementalLoad]", "pop.wav"},
    {"World -[incrementalLoad]", "sale.wav"},
    {"World -[incrementalLoad]", "snowStep.wav"},
    {"World -[incrementalLoad]", "spear.wav"},
    {"World -[incrementalLoad]", "splash.wav"},
    {"World -[incrementalLoad]", "tcPickup.wav"},
    {"World -[incrementalLoad]", "timeCrystal.wav"},
    {"World -[incrementalLoad]", "troll.wav"},
    {"World -[incrementalLoad]", "trollOuch.wav"},
    {"World -[incrementalLoad]", "yak1.wav"},
    {"World -[incrementalLoad]", "yak2.wav"},
    {"World -[incrementalLoad]", "yak3.wav"},
    {"World -[incrementalLoad]", "yakBaby.wav"},
    {"World -[placeWorkbenchOfType:atPos:saveDict:placedByClient:placedByBlockhead:placedByClientName:]", "fire.wav"},
    {"World -[preRenderUpdate:fastSlowDT:cameraZ:projectionMatrix:]", "divertissement.mp4"},
    {"World -[preRenderUpdate:fastSlowDT:cameraZ:projectionMatrix:]", "gym.mp4"},
    {"World -[preRenderUpdate:fastSlowDT:cameraZ:projectionMatrix:]", "largo.mp4"},
    {"World -[preRenderUpdate:fastSlowDT:cameraZ:projectionMatrix:]", "morning.mp4"},
    {"World -[preRenderUpdate:fastSlowDT:cameraZ:projectionMatrix:]", "nightFall.mp4"},
    {"World -[preRenderUpdate:fastSlowDT:cameraZ:projectionMatrix:]", "sneakySnitch.mp4"},
    {"World -[preRenderUpdate:fastSlowDT:cameraZ:projectionMatrix:]", "sugarPlum.mp4"},
    {"World -[preRenderUpdate:fastSlowDT:cameraZ:projectionMatrix:]", "tikopia.mp4"},
    {"World -[tap:]", "noPath.wav"},
    {"World -[tap:]", "noPath.wav"},
    {"World -[tap:]", "noPath.wav"},
    {"World -[tap:]", "pop.wav"},
    {"World -[tap:]", "tap.wav"},
    {"World -[tap:]", "tap.wav"},
    {"World -[tap:]", "tap.wav"},
    {"World -[update:accurateDT:pinchScale:dragInProgress:]", "slowdown.wav"},
    {"World -[update:accurateDT:pinchScale:dragInProgress:]", "speedup.wav"},
    {"WorldUI -[moveTouch:paused:index:]", "littlePop.wav"},
    {"WorldUI -[render:translation:pinchScale:paused:]", "click.wav"},
    {"WorldUI -[render:translation:pinchScale:paused:]", "click.wav"},
    {"WorldUI -[startInventoryDragAtPos:]", "click.wav"},
    {"WorldUI -[updatePotentialDrag:fromDragSlot:dragItems:]", "littlePop.wav"},
    {"Yak -[loadDerivedStuff]", "yak2.wav"},
    {"Yak -[loadDerivedStuff]", "yak3.wav"},
    {"Yak -[loadDerivedStuff]", "yakBaby.wav"},
}};

// Sound names the original loads and the replacement's sources do not mention, measured at this head.
inline constexpr std::array<std::string_view, 77> kNotYetReferenced = {{
    "babyUnicorn.wav",
    "blockheadDie.wav",
    "bow.wav",
    "buzz1.wav",
    "chatMessage.wav",
    "chimeUpgrade.wav",
    "craftTool.wav",
    "craftWood.wav",
    "craftWorkbench.wav",
    "divertissement.mp4",
    "doorClose.wav",
    "doorOpen.wav",
    "drink.wav",
    "dropbeardrop.wav",
    "eggExtractor.wav",
    "eggLay.wav",
    "electricFurnace.wav",
    "electricMetalwork.wav",
    "elevatorBell.wav",
    "elevatorDoor.wav",
    "fanfare.wav",
    "fireLoop.wav",
    "fireLoopLow.wav",
    "fireShort.wav",
    "fishCast.wav",
    "fishDie.wav",
    "fishReelIn.wav",
    "fishRun.wav",
    "furnace.wav",
    "gateClose.wav",
    "gateOpen.wav",
    "glassSmash.wav",
    "gym.mp4",
    "ironDoorClose.wav",
    "ironDoorOpen.wav",
    "jaws.wav",
    "largo.mp4",
    "magnet.wav",
    "menuPop.wav",
    "mountainKingLoop.mp4",
    "noPath.wav",
    "pickupGem.wav",
    "punch.wav",
    "punchSmall.wav",
    "rainHeavy.wav",
    "rainLight.wav",
    "rainUnderground.wav",
    "razor.wav",
    "scorpion.wav",
    "scorpionAttack.wav",
    "scorpionFire.wav",
    "sharkSplash.wav",
    "shortTwinkle.wav",
    "sighFemale.wav",
    "sighMale.wav",
    "sluice.wav",
    "sneakySnitch.mp4",
    "snip.wav",
    "steamHiss.wav",
    "stove.wav",
    "sugarPlum.mp4",
    "tcMine.wav",
    "tear.wav",
    "tikopia.mp4",
    "timeCrystalBuy.wav",
    "toolBreak.wav",
    "tpMission.wav",
    "tradeJobAbort.wav",
    "trainChug.wav",
    "trainWhistle.wav",
    "trollDie.wav",
    "trollFound.wav",
    "unicornDie.wav",
    "unicornprr.wav",
    "womanOuch.wav",
    "yawnFemale.wav",
    "yawnMale.wav",
}};

// The original's largest single loader, kept as a sanity anchor in both the header and the test.
inline constexpr std::string_view kLargestLoader = "World -[incrementalLoad]";
inline constexpr std::size_t kLargestLoaderSoundCount = 32;

}  // namespace blockheads::recovered::audio
