// Recovered model: the CraftableItemObject layout (1 ivars, offsets 4..4).
//
// Generated by tools/gen_layout_model.py from the binary's own OBJC_IVAR_$_CraftableItemObject.* table, so the offsets are the
// runtime's numbers rather than measurements. offset 4 is the host recorded in craftable_item_record.h: instance_size 128 = 4 + the 124-byte record, and initWithSaveDict: copies 124 bytes there with getBytes:length:. Anchoring on it makes the two models check each other.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace blockheads::recovered::craftable_item_object_layout {

struct Field {
    std::size_t offset;
    std::string_view name;
    std::uint32_t cell;
};

inline constexpr std::array<Field, 1> kCraftableItemObjectFields = {{
    {4, "craftableItem", 0x00f34ea0U},
}};

constexpr bool offsetsRise() {
    for (std::size_t i = 1; i < kCraftableItemObjectFields.size(); ++i)
        if (kCraftableItemObjectFields[i - 1].offset >= kCraftableItemObjectFields[i].offset) return false;
    return true;
}
static_assert(offsetsRise(), "the ivar table must be ordered and duplicate-free");

constexpr std::size_t offsetOf(std::string_view want) {
    for (const Field& f : kCraftableItemObjectFields)
        if (f.name == want) return f.offset;
    return static_cast<std::size_t>(-1);
}

static_assert(offsetOf("craftableItem") == 4);

}  // namespace blockheads::recovered::craftable_item_object_layout
