// GENERATED by tools/gen_sound_preload_list.py - do not edit by hand.
// Source of record: reconstruction/reverse-v3/native/audio_wiring_map.json
// Method: World -[incrementalLoad]  (original ELF 733d821027d69de329d0ba171df2e6013d612edf5a4d327badd001acc30b94c7)
// Names: 32   shipped: 32   already referenced by the replacement: 6
//
// Membership only: the original references each of these names from that one method.
// Playback order/volume are NOT claimed here.
#pragma once

namespace blockheads::recovered {

struct OriginalLoadTimeSound {
    const char* name;      // shipped asset filename
    const char* sha256;    // asset bytes, for verification rather than trust
    bool already_wired;    // true when the replacement already references the name
};

inline constexpr OriginalLoadTimeSound kOriginalLoadTimeSounds[] = {
    {"cluck.wav", "140102cf0e666ab6e6c84f3b7550f29e456dd59be38ece8941b675898ba7b541", false},
    {"craftCreate.wav", "50244da518f055ecf9346edf6c8771b1c2150a314dd38f9dfe97f3a08947ad01", true},
    {"crunch.wav", "692349dc3c61ac62e5e4d126dd47d827e6fa7bac49c4bd6d2ba16168d2469cd0", true},
    {"dodo2.wav", "34c327aabaf3b77596d59054a6f9f7b821fb2ed72c5130616b39eb483461f21e", false},
    {"dodoCluck1.wav", "32d94ad7e0a8966e89a1aa1fd9f1f851d90390318fb85439e49ccf7c93c98afb", true},
    {"dodoCluck2.wav", "b019baa99e0ccf8a0d6ca061e46855aa90923b3b3601831ec2fa5282a5ab4c0e", false},
    {"dodoCluck3.wav", "a0e9ff07e6005c41e944694f174ba29f2f835f4d3c2cf22d050241311d317909", false},
    {"dodoCluck4.wav", "331ff8166a559d6da2986371ca236c8df8e329751b665889ca2847288fe773d1", false},
    {"dodoTame.wav", "11cd1f42028e864917ffd5f716a31d1a7ce9adf777fd5b3e0b21c80a6c0b468c", false},
    {"donkeyEee.wav", "1ef7c95ef112e4b48bed42009164f39dfa9de35d947ef43709a416d215241db8", false},
    {"donkeyEeeLittle.wav", "9f6a42723e97d1410abc655d1c999c04f73175460ccb44d0d0df37a4fe5c1042", false},
    {"donkeySnort.wav", "6113ab8e321cb18b42006a67b670284ecbba67195b407ef887d3e68f78cfc5a4", false},
    {"drop.wav", "04dfb12b9e4c49b692e83586c6d7d10cbf81b2ba3e30da8279e93002fdf57215", false},
    {"dropbear.wav", "e0d7062c803d3756aca323ce55a0835aa37d280ec12d8e671e7f02cd571d232b", false},
    {"freeblockLavaHiss.wav", "18c376986d0f925b48aedfdcbba03ba7945524f52d5852f75360ef80921afb89", false},
    {"hatch.wav", "2a38f1c23db607ff96906f09657be084c76bed820ce5a2739362317d48668e08", false},
    {"littlePop.wav", "d2602923a3a2fe9c509dcbd2c2aa82891284f800b9adb1b3316b2c28f1a33c24", false},
    {"manDie.wav", "2a1ba8ac2c1cd304eae5a72330bd2f293b08ff6c51a3387ea1c59880c9b078ec", false},
    {"manOuch.wav", "9242cf9a89555f6b94e720a2e41880049ca1015129e8fb39b3f9c9a595806c30", true},
    {"pop.wav", "04dfb12b9e4c49b692e83586c6d7d10cbf81b2ba3e30da8279e93002fdf57215", true},
    {"sale.wav", "f201b4fa31caedfa91f9bd5b9d70bec26cb215c8ad3122c239c3203f2a51894e", false},
    {"snowStep.wav", "7e9d6c7bd0cf080c00139fc119fa02cd457cf4b6840995b1d8c7d015b965b4f1", false},
    {"spear.wav", "4f13576633f3cb5835bc337a121b0ea4462121c79d65cdc6011ca136db3942af", false},
    {"splash.wav", "710c49f97614cae48cbc3cdd8b272f85d672b45ac91d4be74dd2f41797615d3d", true},
    {"tcPickup.wav", "9d95c29a6b49645524d21178d46bb2d1db2cee87d56cb381a156fcd680b6fc5d", false},
    {"timeCrystal.wav", "458eea137fb14b018dbf5a652f934bf1fa09f33baeec38b7edc6f9e5fa56a320", false},
    {"troll.wav", "eb27661d9e43b431f3032afd45917b3d981f39fd59ef4c86316a29e6619053bc", false},
    {"trollOuch.wav", "e6505b7d4a93f84a16638acf9ad47b01e83da13f018d4d6db037b0caf69e90cb", false},
    {"yak1.wav", "e0263d8b711e0fd82b6822473089b9e69ed49afc37d6d3d78186495d9082964f", false},
    {"yak2.wav", "6944b23600a50f49bb631fbf40bf937d34480371703d526e10c2defe7aa4bc71", false},
    {"yak3.wav", "6ee6625bc6844517cb3281994a6192c553506c8f100497ca8b6159068a87c880", false},
    {"yakBaby.wav", "9b7e3bb2fe8a4ba0c3cec5255da6541d001dddd6aecffe3c9524f5da240d75c6", false},
};

inline constexpr int kOriginalLoadTimeSoundCount = 32;

}  // namespace blockheads::recovered
