// Recovered model: the UIManager layout (46 ivars, offsets 4..154).
//
// Generated by tools/gen_layout_model.py from the binary's own OBJC_IVAR_$_UIManager.* table, so the offsets are the
// runtime's numbers rather than measurements. UIManager+56 is the live-verified hop to paintMixUI, and +4/+8 match the walk's World and DynamicWorld edges, so this model and the live measurement agree with each other.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace blockheads::recovered::u_i_manager_layout {

struct Field {
    std::size_t offset;
    std::string_view name;
    std::uint32_t cell;
};

inline constexpr std::array<Field, 46> kUIManagerFields = {{
    {4, "world", 0x00f34ea4U},
    {8, "dynamicWorld", 0x00f34ea8U},
    {12, "cache", 0x00f34eacU},
    {16, "windowInfo", 0x00f34eb0U},
    {20, "worldUI", 0x00f34eb8U},
    {24, "pauseUI", 0x00f34f20U},
    {28, "mapUI", 0x00f34f24U},
    {32, "tcUI", 0x00f34f14U},
    {36, "dpad", 0x00f34f18U},
    {40, "tcUIDisplayed", 0x00f34f30U},
    {44, "workbenchChoiceUI", 0x00f34ebcU},
    {48, "craftUI", 0x00f34ef4U},
    {52, "newBlockheadUI", 0x00f34ec0U},
    {56, "paintMixUI", 0x00f34ec4U},
    {60, "chestUI", 0x00f34ed0U},
    {64, "blockheadUI", 0x00f34f08U},
    {68, "craftProgressUI", 0x00f34f0cU},
    {72, "addFuelUI", 0x00f34ec8U},
    {76, "jetPackUI", 0x00f34ef8U},
    {80, "sleepProgressUI", 0x00f34f10U},
    {84, "regenerateUI", 0x00f34eccU},
    {88, "hungerUI", 0x00f34ed4U},
    {92, "wearUI", 0x00f34ed8U},
    {96, "inventoryFullUI", 0x00f34f00U},
    {100, "cameraUI", 0x00f34f28U},
    {104, "signTextUI", 0x00f34f1cU},
    {108, "tradingPostSellUI", 0x00f34edcU},
    {112, "tradingPostBuyUI", 0x00f34ee0U},
    {116, "ownershipSignUI", 0x00f34ee4U},
    {120, "workbenchProgressBarUI", 0x00f34ee8U},
    {124, "tradePortalUI", 0x00f34eecU},
    {128, "tradeMissionUI", 0x00f34ef0U},
    {132, "petUI", 0x00f34efcU},
    {136, "customizeBlockheadUI", 0x00f34f04U},
    {140, "uiViews", 0x00f34eb4U},
    {144, "fuelInventoryItemTapped", 0x00f34f4cU},
    {145, "pauseTapped", 0x00f34f58U},
    {146, "pauseResumeTapped", 0x00f34f38U},
    {147, "dismissCameraUI", 0x00f34f3cU},
    {148, "hidePauseUI", 0x00f34f34U},
    {149, "showTCUITapped", 0x00f34f44U},
    {150, "hideTCUITapped", 0x00f34f48U},
    {151, "showCameraUITapped", 0x00f34f40U},
    {152, "mapDisplayed", 0x00f34f2cU},
    {153, "currentTouchIsInInventoryButtons", 0x00f34f50U},
    {154, "currentTouchIsInAnyButtons", 0x00f34f54U},
}};

constexpr bool offsetsRise() {
    for (std::size_t i = 1; i < kUIManagerFields.size(); ++i)
        if (kUIManagerFields[i - 1].offset >= kUIManagerFields[i].offset) return false;
    return true;
}
static_assert(offsetsRise(), "the ivar table must be ordered and duplicate-free");

constexpr std::size_t offsetOf(std::string_view want) {
    for (const Field& f : kUIManagerFields)
        if (f.name == want) return f.offset;
    return static_cast<std::size_t>(-1);
}

static_assert(offsetOf("paintMixUI") == 56);
static_assert(offsetOf("world") == 4);
static_assert(offsetOf("dynamicWorld") == 8);
static_assert(offsetOf("craftUI") == 48);

}  // namespace blockheads::recovered::u_i_manager_layout
