#!/usr/bin/env python3
"""Emit the bounded NPC -[loadValuesFromSaveDict:] listing with pool annotations.

Format-compatible with the checked-in disasm_*.txt files (address, raw word,
comment; raw words are byte-order strings like `verify_disassembly` expects).
The '# implementation:' owner header is what the coverage ledger attributes
refs/cfg to. Deterministic: capstone over the SHA-256-pinned ELF.

Cell classification (all on file bytes + relocation tables, not load-time
memory):
- GOT: R_ARM_ABS32/CALL relocation names the import (file word 0);
- ivar-offset storage: resolved slot equals dynsym st_value of OBJC_IVAR_$…;
- selref: slot word indexes a __objc_selrefs-known selector string;
- CFString object: resolved slot carries R_ARM_ABS32 against
  __CFConstantStringClassReference; the data pointer at +8 is a file
  constant, verified by length field == strlen.
"""
import hashlib, io, sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS))
import capstone
from elftools.elf.elffile import ELFFile
from elftools.elf.relocation import RelocationSection
from trace_objc_dispatch import ELFMemory

ELF = Path.home() / 'blockheads-work/extracted/lib/armeabi-v7a/libApplication.so'
SHA = '733d821027d69de329d0ba171df2e6013d612edf5a4d327badd001acc30b94c7'
BASE = 0x0105FAF4
TITLE, TYPES, START_S, END_S, OUTNAME = sys.argv[1:6]
START, END = int(START_S, 16), int(END_S, 16)
OUT = TOOLS.parent / 'reconstruction/reverse-v3/native' / OUTNAME


def signed(v):
    return v - (1 << 32) if v & 0x80000000 else v


def main():
    raw = ELF.read_bytes()
    if hashlib.sha256(raw).hexdigest() != SHA:
        raise SystemExit('ELF SHA mismatch')
    m = ELFMemory(ELF)
    elf = ELFFile(io.BytesIO(raw))

    def rw(a):
        off = m.offset(a, 4)
        return None if off is None else int.from_bytes(m.data[off:off + 4], 'little')

    def cstr(a):
        if a is None or a >= 0x1060488:
            return None
        off = m.offset(a, 1)
        if off is None:
            return None
        end = m.data.find(b'\0', off, off + 96)
        if end < 0:
            return None
        try:
            s = m.data[off:end].decode('ascii')
        except UnicodeDecodeError:
            return None
        return s if s.isprintable() else None

    abs32 = {}
    for section in elf.iter_sections():
        if isinstance(section, RelocationSection):
            syms = elf.get_section(section['sh_link'])
            for rel in section.iter_relocations():
                if rel['r_info_type'] == 2 and rel['r_info_sym']:
                    abs32[rel['r_offset']] = syms.get_symbol(rel['r_info_sym']).name
    dynsym = elf.get_section_by_name('.dynsym')
    ivar_addrs = {s['st_value']: s.name for s in dynsym.iter_symbols()
                  if s['st_value'] and s.name.startswith('OBJC_IVAR_$_')}

    def cellinfo(vaddr):
        w = rw(vaddr)
        if w is None:
            return None
        t = (BASE + signed(w)) & 0xFFFFFFFF
        imp = m.imports.get(t)
        if imp:
            return f'GOT {imp} slot 0x{t:08x} (relocated at load)'
        name = abs32.get(t)
        if name and name.startswith('OBJC_IVAR_$_'):
            offv = rw(t)
            return f'ivar-offset storage {name} = {offv}'
        if ivar_addrs.get(t):
            return f'ivar-offset storage {ivar_addrs[t]} = {rw(t)}'
        if name and name.startswith('OBJC_CLASS_$_'):
            return f'classref {name} slot 0x{t:08x} (relocated at load)'
        if name == '__CFConstantStringClassReference':
            da = rw(t + 8)
            key = cstr(da)
            ln = rw(t + 12)
            if key is not None and ln is not None and ln == len(key.encode()):
                return f'CFString key obj @0x{t:08x} {key!r}'
            return f'CFString isa cell @0x{t:08x} data-ptr unresolved'
        tw = rw(t)
        if tw is None:
            return f'slot 0x{t:08x} unmapped'
        if tw == 0:
            return f'slot 0x{t:08x} word 0 (load-relocated, unclassified)'
        name = ivar_addrs.get(tw)
        if name:
            return f'ivar-offset storage {name} (slot 0x{t:08x}) = {rw(tw)}'
        sel = m.selectors.get(tw)
        if sel:
            return f'selref/cstring @0x{tw:08x} {sel!r}'
        return f'slot 0x{t:08x} word 0x{tw:08x}'

    md = capstone.Cs(capstone.CS_ARCH_ARM, capstone.CS_MODE_ARM)
    md.detail = False
    lines = [
        f'# {TITLE}',
        f'# types: {TYPES}',
        f'# implementation: 0x{START:08x}',
        f'# boundary: 0x{END:08x} (next method IMP from the pinned ObjC method map)',
        '# generated by capstone 5 over the SHA-256-pinned ELF; PIC base 0x0105faf4',
        '',
    ]
    off0 = m.offset(START, END - START)
    count = 0
    for a in range(START, END, 4):
        w4 = m.data[off0 + (a - START): off0 + (a - START) + 4]
        w = int.from_bytes(w4, 'little')
        got = list(md.disasm(w4, a))
        mn = got[0].mnemonic if got else 'invalid'
        text = f'{mn} {got[0].op_str}'.strip() if mn != 'invalid' else 'invalid'
        note = ''
        if mn == "ldr" and w & 0x059F0000 == 0x059F0000 and ((w >> 12) & 0xF) != 15:
            lit = (a + 8 + (w & 0xFFF)) & 0xFFFFFFFF
            lw = rw(lit)
            info = cellinfo(lit)
            if lw is not None:
                note = f'  ; [0x{lit:08x}:4]=0x{lw:08x}'
                if info:
                    note += f' -> {info}'
        lines.append(f'            0x{a:08x}      {w4.hex()}       {text}{note}')
        count += 1
    OUT.write_text('\n'.join(lines) + '\n')
    print(f'wrote {OUT.name}: {count} words')
    import re
    rows = re.findall(r'\b(0x[0-9a-fA-F]{8})\s+([0-9a-fA-F]{8})\s', OUT.read_text())
    addrs = []
    for addr, hx in rows:
        addr = int(addr, 16)
        if m.word(addr) != int.from_bytes(bytes.fromhex(hx), 'little'):
            raise SystemExit(f'word drift {addr:#x}')
        addrs.append(addr)
    assert len(addrs) == len(set(addrs)) and set(addrs) == set(range(START, END, 4))
    print('coverage gate: OK')


if __name__ == '__main__':
    main()
