#!/usr/bin/env python3
"""Emit the bounded NPC -[loadValuesFromSaveDict:] listing with pool annotations.

Format-compatible with the checked-in disasm_*.txt files (address, raw word,
comment). The '# implementation:' owner header is what the coverage ledger
attributes refs/cfg to. Deterministic: capstone over the SHA-256-pinned ELF,
literal cells decoded via the PIC base (GOT import / selector cstring /
CFString key candidate).
"""
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS))
import capstone
from elftools.elf.elffile import ELFFile
from trace_objc_dispatch import ELFMemory
import io

ELF = Path.home() / 'blockheads-work/extracted/lib/armeabi-v7a/libApplication.so'
SHA = '733d821027d69de329d0ba171df2e6013d612edf5a4d327badd001acc30b94c7'
BASE = 0x0105FAF4
START, END = 0x00643B20, 0x0064448C   # next IMP: NPC -[update:] region boundary
OUT = TOOLS.parent / 'reconstruction/reverse-v3/native/disasm_npc_loadvaluesfromsavedict.txt'


def signed(v):
    return v - (1 << 32) if v & 0x80000000 else v


def main():
    import hashlib
    raw = ELF.read_bytes()
    if hashlib.sha256(raw).hexdigest() != SHA:
        raise SystemExit('ELF SHA mismatch')
    m = ELFMemory(ELF)

    def word(a):
        v = m.word(a)
        return None if v is None else int(v)

    def cstr(a):
        if a is None or a >= 0x1060488:
            return None
        off = m.offset(a, 1)
        if off is None:
            return None
        end = m.data.find(b'\0', off, off + 96)
        if end < 0:
            return None
        try:
            s = m.data[off:end].decode('ascii')
        except UnicodeDecodeError:
            return None
        return s if s.isprintable() else None

    elf = ELFFile(io.BytesIO(raw))
    dynsym = elf.get_section_by_name('.dynsym')
    symbols = {s['st_value']: s.name for s in dynsym.iter_symbols() if s['st_value']}

    def cellinfo(vaddr):
        w = word(vaddr)
        if w is None:
            return None
        t = (BASE + signed(w)) & 0xFFFFFFFF
        tw = word(t)
        imp = m.imports.get(t)
        if imp:
            return f'GOT {imp} slot 0x{t:08x}'
        if tw is None:
            return f'slot 0x{t:08x} unmapped'
        sel = m.selectors.get(tw)
        if sel:
            return f'selref/cstring @0x{tw:08x} {sel!r}'
        sym = symbols.get(tw)
        if sym:
            return f'sym {sym} @0x{tw:08x}'
        da = word(tw + 8) if tw + 8 < 0x1060488 else None
        key = cstr(da) if da else None
        if key:
            return f'CFString obj @0x{tw:08x} -> {key!r}'
        return f'slot 0x{t:08x} word 0x{tw:08x}'

    md = capstone.Cs(capstone.CS_ARCH_ARM, capstone.CS_MODE_ARM)
    md.detail = False
    lines = [
        '# NPC -[loadValuesFromSaveDict:]',
        '# types: v12@0:4@8',
        '# implementation: 0x00643b20',
        '# boundary: 0x0064448c (next method IMP from the pinned ObjC method map)',
        '# generated by capstone 5 over the SHA-256-pinned ELF; PIC base 0x0105faf4',
        '',
    ]
    off0 = m.offset(START, END - START)
    count = 0
    for a in range(START, END, 4):
        w4 = m.data[off0 + (a - START): off0 + (a - START) + 4]
        w = int.from_bytes(w4, 'little')
        got = list(md.disasm(w4, a))
        dis = got[0].op_str if got and got[0].mnemonic else ''
        mn = got[0].mnemonic if got else 'invalid'
        text = f'{mn} {dis}'.strip() if mn != 'invalid' else 'invalid'
        note = ''
        if w & 0x059F0000 == 0x059F0000 and ((w >> 12) & 0xF) != 15:
            lit = (a + 8 + (w & 0xFFF)) & 0xFFFFFFFF
            lw = word(lit)
            info = cellinfo(lit) if lw is not None else None
            if lw is not None:
                note = f'  ; [0x{lit:08x}:4]=0x{lw:08x}'
                if info:
                    note += f' -> {info}'
        lines.append(f'            0x{a:08x}      {w4.hex()}       {text}{note}')
        count += 1
    OUT.write_text('\n'.join(lines) + '\n')
    print(f'wrote {OUT.name}: {count} words')
    # gate: exact coverage + raw-word equality
    import re
    rows = re.findall(r'\b(0x[0-9a-fA-F]{8})\s+([0-9a-fA-F]{8})\s', OUT.read_text())
    addrs = []
    for addr, hx in rows:
        addr = int(addr, 16)
        if m.word(addr) != int.from_bytes(bytes.fromhex(hx), 'little'):
            raise SystemExit(f'word drift {addr:#x}')
        addrs.append(addr)
    assert len(addrs) == len(set(addrs)) and set(addrs) == set(range(START, END, 4))
    print('coverage gate: OK')


if __name__ == '__main__':
    main()
