#!/usr/bin/env python3
"""Generate the client-app DynamicObjectType table from the decoded matrix.

Single source of truth: reconstruction/reverse-v3/native/dynamicobject_type_matrix.json
(decoded from `_Z25classForDynamicObjectTypei` @ 0x00b597bc, the 1..64 jump
table of the SHA-pinned 1.7.6 ELF). The app-side type registry must not carry a
hand-transcribed copy of the mapping: this generator emits a C++ include and
`--check` fails on drift, exactly like the trace-code single-source files.

Usage:
  python3 tools/gen_dynamic_object_type_table.py           # write the include
  python3 tools/gen_dynamic_object_type_table.py --check   # verify committed copy
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / 'reconstruction/reverse-v3/native/dynamicobject_type_matrix.json'
OUT = ROOT / 'app/src/main/cpp/dynamic_object_type_table.inc'


def render():
    matrix = json.loads(MATRIX.read_text())
    types = matrix['types']
    assert matrix['total_types'] == 64, matrix['total_types']
    assert [t['type_id'] for t in types] == list(range(1, 65)), 'type id order'
    lines = [
        '// GENERATED by tools/gen_dynamic_object_type_table.py from',
        '// reconstruction/reverse-v3/native/dynamicobject_type_matrix.json',
        '// (classForDynamicObjectType jump table 0x00b597fc, ELF',
        f"// {matrix['elf_sha256']}) -- do not edit.",
        '// Every row is decoded from the binary; no name is inferred from the key',
        '// shape or from the replacement game.',
    ]
    for t in types:
        lines.append('    {%d, "%s", "%s"},' % (
            t['type_id'], t['class_name'], t['jump_target']))
    lines.append('')
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ''
        if current != text:
            print(f'{OUT} is stale; run tools/gen_dynamic_object_type_table.py')
            return 1
        print('dynamic object type table: PASS (matches the decoded matrix)')
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f'wrote {OUT.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
