#!/usr/bin/env python3
"""Trace-code single source of truth (tooling upgrade after the b4f bug).

reconstruction/reverse-v3/native/trace_schemas.json is the ONLY place trace
codes are defined. This generator emits both consumers:

  * tools/trace_codes_gen.py                (imported by the ARM harnesses)
  * reconstruction/recovered/generated/trace_codes.h
    (included by the recovered contract headers)

Run `python3 tools/gen_trace_codes.py` after editing the JSON, and
`python3 tools/gen_trace_codes.py --check` in CI/guards to fail on drift.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / 'reconstruction/reverse-v3/native/trace_schemas.json'
PY_OUT = ROOT / 'tools/trace_codes_gen.py'
H_OUT = ROOT / 'reconstruction/recovered/generated/trace_codes.h'

PY_HEADER = '''# GENERATED by tools/gen_trace_codes.py from
# reconstruction/reverse-v3/native/trace_schemas.json -- do not edit.
# Single source of truth for LEVEL-B differential trace codes (the b4f
# collision bug: a hand-maintained Python enumerate drifted from the C++
# enum because two tables encoded the same semantics).

'''

H_HEADER = '''// GENERATED by tools/gen_trace_codes.py from
// reconstruction/reverse-v3/native/trace_schemas.json -- do not edit.
// Single source of truth for LEVEL-B differential trace codes.
#pragma once

#include <cstdint>

'''


def check_unique(codes, table):
    seen = {}
    for name, value in codes.items():
        if value in seen:
            raise SystemExit(
                f'trace schema {table}: duplicate code {value} for '
                f'{name} and {seen[value]}')
        seen[value] = name


def render(schema):
    tables = schema['tables']
    for name, table in tables.items():
        check_unique(table['codes'], name)

    py = [PY_HEADER]
    for name, table in tables.items():
        const = name.upper()
        py.append(f'{const}_CODES = {json.dumps(table["codes"], indent=4)}\n')
    py.append('TABLES = {')
    for name in tables:
        py.append(f'    {name!r}: {name.upper()}_CODES,')
    py.append('}\n')
    py.append('''
def self_test():
    for table, codes in TABLES.items():
        values = list(codes.values())
        assert len(values) == len(set(values)), table
    return True
''')

    h = [H_HEADER, 'namespace blockheads {\nnamespace recovered {\n']
    for name, table in tables.items():
        h.append(f'enum class {table["cpp_enum"]} : std::uint8_t {{\n')
        items = sorted(table['codes'].items(), key=lambda kv: kv[1])
        for i, (ename, value) in enumerate(items):
            comma = ',' if i + 1 < len(items) else ''
            h.append(f'    {ename} = {value}{comma}\n')
        h.append('};\n')
    h.append('}  // namespace recovered\n}  // namespace blockheads\n')
    return ''.join(py), ''.join(h)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    schema = json.loads(SCHEMA.read_text())
    py, h = render(schema)
    if a.check:
        ok = PY_OUT.read_text() == py and H_OUT.read_text() == h
        if not ok:
            raise SystemExit('trace code drift: regenerate with '
                             'python3 tools/gen_trace_codes.py')
        print('trace schema check: PASS')
        return
    PY_OUT.write_text(py)
    H_OUT.parent.mkdir(parents=True, exist_ok=True)
    H_OUT.write_text(h)
    print(f'wrote {PY_OUT.relative_to(ROOT)} and {H_OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    sys.exit(main())
