#!/usr/bin/env python3
"""Generate the per-class thin-wrapper table for the nine tree-family LONG
loaders (batch b3i) from the frozen static decode.

The nine classes share ONE byte-identical body; only their per-class tail
literal cells differ. So the recovered contract is a single shared
implementation (`treefamily9_long_init_forward`) and every class is a thin
wrapper that binds its own superref / selector cells. Those cells are owned by
`reconstruction/reverse-v3/native/treefamily9_long_initwithworld.json` (the b3i
hash-gated decode), never transcribed by hand:

    python3 tools/gen_treefamily9_class_table.py           # (re)write
    python3 tools/gen_treefamily9_class_table.py --check   # CI drift gate
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = (ROOT / 'reconstruction/reverse-v3/native/'
             'treefamily9_long_initwithworld.json')
OUT = ROOT / 'reconstruction/recovered/treefamily9_long_init_classes.inc'

HEADER = '''// GENERATED by tools/gen_treefamily9_class_table.py from
// reconstruction/reverse-v3/native/treefamily9_long_initwithworld.json
// (batch b3i) -- do not edit. Each row is expanded twice by
// treefamily9_long_init_classes.h: once into kTreeForward9Classes[] and once
// into the per-class thin wrapper NAME_long_init.
// NAME, NAME_STR, IMP, BOUNDARY, SUPERREF_SLOT, SELECTOR_CELL
'''


def render(data):
    lines = [HEADER]
    for c in data['classes']:
        cells = c['literal_cells']
        lines.append(
            f'BLOCKHEADS_TREE9_ROW({c["class"]}, "{c["class"]}", '
            f'{c["imp"]}, {c["boundary"]}, '
            f'{cells["superref_slot"]}, {cells["super_selector_cell"]})\n')
    return ''.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    text = render(json.loads(JSON_PATH.read_text()))
    if a.check:
        if not OUT.exists() or OUT.read_text() != text:
            raise SystemExit('treefamily9 class table drift: regenerate with '
                             'python3 tools/gen_treefamily9_class_table.py')
        print('treefamily9 class table check: PASS')
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f'wrote {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
