#!/usr/bin/env python3
"""Generate the conditional TileType contents table for the replacement app.

Input:  reconstruction/reverse-v3/native/original_tile_conditional.json
        (produced by tools/extract_original_tile_conditional.py from the fixed
        original ARM ELF).
Output: app/src/main/cpp/generated/original_tile_conditional_table.inc

The replacement importer must never hand-transcribe this table: it is a decode
product, so `--check` fails when the committed `.inc` is stale relative to the
evidence JSON.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

KIND = {
    "contents": 0,
    "helper": 1,
    "unresolved-after-assignment": 2,
}


def render(record: dict) -> str:
    steps = []
    fallbacks = []
    # Chain ORDER matters: a step may only be reached after an earlier helper
    # gate or compare, so rows stay in extraction order per case.
    for case in record["cases"]:
        target = case["case_target"]
        for step_index, step in enumerate(case["steps"]):
            if step.get("helper") is not None:
                kind = KIND["helper"]
                contents = 0
                note = step["helper"]
            elif step.get("tail") is not None:
                kind = KIND["unresolved-after-assignment"]
                contents = step["contents_type"]
                note = ""
            else:
                kind = KIND["contents"]
                contents = step["contents_type"]
                note = ""
            for tile in case["tile_types"]:
                steps.append(
                    (tile, step_index, contents, step["item_type"], kind, target, note)
                )
        for tile in case["tile_types"]:
            fallbacks.append(
                (
                    tile,
                    -1 if case["fallback_item_type"] is None else case["fallback_item_type"],
                    target,
                    case["termination"],
                )
            )
    fallbacks.sort()

    lines = [
        "// Generated by tools/gen_tile_conditional_table.py -- do not edit.",
        "// Source: reconstruction/reverse-v3/native/original_tile_conditional.json",
        f"// Original ELF sha256: {record['elf_sha256']}",
        f"// Function: {record['function']} @ {record['function_address']}"
        f" (foreground_arg == 0 switch, table {record['table_address']})",
        "// Dependency: OriginalTile.contentsType() (original_save_format.h raw[3]).",
        "//",
        "// kind: 0 = contentsType compare step, 1 = helper-gated step (the item",
        "// type is selected by a call this map does not model), 2 = value assigned",
        "// but the block continues with further setup (unresolved tail).",
        "",
        "struct ConditionalTileStep {",
        "    unsigned short tile_type;",
        "    unsigned short contents_type;",
        "    unsigned short kind;",
        "    int item_type;",
        "    const char* case_target;",
        "};",
        "",
        "static const ConditionalTileStep kConditionalTileSteps[] = {",
    ]
    for tile, _step_index, contents, item, kind, target, note in steps:
        suffix = f"  // {note}" if note else ""
        lines.append(
            f"    {{{tile}, {contents}, {kind}, {item}, \"{target}\"}},{suffix}"
        )
    lines += [
        "};",
        "",
        "struct ConditionalTileFallback {",
        "    unsigned short tile_type;",
        "    int item_type;",
        "    const char* case_target;",
        "    const char* termination;",
        "};",
        "",
        "static const ConditionalTileFallback kConditionalTileFallbacks[] = {",
    ]
    for tile, item, target, termination in fallbacks:
        lines.append(f'    {{{tile}, {item}, "{target}", "{termination}"}},')
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "evidence",
        nargs="?",
        type=Path,
        default=Path("reconstruction/reverse-v3/native/original_tile_conditional.json"),
    )
    parser.add_argument(
        "output",
        nargs="?",
        type=Path,
        default=Path("app/src/main/cpp/original_tile_conditional_table.inc"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    record = json.loads(args.evidence.read_text(encoding="utf-8"))
    text = render(record)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != text:
            print(f"CHECK FAILED: {args.output} is stale", flush=True)
            return 1
        print(f"check ok: {args.output} matches {args.evidence}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"wrote {args.output} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
