#!/usr/bin/env python3
"""Generate a recovered layout model for one Objective-C class from the binary's own ivar table.

Four layouts were written by hand before this existed, each a fresh copy of the same template - which is how rules
drift. This writes all four pieces at once (header, .cpp, C++ contract test, Python cross-check) and registers the
test in CMakeLists behind a hit-count assertion, because a target string that occurs twice is how three CI runs went
red.

Rows come from the binary's OBJC_IVAR_$_<Class>.<name> symbols, whose payload is the ivar's runtime offset, so the
offsets are the runtime's own numbers rather than measurements. --anchors pins facts a test must keep true (e.g. a
hop another model depends on).

Usage:
  gen_layout_model.py UIManager --anchors paintMixUI=56,world=20 --note "UIManager+56 is the live-verified hop"
  gen_layout_model.py UIManager --stdout        # inspect without writing
"""
from __future__ import annotations

import argparse
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ELF = ROOT.parent.parent / "extracted/lib/armeabi-v7a/libApplication.so"


def read_table(elf: Path, cls: str) -> list[tuple[int, str, int]]:
    """(offset, name, cell) rows from OBJC_IVAR_$_<cls>.* - the runtime's own numbers."""
    from elftools.elf.elffile import ELFFile

    blob = elf.read_bytes()
    pre = f"OBJC_IVAR_$_{cls}."
    rows: list[tuple[int, str, int]] = []
    with elf.open("rb") as fh:
        for s in ELFFile(fh).get_section_by_name(".dynsym").iter_symbols():
            if s.name.startswith(pre) and s["st_value"]:
                rows.append((struct.unpack_from("<i", blob, s["st_value"])[0], s.name[len(pre):], s["st_value"]))
    rows.sort()
    return rows


HEADER = '''// Recovered model: the {cls} layout ({n} ivars, offsets {lo}..{hi}).
//
// Generated by tools/gen_layout_model.py from the binary's own OBJC_IVAR_$_{cls}.* table, so the offsets are the
// runtime's numbers rather than measurements. {note}
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace blockheads::recovered::{snake}_layout {{

struct Field {{
    std::size_t offset;
    std::string_view name;
    std::uint32_t cell;
}};

inline constexpr std::array<Field, {n}> k{cls}Fields = {{{{
{entries}
}}}};

constexpr bool offsetsRise() {{
    for (std::size_t i = 1; i < k{cls}Fields.size(); ++i)
        if (k{cls}Fields[i - 1].offset >= k{cls}Fields[i].offset) return false;
    return true;
}}
static_assert(offsetsRise(), "the ivar table must be ordered and duplicate-free");

constexpr std::size_t offsetOf(std::string_view want) {{
    for (const Field& f : k{cls}Fields)
        if (f.name == want) return f.offset;
    return static_cast<std::size_t>(-1);
}}

{asserts}

}}  // namespace blockheads::recovered::{snake}_layout
'''

CPP = '''#include "{snake}_layout.h"

namespace blockheads::recovered::{snake}_layout {{
namespace {{ static_assert(k{cls}Fields.size() == {n}); }}
}}  // namespace blockheads::recovered::{snake}_layout
'''

CTEST = '''// Contract test for the recovered {cls} layout (generated).
#include "{snake}_layout.h"

#include <cassert>
#include <cstdio>
#include <string_view>

using namespace blockheads::recovered::{snake}_layout;

int main() {{
    assert(k{cls}Fields.size() == {n});
    for (std::size_t i = 1; i < k{cls}Fields.size(); ++i)
        assert(k{cls}Fields[i - 1].offset < k{cls}Fields[i].offset);
{anchor_asserts}
    assert(offsetOf("thisIsNotAnIvar") == static_cast<std::size_t>(-1));
    std::puts("{snake}-layout: PASS");
    return 0;
}}
'''

PYTEST = '''#!/usr/bin/env python3
"""Contract test for the recovered {cls} layout (generated): re-read the ivar table and match every row.

The rule for what a row looks like lives in the generator, not here, so the two cannot drift apart.
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROW = re.compile(r'^\\s*\\{{(\\d+), "([^"]+)", (0x[0-9a-f]+)U\\}},$', re.M)


def main() -> int:
    if not (ROOT / "tools/gen_layout_model.py").is_file():
        print("skip: generator not present")
        return 0
    pinned = Path(os.environ.get("BH_ELF", ROOT.parent.parent / "extracted/lib/armeabi-v7a/libApplication.so"))
    if not pinned.is_file():
        print("skip: pinned ELF not present")
        return 0
    sys.path.insert(0, str(ROOT / "tools"))
    from gen_layout_model import read_table

    rows = read_table(pinned, "{cls}")
    hdr = (ROOT / "reconstruction/recovered/{snake}_layout.h").read_text()
    got = [(int(o), n, int(c, 16)) for o, n, c in ROW.findall(hdr)]
    assert len(got) == len(rows), (len(got), len(rows))
    for x, y in zip(got, rows):
        assert x == y, (x, y)
    print(f"{snake} layout: {{len(rows)}} ivars matched")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("cls")
    ap.add_argument("--elf", default=str(DEFAULT_ELF))
    ap.add_argument("--anchors", default="", help="name=offset pairs a static_assert must pin, e.g. paintMixUI=56")
    ap.add_argument("--note", default="")
    ap.add_argument("--stdout", action="store_true")
    a = ap.parse_args()

    snake = re.sub(r"(?<!^)(?=[A-Z])", "_", a.cls).lower()
    rec = ROOT / "reconstruction/recovered"
    rows = read_table(Path(a.elf), a.cls)
    if not rows:
        print(f"no OBJC_IVAR_$_{a.cls}.* symbols in {a.elf}")
        return 1
    byname = {r[1]: r[0] for r in rows}

    anchors: dict[str, int] = {}
    for pair in filter(None, a.anchors.split(",")):
        name, value = pair.split("=")
        value = int(value)
        if name not in byname:
            print(f"refusing: {name} is not an ivar of {a.cls}")
            return 1
        if byname[name] != value:
            print(f"refusing: anchor {name}={value} contradicts the table ({byname[name]})")
            return 1
        anchors[name] = value

    entries = "\n".join(f'    {{{o}, "{n}", {c:#010x}U}},' for o, n, c in rows)
    asserts = "\n".join(f'static_assert(offsetOf("{n}") == {v});' for n, v in anchors.items())
    anchor_asserts = "\n".join(f'    assert(offsetOf("{n}") == {v});' for n, v in anchors.items())

    header = HEADER.format(cls=a.cls, snake=snake, n=len(rows), lo=rows[0][0], hi=rows[-1][0], note=a.note,
                           entries=entries, asserts=asserts)
    if a.stdout:
        print(header)
        return 0

    (rec / f"{snake}_layout.h").write_text(header)
    (rec / f"{snake}_layout.cpp").write_text(CPP.format(cls=a.cls, snake=snake, n=len(rows)))
    (ROOT / "tools" / f"test_{snake}_layout.cpp").write_text(
        CTEST.format(cls=a.cls, snake=snake, n=len(rows), anchor_asserts=anchor_asserts))
    (ROOT / "tools" / f"test_{snake}_layout.py").write_text(PYTEST.format(cls=a.cls, snake=snake))

    # Registration must not depend on matching a substring in the source list: "action_layout.cpp)" also matched
    # inside "add_executable(test_action_layout ...)" four times over, each time taking a CI run with it. So the
    # new source is added to the existing target with target_sources, and the test block is appended at the end
    # behind an idempotence guard. Neither touches a line that already exists.
    cm = rec / "CMakeLists.txt"
    s = cm.read_text()
    guard = f"if(NOT TARGET test_{snake}_layout)"
    if guard in s:
        print(f"{a.cls}: already registered")
    else:
        s = s.rstrip() + (
            f"\n\ntarget_sources(blockheads_recovered_view PRIVATE {snake}_layout.cpp)\n"
            f"if(NOT TARGET test_{snake}_layout)\n"
            f"    add_executable(test_{snake}_layout ../../tools/test_{snake}_layout.cpp)\n"
            f"    target_link_libraries(test_{snake}_layout PRIVATE blockheads_recovered_view)\n"
            f"    target_compile_options(test_{snake}_layout PRIVATE -UNDEBUG)\n"
            f"    add_test(NAME recovered_{snake}_layout COMMAND test_{snake}_layout)\n"
            f"endif()\n")
        cm.write_text(s)
    print(f"{a.cls}: {len(rows)} ivars, header+impl+two tests written, test registered "
          f"(anchors: {anchors or 'none'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
