#!/usr/bin/env python3
"""Generate the load-time sound list the original names in World -[incrementalLoad].

The wiring map says which method references each shipped sound. One method stands out as a load-time
list rather than an event handler: `World -[incrementalLoad]` names ~30 of them in one place. That is
the natural first consumer for a replacement audio path, and it is data - so it belongs in a
generated header with a --check gate, not in hand-written code.

What this is NOT: it does not claim playback order, volume, or that these are the only sounds the
world uses. It is the exact set of names the original references from that one method, with the
shipped flag and asset sha256 so a consumer can verify bytes rather than trust a filename.

Usage:
  python3 tools/gen_sound_preload_list.py --wiring <audio_wiring_map.json> \\
      --coverage <audio_asset_coverage.json> --out reconstruction/recovered/sound_preload_list.h
  python3 tools/gen_sound_preload_list.py ... --check          # fail if the header drifted

The generator is deterministic: rows are emitted sorted by name.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

METHOD = "World -[incrementalLoad]"


def build(wiring: Path, coverage: Path) -> tuple[list[dict], dict]:
    w = json.loads(wiring.read_text())
    c = json.loads(coverage.read_text())
    sha = {r["name"]: r.get("sha256") for r in c.get("rows", [])}
    shipped = {r["name"]: r for r in c.get("rows", [])}
    rows = []
    for r in w.get("rows", []):
        if METHOD not in (r.get("methods") or []):
            continue
        rows.append({"name": r["name"],
                     "replacement_referenced": bool(r.get("replacement_referenced")),
                     "shipped": r["name"] in shipped,
                     "sha256": sha.get(r["name"]),
                     "site": (r.get("sites") or [{}])[0].get("pool_word_at")})
    rows.sort(key=lambda x: x["name"])
    meta = {"wiring_elf_sha256": w.get("elf_sha256"), "method": METHOD,
            "count": len(rows),
            "already_referenced_by_replacement": sum(1 for r in rows if r["replacement_referenced"]),
            "shipped": sum(1 for r in rows if r["shipped"]),
            "with_sha256": sum(1 for r in rows if r["sha256"])}
    return rows, meta


def render(rows: list[dict], meta: dict) -> str:
    lines = [
        "// GENERATED by tools/gen_sound_preload_list.py - do not edit by hand.",
        "// Source of record: reconstruction/reverse-v3/native/audio_wiring_map.json",
        f"// Method: {meta['method']}  (original ELF {meta['wiring_elf_sha256']})",
        f"// Names: {meta['count']}   shipped: {meta['shipped']}   "
        f"already referenced by the replacement: {meta['already_referenced_by_replacement']}",
        "//",
        "// Membership only: the original references each of these names from that one method.",
        "// Playback order/volume are NOT claimed here.",
        "#pragma once",
        "",
        "namespace blockheads::recovered {",
        "",
        "struct OriginalLoadTimeSound {",
        "    const char* name;      // shipped asset filename",
        "    const char* sha256;    // asset bytes, for verification rather than trust",
        "    bool already_wired;    // true when the replacement already references the name",
        "};",
        "",
        "inline constexpr OriginalLoadTimeSound kOriginalLoadTimeSounds[] = {",
    ]
    for r in rows:
        sh = f'"{r["sha256"]}"' if r["sha256"] else "nullptr"
        lines.append(f'    {{"{r["name"]}", {sh}, {"true" if r["replacement_referenced"] else "false"}}},')
    lines += [
        "};",
        "",
        f"inline constexpr int kOriginalLoadTimeSoundCount = {meta['count']};",
        "",
        "}  // namespace blockheads::recovered",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--wiring", type=Path, required=True)
    ap.add_argument("--coverage", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    rows, meta = build(args.wiring, args.coverage)
    if meta["count"] == 0:
        print("REFUSING: the method names no sounds - inputs are wrong or the method changed",
              file=sys.stderr)
        return 1
    if meta["with_sha256"] != meta["count"]:
        print(f"REFUSING: {meta['count'] - meta['with_sha256']} name(s) have no asset sha256",
              file=sys.stderr)
        return 1
    payload = render(rows, meta)

    if args.check:
        if not args.out.is_file():
            print(f"CHECK FAILED: {args.out} missing", file=sys.stderr)
            return 1
        if args.out.read_text() != payload:
            print(f"CHECK FAILED: {args.out} is stale", file=sys.stderr)
            return 1
        print(f"check ok: {meta['count']} load-time sounds, all with sha256")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(payload)
    print(f"wrote {args.out}: {meta['count']} names "
          f"({meta['already_referenced_by_replacement']} already wired, "
          f"{meta['count'] - meta['already_referenced_by_replacement']} to wire)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
