#!/usr/bin/env python3
"""Compare static ELF ivar-offset cells against the live realized values.

The comparison is only meaningful when the running process executes the SAME build as the
ELF being read. This tool hashes the libApplication.so file mapped in the process (from
/proc/<pid>/maps) and refuses to measure when it does not match the ELF passed in
("BUILD MISMATCH") - the check whose absence produced the invalid cross-build table
recorded in live_ivar_offset_divergence.json.

Semantics (corrected 2026-10-02): for a same-build read the cell value IS the runtime
field offset for all but the rewritten set (79 of 3793 on the audited 1.7.5 build).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import struct
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from elftools.elf.elffile import ELFFile  # noqa: E402

DEFAULT_ELF = Path(os.environ.get(
    "BH_ELF",
    "/data/data/com.termux/files/home/blockheads-work/extracted/lib/armeabi-v7a/libApplication.so"))
NATIVE = Path(__file__).resolve().parent.parent / "reconstruction/reverse-v3/native"
RW_FILE_OFF = 0x00E32000

PRIOR_MEASUREMENT = {
    "pid": 18779,
    "lib_rw_base": "0x653fc000",
    "cells_compared": 3793,
    "cells_identical": 58,
    "cells_rewritten": 3735,
    "verdict": "INVALID - read a 1.7.5 process at 1.7.6 symbol addresses (uniform +0x50 shift)",
}
CORRECTION_EVIDENCE = [
    "reading the process at the prior measurement's exact relative addresses reproduces all 3793 prior values (same build)",
    "va176 - va175 == +0x50 for all 3793 ivar symbols",
    "prior values equal the cell values of the symbols 0x50 later (Blockhead.state 728 == skinOptions; bodyCube 516 == prevFromSquare; floatPos 36 == FishingRod.hookPos)",
]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def ivar_symbols(fp) -> dict:
    e = ELFFile(fp)
    out = {}
    for s in e.get_section_by_name(".dynsym").iter_symbols():
        if s.name.startswith("OBJC_IVAR_$_") and s["st_value"]:
            out[s.name[len("OBJC_IVAR_$_"):]] = s["st_value"]
    return out


def find_target():
    pid = subprocess.check_output(["pidof", "com.noodlecake.blockheads"]).decode().split()[0]
    base_rw = None
    lib_path = None
    with open(f"/proc/{pid}/maps") as fh:
        for line in fh:
            if "libApplication.so" in line and "rw-p" in line:
                base_rw = int(line.split("-")[0], 16)
                lib_path = line.split()[-1]
                break
    return pid, base_rw, lib_path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--elf", type=Path, default=DEFAULT_ELF)
    ap.add_argument("--allow-build-mismatch", action="store_true",
                    help="measure anyway (result is NOT a realization reading)")
    args = ap.parse_args()

    pid, base_rw, lib_path = find_target()
    want_sha = sha256(args.elf)
    live_sha = None
    if lib_path and Path(lib_path).exists():
        live_sha = sha256(Path(lib_path))
    if live_sha != want_sha:
        print(f"BUILD MISMATCH: live {lib_path} sha256 {live_sha}")
        print(f"               != ELF {args.elf} sha256 {want_sha}")
        if not args.allow_build_mismatch:
            print("refusing to measure across builds (pass --allow-build-mismatch to override)")
            return 2

    with args.elf.open("rb") as fh:
        syms = ivar_symbols(fh)
    blob = args.elf.read_bytes()
    static = {}
    for name, addr in syms.items():
        if addr + 4 <= len(blob):
            static[name] = struct.unpack_from("<i", blob, addr)[0]

    fd = os.open(f"/proc/{pid}/mem", os.O_RDONLY)
    live = {}
    try:
        for name, addr in syms.items():
            try:
                b = os.pread(fd, 4, base_rw + (addr - RW_FILE_OFF))
            except OSError:
                continue
            if len(b) == 4:
                live[name] = struct.unpack("<i", b)[0]
    finally:
        os.close(fd)

    same = [k for k in live if k in static and static[k] == live[k]]
    diff = [(k, static[k], live[k]) for k in sorted(live)
            if k in static and static[k] != live[k]]
    print(f"pid={pid} base_rw=0x{base_rw:x}")
    print(f"compared {len(live)} ivar storage cells: {len(same)} identical, {len(diff)} rewritten")

    payload = {
        "schema": 2,
        "status": "regenerated by tools/probe_live_ivar_offsets.py on a same-build process",
        "prior_measurement": PRIOR_MEASUREMENT,
        "correction_evidence": CORRECTION_EVIDENCE,
        "corrected_same_build": {
            "build": live_sha,
            "cells_compared": len(live),
            "cells_identical": len(same),
            "cells_rewritten": len(diff),
            "rewritten_list": [{"ivar": k, "file": s, "live": l} for k, s, l in diff],
            "note": ("rewrites concentrate in UIKit-inherited classes whose realized layout "
                     "differs (EAGLView +144, UIView +4, UISegment +196, ...)"),
        },
        "semantics": ("for a same-build read the cell value IS the runtime field offset for "
                      "all but the rewritten set; see IVAR_OFFSET_READING.md and "
                      "live_verified_fields.json"),
        "verified_fields_artifact": "live_verified_fields.json",
    }
    out = NATIVE / "live_ivar_offset_divergence.json"
    out.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
