import json
import sys
import os

def generate_code(json_path, header_path, source_path):
    with open(json_path, 'r') as f:
        items = json.load(f)

    # 1. Sort items by ID to find the max ID for array sizing
    max_id = 0
    for item in items:
        if item['id'] > max_id:
            max_id = item['id']
    
    array_size = max_id + 1

    # 2. Generate Header (Item IDs Enum)
    with open(header_path, 'w') as h:
        h.write("#ifndef GAME_ITEM_IDS_H\n")
        h.write("#define GAME_ITEM_IDS_H\n\n")
        h.write("// Auto-generated by process_items.py. DO NOT EDIT.\n\n")
        h.write("enum ItemID {\n")
        h.write("    ITEM_AIR = 0,\n")
        
        for item in items:
            h.write(f"    {item['string_id']} = {item['id']},\n")
            
        h.write(f"    ITEM_COUNT_MAX = {array_size}\n")
        h.write("\n};")
        h.write("\n#endif // GAME_ITEM_IDS_H\n")

    # 3. Generate Source (Data Array)
    with open(source_path, 'w') as c:
        c.write('#include "item_manager.h"\n')
        c.write('#include "game_item_ids.h"\n\n')
        c.write("// Auto-generated by process_items.py. DO NOT EDIT.\n\n")
        
        c.write(f"ItemManager::ItemDef g_itemDefs[{array_size}] = {{\n")
        
        # Initialize default empty items
        c.write("    // Default initialization for empty slots implicitly handled by C++ zero-init\n")
        
        for item in items:
            is_block = "true" if item.get('isBlock', False) else "false"
            is_food = "true" if item.get('isFood', False) else "false"
            hunger = item.get('hunger', 0.0)
            tool_power = item.get('tool', 0)
            
            c.write(f"    [{item['string_id']}] = {{ ")
            c.write(f"{item['id']}, \"{item['name']}\", {item['texRow']}, {item['texCol']}, ")
            c.write(f"{is_block}, {is_food}, {hunger}f, {tool_power} ")
            c.write("},")
            
        c.write("};\n")

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python process_items.py <items.json> <output_header> <output_source>")
        sys.exit(1)
        
    generate_code(sys.argv[1], sys.argv[2], sys.argv[3])
