import json
import sys
import os

def generate_code(items_json_path, recipes_json_path, item_header_path, item_source_path, recipe_header_path, recipe_source_path):
    # --- Process Items ---
    with open(items_json_path, 'r') as f:
        items = json.load(f)

    # 1. Sort items by ID to find the max ID for array sizing
    max_id = 0
    item_id_map = {} # Map string_id -> int ID for recipe resolution
    
    for item in items:
        if item['id'] > max_id:
            max_id = item['id']
        item_id_map[item['string_id']] = item['id']
    
    # Add special ITEM_AIR if not present
    if "ITEM_AIR" not in item_id_map:
         item_id_map["ITEM_AIR"] = 0

    array_size = max_id + 1

    # 2. Generate Item Header (Item IDs Enum)
    with open(item_header_path, 'w') as h:
        h.write("#ifndef GAME_ITEM_IDS_H\n")
        h.write("#define GAME_ITEM_IDS_H\n\n")
        h.write("// Auto-generated by process_items.py. DO NOT EDIT.\n\n")
        h.write("enum ItemID {\n")
        h.write("    ITEM_AIR = 0,\n")
        
        for item in items:
            h.write(f"    {item['string_id']} = {item['id']},\n")
            
        h.write(f"    ITEM_COUNT_MAX = {array_size}\n")
        h.write("\n};\n")
        h.write("#endif // GAME_ITEM_IDS_H\n")

    # 3. Generate Item Source (Data Array)
    with open(item_source_path, 'w') as c:
        c.write('#include "item_manager.h"\n')
        c.write('#include "game_item_ids.h"\n\n')
        c.write("// Auto-generated by process_items.py. DO NOT EDIT.\n\n")
        
        c.write(f"ItemManager::ItemDef g_itemDefs[{array_size}] = {{\n")
        
        # Create a list for all IDs up to max_id, default to empty
        full_list = [None] * array_size
        for item in items:
            full_list[item['id']] = item

        for i in range(array_size):
            item = full_list[i]
            if item is None:
                c.write(f"    {{ {i}, \"Unknown\", 0, 0, false, false, 0.0f, 0, 0 }},\n")
            else:
                is_block = "true" if item.get('isBlock', False) else "false"
                is_food = "true" if item.get('isFood', False) else "false"
                hunger = item.get('hunger', 0.0)
                tool_power = item.get('tool', 0)
                render_type = item.get('renderType', 0)
                c.write(f"    {{ {item['id']}, \"{item['name']}\", {item['texRow']}, {item['texCol']}, ")
                c.write(f"{is_block}, {is_food}, {hunger}f, {tool_power}, {render_type} }},\n")
            
        c.write("};\n")

    # --- Process Recipes ---
    with open(recipes_json_path, 'r') as f:
        recipes = json.load(f)

    # 4. Generate Recipe Header
    with open(recipe_header_path, 'w') as h:
        h.write("#ifndef GAME_RECIPE_DATA_H\n")
        h.write("#define GAME_RECIPE_DATA_H\n\n")
        h.write("#include <vector>\n")
        h.write("#include <string>\n")
        h.write('#include "game_item_ids.h"\n\n')
        h.write("// Auto-generated by process_items.py. DO NOT EDIT.\n\n")
        
        h.write("struct RecipeData {\n")
        h.write("    int id;\n")
        h.write("    const char* name;\n")
        h.write("    int outType;\n")
        h.write("    int outCount;\n")
        h.write("    struct Ingredient { int itemId; int count; };\n")
        h.write("    Ingredient ingredients[4]; // Fixed max ingredients for static struct\n")
        h.write("    int ingredientCount;\n")
        h.write("    int requiredBench;\n")
        h.write("    float time;\n")
        h.write("};\n\n")
        
        h.write("extern const RecipeData g_recipeData[];\n")
        h.write(f"const int g_recipeCount = {len(recipes)};\n")
        h.write("\n#endif // GAME_RECIPE_DATA_H\n")

    # 5. Generate Recipe Source
    with open(recipe_source_path, 'w') as c:
        c.write('#include "game_recipe_data.h"\n\n')
        c.write("// Auto-generated by process_items.py. DO NOT EDIT.\n\n")
        
        c.write("const RecipeData g_recipeData[] = {\n")
        
        for r in recipes:
            # Resolve Item IDs
            out_id = item_id_map.get(r['out'])
            if out_id is None:
                print(f"Error: Unknown output item {r['out']} in recipe {r['id']}")
                sys.exit(1)
                
            c.write(f"    {{ {r['id']}, \"{r['name']}\", {out_id}, {r['count']}, {{")
            
            ing_count = 0
            for ing in r['ingredients']:
                ing_id = item_id_map.get(ing['item'])
                if ing_id is None:
                     print(f"Error: Unknown ingredient {ing['item']} in recipe {r['id']}")
                     sys.exit(1)
                c.write(f"{{ {ing_id}, {ing['count']} }}, ")
                ing_count += 1
            
            # Fill remaining slots with 0
            for _ in range(4 - ing_count):
                c.write("{ 0, 0 }, ")
                
            c.write(f"}}, {ing_count}, {r['bench']}, {r['time']}f }},\n")
            
        c.write("};\n")

if __name__ == "__main__":
    if len(sys.argv) < 7:
        print("Usage: python process_items.py <items.json> <recipes.json> <out_item_h> <out_item_cpp> <out_recipe_h> <out_recipe_cpp>")
        sys.exit(1)
        
    generate_code(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6])
