#!/usr/bin/env python3
"""Hash-gated recovery of the DynamicWorld block-load/accessor smalls (E35).

The plants line opens: the ten fruit trees smalls sweep: the repair removal, the client-
blockhead receive, the portal checks, the loaded-count, the gather pair, the
client/server booleans, the net/all-blockhead merges, the portal-positions and
blockheads getters and the connection-loss stub:
1 body, 1463 instruction words, from the pinned original libApplication.so
(1.7.6, armeabi-v7a).  Every instruction word is re-verified; tool refuses to
emit on drift.

Verification rules (each one is a claim this file makes about its own evidence):
  * coverage    - the checked-in listing must cover [start, end) exactly once per word,
                  and every word is re-read from the pinned ELF.
  * PIC base    - recomputed from the `add rX, pc, rY` anchor and its pool literal;
                  must equal 0x0105faf4.
  * cells       - selector cells: the slot is base + signed(pool value) and the C string
                  it points at must be the named selector.  Import cells: the slot must be
                  a PLT/GOT slot whose relocation names the import, or - for functions
                  reached through an ABS32 relocation - a relocation whose symbol names
                  it (the route used is recorded per cell).  Ivar cells: the slot
                  holds a pointer to OBJC_IVAR_$_<Class>.<name> in .dynsym plus the
                  offset word.  Class cells: the slot either holds the OBJC_CLASS_$_
                  symbol value (.dynsym) or - for classes imported from the system
                  frameworks - carries an ABS32 relocation whose symbol is the class;
                  both routes are checked, the relocation route is named when used.
  * calls       - the set of bl/blx rows inside the body must equal the spec's set, and
                  every `bl <name>` route's computed target must match ROUTE_TARGETS.
  * branches    - the set of conditional/unconditional b* rows whose destination lands
                  inside the body must equal the spec's set.  Rows outside the body are
                  literal-pool words that mask as branches; they are recorded in
                  `disjoint_branch_rows` instead of being silently dropped.
  * anchors     - the listed instruction texts must match the listing byte for byte.

Machine-generated spec tables + hand-written semantics; see
reconstruction/reverse-v3/native/TREE_SMALLS.md for the prose and boundaries.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import sys
from pathlib import Path

from elftools.elf.elffile import ELFFile
from elftools.elf.relocation import RelocationSection

sys.path.insert(0, str(Path(__file__).resolve().parent))
from trace_objc_dispatch import ELFMemory
from recover_drawframe_slices import verify_disassembly

ROOT = Path(__file__).resolve().parents[1]
NATIVE = ROOT / 'reconstruction/reverse-v3/native'
EXPECTED_SHA = '733d821027d69de329d0ba171df2e6013d612edf5a4d327badd001acc30b94c7'
EXPECTED_BASE = 0x0105FAF4

ROUTE_TARGETS = {
    'bl loc.imp.objc_msgSend': 0x001c281c,
}

SPECS = [
    dict(
        name='cf_objecttype',
        method='CoffeeTree -[objectType]',
        types='i8@0:4',
        start=8249688,
        end=8249744,
        disasm='disasm_worldtileloader_cf_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x007de190 (listing bound); next ObjC IMP 0x007de174 CoffeeTree -[fruitItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8249688, 'sub sp, sp, 8'), (8249740, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[CoffeeTree objectType] (imp 0x007de158, 14w): returns **0x4e (78)** - the CoffeeTree's dynamic-object type code.\n"),
    ),
    dict(
        name='cf_fruititem',
        method='CoffeeTree -[fruitItemType]',
        types='i8@0:4',
        start=8249716,
        end=8249744,
        disasm='disasm_worldtileloader_cf_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x007de190 (listing bound); next ObjC IMP 0x007de190 CoffeeTree -[fruitShouldFallInSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8249716, 'sub sp, sp, 8'), (8249740, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CoffeeTree fruitItemType] (imp 0x007de174, 7w): returns **0x4e (78)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='cf_fruitseason',
        method='CoffeeTree -[fruitShouldFallInSeason:]',
        types='c12@0:4i8',
        start=8249744,
        end=8249792,
        disasm='disasm_worldtileloader_cf_fruitseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x007de1c0 (listing bound); next ObjC IMP 0x007de1c0 CoffeeTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8249744, 'sub sp, sp, 0xc'), (8249788, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CoffeeTree fruitShouldFallInSeason:] (imp 0x007de190, 12w): the season equality gate - `cmp r0, 3; moveq 1` (E85 read: the apple checks season 3); the patterned `cmp rN, k; movw r0, 0; moveq r0, 1; and; sxtb` shape returns the boolean.\n'),
    ),
    dict(
        name='cf_getsavedict',
        method='CoffeeTree -[getSaveDict]',
        types='@8@0:4',
        start=8252448,
        end=8252576,
        disasm='disasm_worldtileloader_cf_getsavedict.txt',
        base_add=8252464,
        base_literal=8252568,
        boundary='ARM.exidx end 0x007deca0 (listing bound); next ObjC IMP 0x007deca0 CoffeeTree -[updateGrowth:]',
        selectors={
                 0x7dec90: (15210744, 'getSaveDict'),
        },
        imports={
                 0x7dec8c: (17151900, 'objc_msgSendSuper2'),
        },
        ivars={},
        classes={
                 0x7dec94: (15252824, 'OBJC_CLASS_$_CoffeeTree'),
        },
        instructions=[(8252448, 'push {r4, sl, fp, lr}'), (8252572, 'andeq r0, r0, r0')],
        calls=[(8252528, 'blx ip')],
        branches=[],
        semantics=('[CoffeeTree getSaveDict] (imp 0x007dec20, 32w): the save-dict forwarder - ffffbca8 super + the class chain (ffe28998/ffe2c414 family) builds the dict from the tree state.\n'),
    ),
    dict(
        name='cf_makedead',
        method='CoffeeTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=8260644,
        end=8260748,
        disasm='disasm_worldtileloader_cf_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x007e0c8c (listing bound); next ObjC IMP 0x007e0c8c CoffeeTree -[update:accurateDT:isSimulation:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8260644, 'sub sp, sp, 0xc'), (8260744, 'bx lr')],
        calls=[],
        branches=[(8260672, 'bne', 8260692), (8260688, 'b', 8260740), (8260704, 'beq', 8260724), (8260720, 'bne', 8260736), (8260736, 'b', 8260740)],
        semantics=('[CoffeeTree makeTileDead:] (imp 0x007e0c24, 26w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (24/25/26) writes the DEAD markers (0x29/0x2a) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='cf_treetype',
        method='CoffeeTree -[treeType]',
        types='i8@0:4',
        start=8262504,
        end=8262532,
        disasm='disasm_worldtileloader_cf_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x007e1384 (listing bound); next ObjC IMP 0x007e1384 CoffeeTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8262504, 'sub sp, sp, 8'), (8262528, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CoffeeTree treeType] (imp 0x007e1368, 7w): returns **0x4e** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='cf_kindself',
        method='CoffeeTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=8262532,
        end=8262688,
        disasm='disasm_worldtileloader_cf_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x007e1420 (listing bound); next ObjC IMP 0x007e1580 TipManager -[instance]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8262532, 'sub sp, sp, 0x10'), (8262684, 'bx lr')],
        calls=[],
        branches=[(8262568, 'beq', 8262668), (8262592, 'beq', 8262668), (8262616, 'beq', 8262668), (8262640, 'beq', 8262668)],
        semantics=("[CoffeeTree tileIsKindOfSelf:] (imp 0x007e1384, 39w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x29/0x2a family) and the generic marker arm.\n"),
    ),
    dict(
        name='lt_objecttype',
        method='LimeTree -[objectType]',
        types='i8@0:4',
        start=8426000,
        end=8426056,
        disasm='disasm_worldtileloader_lt_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00809248 (listing bound); next ObjC IMP 0x0080922c LimeTree -[fruitItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8426000, 'sub sp, sp, 8'), (8426052, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[LimeTree objectType] (imp 0x00809210, 14w): returns **0xa0 (160)** - the LimeTree's dynamic-object type code.\n"),
    ),
    dict(
        name='lt_fruititem',
        method='LimeTree -[fruitItemType]',
        types='i8@0:4',
        start=8426028,
        end=8426056,
        disasm='disasm_worldtileloader_lt_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00809248 (listing bound); next ObjC IMP 0x00809248 LimeTree -[fruitShouldFallInSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8426028, 'sub sp, sp, 8'), (8426052, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[LimeTree fruitItemType] (imp 0x0080922c, 7w): returns **0xa0 (160)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='lt_fruitseason',
        method='LimeTree -[fruitShouldFallInSeason:]',
        types='c12@0:4i8',
        start=8426056,
        end=8426104,
        disasm='disasm_worldtileloader_lt_fruitseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00809278 (listing bound); next ObjC IMP 0x00809278 LimeTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8426056, 'sub sp, sp, 0xc'), (8426100, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[LimeTree fruitShouldFallInSeason:] (imp 0x00809248, 12w): the season equality gate - `cmp r0, 3; moveq 1` (E85 read: the apple checks season 3); the patterned `cmp rN, k; movw r0, 0; moveq r0, 1; and; sxtb` shape returns the boolean.\n'),
    ),
    dict(
        name='lt_getsavedict',
        method='LimeTree -[getSaveDict]',
        types='@8@0:4',
        start=8428852,
        end=8428976,
        disasm='disasm_worldtileloader_lt_getsavedict.txt',
        base_add=8428868,
        base_literal=8428972,
        boundary='ARM.exidx end 0x00809db0 (listing bound); next ObjC IMP 0x00809db0 LimeTree -[updateGrowth:]',
        selectors={
                 0x809da4: (15211612, 'getSaveDict'),
        },
        imports={
                 0x809da0: (17151900, 'objc_msgSendSuper2'),
        },
        ivars={},
        classes={
                 0x809da8: (15252836, 'OBJC_CLASS_$_LimeTree'),
        },
        instructions=[(8428852, 'push {r4, sl, fp, lr}'), (8428972, 'addeq r5, r5, r8, lsr 27')],
        calls=[(8428932, 'blx ip')],
        branches=[],
        semantics=('[LimeTree getSaveDict] (imp 0x00809d34, 31w): the save-dict forwarder - ffffbca8 super + the class chain (ffe28998/ffe2c414 family) builds the dict from the tree state.\n'),
    ),
    dict(
        name='lt_makedead',
        method='LimeTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=8438696,
        end=8438800,
        disasm='disasm_worldtileloader_lt_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x0080c410 (listing bound); next ObjC IMP 0x0080c410 LimeTree -[treeType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8438696, 'sub sp, sp, 0xc'), (8438796, 'bx lr')],
        calls=[],
        branches=[(8438724, 'bne', 8438744), (8438740, 'b', 8438792), (8438756, 'beq', 8438776), (8438772, 'bne', 8438788), (8438788, 'b', 8438792)],
        semantics=('[LimeTree makeTileDead:] (imp 0x0080c3a8, 26w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (89/90/91) writes the DEAD markers (0x5c/0x5d) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='lt_treetype',
        method='LimeTree -[treeType]',
        types='i8@0:4',
        start=8438800,
        end=8438828,
        disasm='disasm_worldtileloader_lt_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x0080c42c (listing bound); next ObjC IMP 0x0080c42c LimeTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8438800, 'sub sp, sp, 8'), (8438824, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[LimeTree treeType] (imp 0x0080c410, 7w): returns **0xa** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='lt_kindself',
        method='LimeTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=8438828,
        end=8438984,
        disasm='disasm_worldtileloader_lt_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x0080c4c8 (listing bound); next ObjC IMP 0x0080c628 PetUI -[loadResources]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(8438828, 'sub sp, sp, 0x10'), (8438980, 'bx lr')],
        calls=[],
        branches=[(8438864, 'beq', 8438964), (8438888, 'beq', 8438964), (8438912, 'beq', 8438964), (8438936, 'beq', 8438964)],
        semantics=("[LimeTree tileIsKindOfSelf:] (imp 0x0080c42c, 39w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x5c/0x5d family) and the generic marker arm.\n"),
    ),
    dict(
        name='at_availfood',
        method='AppleTree -[availableFood]',
        types='f8@0:4',
        start=10209532,
        end=10209596,
        disasm='disasm_worldtileloader_at_availfood.txt',
        base_add=10209556,
        base_literal=10209592,
        boundary='ARM.exidx end 0x009bc93c (listing bound); next ObjC IMP 0x009bc93c AppleTree -[setAvailableFood:]',
        selectors={},
        imports={},
        ivars={
                 0x9bc934: (17163660, 'OBJC_IVAR_$_AppleTree.availableFood', 136),
        },
        classes={},
        instructions=[(10209532, 'sub sp, sp, 8'), (10209592, 'invalid')],
        calls=[],
        branches=[],
        semantics=('[AppleTree availableFood] (imp 0x009bc8fc, 16w): the float member read - vldr s0 from the ivar (ffffff ea98-family cell) and `vmov r0, s0`; the unclassified cell ffff ea98 is the float-ivar base.\n'),
    ),
    dict(
        name='at_setavailfood',
        method='AppleTree -[setAvailableFood:]',
        types='v12@0:4f8',
        start=10209596,
        end=10209800,
        disasm='disasm_worldtileloader_at_setavailfood.txt',
        base_add=10209636,
        base_literal=10209780,
        boundary='ARM.exidx end 0x009bca08 (listing bound); next ObjC IMP 0x009bca08 AppleTree -[fruitItemType]',
        selectors={
                 0x9bca00: (15221088, 'objectType'),
                 0x9bca04: (15221092, 'dynamicWorldChangedAtPos:objectType:'),
        },
        imports={},
        ivars={
                 0x9bc9f0: (17163660, 'OBJC_IVAR_$_AppleTree.availableFood', 136),
                 0x9bc9f8: (17154984, 'OBJC_IVAR_$_DynamicObject.dynamicWorld', 8),
                 0x9bc9fc: (17154960, 'OBJC_IVAR_$_DynamicObject.pos', 16),
        },
        classes={},
        instructions=[(10209596, 'push {fp, lr}'), (10209796, 'invalid')],
        calls=[(10209728, 'bl loc.imp.objc_msgSend'), (10209764, 'bl loc.imp.objc_msgSend')],
        branches=[],
        semantics=('[AppleTree setAvailableFood:] (imp 0x009bc93c, 51w): the float member write (vstr) then the ffffc8b4/ffffc89c dirty chain + ffe2466c notify (@0x9bc9c0).\n'),
    ),
    dict(
        name='at_fruititem',
        method='AppleTree -[fruitItemType]',
        types='i8@0:4',
        start=10209800,
        end=10209828,
        disasm='disasm_worldtileloader_at_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bca24 (listing bound); next ObjC IMP 0x009bca24 AppleTree -[fruitShouldFallInSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10209800, 'sub sp, sp, 8'), (10209824, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[AppleTree fruitItemType] (imp 0x009bca08, 7w): returns **0x15 (21)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='at_fruitseason',
        method='AppleTree -[fruitShouldFallInSeason:]',
        types='c12@0:4i8',
        start=10209828,
        end=10209876,
        disasm='disasm_worldtileloader_at_fruitseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bca54 (listing bound); next ObjC IMP 0x009bca54 AppleTree -[objectType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10209828, 'sub sp, sp, 0xc'), (10209872, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[AppleTree fruitShouldFallInSeason:] (imp 0x009bca24, 12w): the season equality gate - `cmp r0, 3; moveq 1` (E85 read: the apple checks season 3); the patterned `cmp rN, k; movw r0, 0; moveq r0, 1; and; sxtb` shape returns the boolean.\n'),
    ),
    dict(
        name='at_objecttype',
        method='AppleTree -[objectType]',
        types='i8@0:4',
        start=10209876,
        end=10209904,
        disasm='disasm_worldtileloader_at_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bca70 (listing bound); next ObjC IMP 0x009bca70 AppleTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10209876, 'sub sp, sp, 8'), (10209900, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[AppleTree objectType] (imp 0x009bca54, 7w): returns **0x1 (1)** - the AppleTree's dynamic-object type code.\n"),
    ),
    dict(
        name='at_makedead',
        method='AppleTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=10220936,
        end=10221040,
        disasm='disasm_worldtileloader_at_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bf5f0 (listing bound); next ObjC IMP 0x009bf5f0 AppleTree -[update:accurateDT:isSimulation:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10220936, 'sub sp, sp, 0xc'), (10221036, 'bx lr')],
        calls=[],
        branches=[(10220964, 'bne', 10220984), (10220980, 'b', 10221032), (10220996, 'beq', 10221016), (10221012, 'bne', 10221028), (10221028, 'b', 10221032)],
        semantics=('[AppleTree makeTileDead:] (imp 0x009bf588, 26w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (3/4/5) writes the DEAD markers (0x1b/0x1c) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='at_treetype',
        method='AppleTree -[treeType]',
        types='i8@0:4',
        start=10223380,
        end=10223408,
        disasm='disasm_worldtileloader_at_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bff30 (listing bound); next ObjC IMP 0x009bff30 AppleTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10223380, 'sub sp, sp, 8'), (10223404, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[AppleTree treeType] (imp 0x009bff14, 7w): returns **0x1** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='at_kindself',
        method='AppleTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=10223408,
        end=10223564,
        disasm='disasm_worldtileloader_at_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bffcc (listing bound); next ObjC IMP 0x009c012c ShareUI -[initWithWorld:windowInfo:cache:pauseUI:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10223408, 'sub sp, sp, 0x10'), (10223560, 'bx lr')],
        calls=[],
        branches=[(10223444, 'beq', 10223544), (10223468, 'beq', 10223544), (10223492, 'beq', 10223544), (10223516, 'beq', 10223544)],
        semantics=("[AppleTree tileIsKindOfSelf:] (imp 0x009bff30, 39w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x1b/0x1c family) and the generic marker arm.\n"),
    ),
    dict(
        name='ot_objecttype',
        method='OrangeTree -[objectType]',
        types='i8@0:4',
        start=11099096,
        end=11099152,
        disasm='disasm_worldtileloader_ot_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a95c10 (listing bound); next ObjC IMP 0x00a95bf4 OrangeTree -[fruitItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11099096, 'sub sp, sp, 8'), (11099148, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[OrangeTree objectType] (imp 0x00a95bd8, 14w): returns **0x3c (60)** - the OrangeTree's dynamic-object type code.\n"),
    ),
    dict(
        name='ot_fruititem',
        method='OrangeTree -[fruitItemType]',
        types='i8@0:4',
        start=11099124,
        end=11099152,
        disasm='disasm_worldtileloader_ot_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a95c10 (listing bound); next ObjC IMP 0x00a95c10 OrangeTree -[fruitShouldFallInSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11099124, 'sub sp, sp, 8'), (11099148, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[OrangeTree fruitItemType] (imp 0x00a95bf4, 7w): returns **0x3c (60)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='ot_fruitseason',
        method='OrangeTree -[fruitShouldFallInSeason:]',
        types='c12@0:4i8',
        start=11099152,
        end=11099200,
        disasm='disasm_worldtileloader_ot_fruitseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a95c40 (listing bound); next ObjC IMP 0x00a95c40 OrangeTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11099152, 'sub sp, sp, 0xc'), (11099196, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[OrangeTree fruitShouldFallInSeason:] (imp 0x00a95c10, 12w): the season equality gate - `cmp r0, 3; moveq 1` (E85 read: the apple checks season 3); the patterned `cmp rN, k; movw r0, 0; moveq r0, 1; and; sxtb` shape returns the boolean.\n'),
    ),
    dict(
        name='ot_getsavedict',
        method='OrangeTree -[getSaveDict]',
        types='@8@0:4',
        start=11101948,
        end=11102072,
        disasm='disasm_worldtileloader_ot_getsavedict.txt',
        base_add=11101964,
        base_literal=11102068,
        boundary='ARM.exidx end 0x00a96778 (listing bound); next ObjC IMP 0x00a96778 OrangeTree -[updateGrowth:]',
        selectors={
                 0xa9676c: (15226172, 'getSaveDict'),
        },
        imports={
                 0xa96768: (17151900, 'objc_msgSendSuper2'),
        },
        ivars={},
        classes={
                 0xa96770: (15253068, 'OBJC_CLASS_$_OrangeTree'),
        },
        instructions=[(11101948, 'push {r4, sl, fp, lr}'), (11102068, 'subseq sb, ip, r0, ror 7')],
        calls=[(11102028, 'blx ip')],
        branches=[],
        semantics=('[OrangeTree getSaveDict] (imp 0x00a966fc, 31w): the save-dict forwarder - ffffbca8 super + the class chain (ffe28998/ffe2c414 family) builds the dict from the tree state.\n'),
    ),
    dict(
        name='ot_makedead',
        method='OrangeTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=11111792,
        end=11111896,
        disasm='disasm_worldtileloader_ot_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a98dd8 (listing bound); next ObjC IMP 0x00a98dd8 OrangeTree -[treeType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11111792, 'sub sp, sp, 0xc'), (11111892, 'bx lr')],
        calls=[],
        branches=[(11111820, 'bne', 11111840), (11111836, 'b', 11111888), (11111852, 'beq', 11111872), (11111868, 'bne', 11111884), (11111884, 'b', 11111888)],
        semantics=('[OrangeTree makeTileDead:] (imp 0x00a98d70, 26w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (18/19/20) writes the DEAD markers (0x25/0x26) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='ot_treetype',
        method='OrangeTree -[treeType]',
        types='i8@0:4',
        start=11111896,
        end=11111924,
        disasm='disasm_worldtileloader_ot_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a98df4 (listing bound); next ObjC IMP 0x00a98df4 OrangeTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11111896, 'sub sp, sp, 8'), (11111920, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[OrangeTree treeType] (imp 0x00a98dd8, 7w): returns **0x3c** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='ot_kindself',
        method='OrangeTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=11111924,
        end=11112080,
        disasm='disasm_worldtileloader_ot_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a98e90 (listing bound); next ObjC IMP 0x00a98ff0 CoconutTree -[objectType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11111924, 'sub sp, sp, 0x10'), (11112076, 'bx lr')],
        calls=[],
        branches=[(11111960, 'beq', 11112060), (11111984, 'beq', 11112060), (11112008, 'beq', 11112060), (11112032, 'beq', 11112060)],
        semantics=("[OrangeTree tileIsKindOfSelf:] (imp 0x00a98df4, 39w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x25/0x26 family) and the generic marker arm.\n"),
    ),
    dict(
        name='cn_objecttype',
        method='CoconutTree -[objectType]',
        types='i8@0:4',
        start=11112432,
        end=11112488,
        disasm='disasm_worldtileloader_cn_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a99028 (listing bound); next ObjC IMP 0x00a9900c CoconutTree -[fruitItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11112432, 'sub sp, sp, 8'), (11112484, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[CoconutTree objectType] (imp 0x00a98ff0, 14w): returns **0x2e (46)** - the CoconutTree's dynamic-object type code.\n"),
    ),
    dict(
        name='cn_fruititem',
        method='CoconutTree -[fruitItemType]',
        types='i8@0:4',
        start=11112460,
        end=11112488,
        disasm='disasm_worldtileloader_cn_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a99028 (listing bound); next ObjC IMP 0x00a99028 CoconutTree -[fruitShouldFallInSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11112460, 'sub sp, sp, 8'), (11112484, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CoconutTree fruitItemType] (imp 0x00a9900c, 7w): returns **0x2e (46)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='cn_fruitseason',
        method='CoconutTree -[fruitShouldFallInSeason:]',
        types='c12@0:4i8',
        start=11112488,
        end=11112608,
        disasm='disasm_worldtileloader_cn_fruitseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a990a0 (listing bound); next ObjC IMP 0x00a990a0 CoconutTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11112488, 'sub sp, sp, 0x10'), (11112604, 'andeq r0, r0, r0')],
        calls=[],
        branches=[(11112520, 'beq', 11112584), (11112540, 'beq', 11112584), (11112560, 'beq', 11112584)],
        semantics=('[CoconutTree fruitShouldFallInSeason:] (imp 0x00a99028, 30w): the season equality gate - `cmp r0, 3; moveq 1` (E85 read: the apple checks season 3); the patterned `cmp rN, k; movw r0, 0; moveq r0, 1; and; sxtb` shape returns the boolean.\n'),
    ),
    dict(
        name='cn_getsavedict',
        method='CoconutTree -[getSaveDict]',
        types='@8@0:4',
        start=11115188,
        end=11115312,
        disasm='disasm_worldtileloader_cn_getsavedict.txt',
        base_add=11115204,
        base_literal=11115308,
        boundary='ARM.exidx end 0x00a99b30 (listing bound); next ObjC IMP 0x00a99b30 CoconutTree -[updateGrowth:]',
        selectors={
                 0xa99b24: (15226268, 'getSaveDict'),
        },
        imports={
                 0xa99b20: (17151900, 'objc_msgSendSuper2'),
        },
        ivars={},
        classes={
                 0xa99b28: (15253072, 'OBJC_CLASS_$_CoconutTree'),
        },
        instructions=[(11115188, 'push {r4, sl, fp, lr}'), (11115308, 'subseq r6, ip, r8, lsr 32')],
        calls=[(11115268, 'blx ip')],
        branches=[],
        semantics=('[CoconutTree getSaveDict] (imp 0x00a99ab4, 31w): the save-dict forwarder - ffffbca8 super + the class chain (ffe28998/ffe2c414 family) builds the dict from the tree state.\n'),
    ),
    dict(
        name='cn_makedead',
        method='CoconutTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=11121256,
        end=11121360,
        disasm='disasm_worldtileloader_cn_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a9b2d0 (listing bound); next ObjC IMP 0x00a9b2d0 CoconutTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11121256, 'sub sp, sp, 0xc'), (11121356, 'bx lr')],
        calls=[],
        branches=[(11121284, 'bne', 11121304), (11121300, 'b', 11121352), (11121316, 'beq', 11121336), (11121332, 'bne', 11121348), (11121348, 'b', 11121352)],
        semantics=('[CoconutTree makeTileDead:] (imp 0x00a9b268, 26w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (15/16/17) writes the DEAD markers (0x23/0x24) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='cn_kindself',
        method='CoconutTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=11121360,
        end=11121516,
        disasm='disasm_worldtileloader_cn_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a9b36c (listing bound); next ObjC IMP 0x00a9b36c CoconutTree -[treeType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11121360, 'sub sp, sp, 0x10'), (11121512, 'bx lr')],
        calls=[],
        branches=[(11121396, 'beq', 11121496), (11121420, 'beq', 11121496), (11121444, 'beq', 11121496), (11121468, 'beq', 11121496)],
        semantics=("[CoconutTree tileIsKindOfSelf:] (imp 0x00a9b2d0, 39w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x23/0x24 family) and the generic marker arm.\n"),
    ),
    dict(
        name='cn_treetype',
        method='CoconutTree -[treeType]',
        types='i8@0:4',
        start=11121516,
        end=11121544,
        disasm='disasm_worldtileloader_cn_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a9b388 (listing bound); next ObjC IMP 0x00a9b388 CoconutTree -[isRequiredSoilType:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11121516, 'sub sp, sp, 8'), (11121540, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CoconutTree treeType] (imp 0x00a9b36c, 7w): returns **0x2e** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='cn_soiltype',
        method='CoconutTree -[isRequiredSoilType:]',
        types='c12@0:4i8',
        start=11121544,
        end=11121700,
        disasm='disasm_worldtileloader_cn_soiltype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00a9b424 (listing bound); next ObjC IMP 0x00a9b550 ScrollView -[layoutSubviews]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11121544, 'sub sp, sp, 0x10'), (11121696, 'bx lr')],
        calls=[],
        branches=[(11121576, 'beq', 11121680), (11121596, 'beq', 11121680), (11121616, 'beq', 11121680), (11121636, 'beq', 11121680), (11121656, 'beq', 11121680)],
        semantics=('[CoconutTree isRequiredSoilType:] (imp 0x00a9b388, 114w): the accepted-tile set {0x6, 0x1b, 0x8, 0x3a, 0x30, 0x31} (`cmp r0, 6` + `cmp r1, 0x1b/8/0x3a/0x30/0x31` chain @0xa9b3a0-0xa9b408).\n'),
    ),
    dict(
        name='ct_objecttype',
        method='CactusTree -[objectType]',
        types='i8@0:4',
        start=11872228,
        end=11872284,
        disasm='disasm_worldtileloader_ct_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b5281c (listing bound); next ObjC IMP 0x00b52800 CactusTree -[fruitItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11872228, 'sub sp, sp, 8'), (11872280, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[CactusTree objectType] (imp 0x00b527e4, 14w): returns **0x18 (24)** - the CactusTree's dynamic-object type code.\n"),
    ),
    dict(
        name='ct_fruititem',
        method='CactusTree -[fruitItemType]',
        types='i8@0:4',
        start=11872256,
        end=11872284,
        disasm='disasm_worldtileloader_ct_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b5281c (listing bound); next ObjC IMP 0x00b5281c CactusTree -[fruitShouldFallInSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11872256, 'sub sp, sp, 8'), (11872280, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CactusTree fruitItemType] (imp 0x00b52800, 7w): returns **0x18 (24)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='ct_fruitseason',
        method='CactusTree -[fruitShouldFallInSeason:]',
        types='c12@0:4i8',
        start=11872284,
        end=11872336,
        disasm='disasm_worldtileloader_ct_fruitseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b52850 (listing bound); next ObjC IMP 0x00b52850 CactusTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11872284, 'sub sp, sp, 0xc'), (11872332, 'andeq r0, r0, r0')],
        calls=[],
        branches=[],
        semantics=('[CactusTree fruitShouldFallInSeason:] (imp 0x00b5281c, 13w): the season equality gate - `cmp r0, 3; moveq 1` (E85 read: the apple checks season 3); the patterned `cmp rN, k; movw r0, 0; moveq r0, 1; and; sxtb` shape returns the boolean.\n'),
    ),
    dict(
        name='ct_makedead',
        method='CactusTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=11884060,
        end=11884112,
        disasm='disasm_worldtileloader_ct_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b55650 (listing bound); next ObjC IMP 0x00b55650 CactusTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11884060, 'sub sp, sp, 0xc'), (11884108, 'bx lr')],
        calls=[],
        branches=[(11884088, 'bne', 11884104)],
        semantics=('[CactusTree makeTileDead:] (imp 0x00b5561c, 13w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (43) writes the DEAD markers (0x2b/0x2c) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='ct_kindself',
        method='CactusTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=11884112,
        end=11884196,
        disasm='disasm_worldtileloader_ct_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b556a4 (listing bound); next ObjC IMP 0x00b556a4 CactusTree -[treeType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11884112, 'sub sp, sp, 0x10'), (11884192, 'bx lr')],
        calls=[],
        branches=[(11884148, 'beq', 11884176)],
        semantics=("[CactusTree tileIsKindOfSelf:] (imp 0x00b55650, 21w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x2b/0x2c family) and the generic marker arm.\n"),
    ),
    dict(
        name='ct_treetype',
        method='CactusTree -[treeType]',
        types='i8@0:4',
        start=11884196,
        end=11884224,
        disasm='disasm_worldtileloader_ct_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b556c0 (listing bound); next ObjC IMP 0x00b556c0 CactusTree -[isRequiredSoilType:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11884196, 'sub sp, sp, 8'), (11884220, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CactusTree treeType] (imp 0x00b556a4, 7w): returns **0x5** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='ct_soiltype',
        method='CactusTree -[isRequiredSoilType:]',
        types='c12@0:4i8',
        start=11884224,
        end=11884380,
        disasm='disasm_worldtileloader_ct_soiltype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b5575c (listing bound); next ObjC IMP 0x00b5575c CactusTree -[availableFood]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11884224, 'sub sp, sp, 0x10'), (11884376, 'bx lr')],
        calls=[],
        branches=[(11884256, 'beq', 11884360), (11884276, 'beq', 11884360), (11884296, 'beq', 11884360), (11884316, 'beq', 11884360), (11884336, 'beq', 11884360)],
        semantics=('[CactusTree isRequiredSoilType:] (imp 0x00b556c0, 39w): the soil-tile membership test - cmp against 0x3a/0x30/0x31/0x32 (the accepted soil codes; read: the compare chain).\n'),
    ),
    dict(
        name='ct_availfood',
        method='CactusTree -[availableFood]',
        types='f8@0:4',
        start=11884380,
        end=11884528,
        disasm='disasm_worldtileloader_ct_availfood.txt',
        base_add=11884404,
        base_literal=11884448,
        boundary='ARM.exidx end 0x00b557f0 (listing bound); next ObjC IMP 0x00b557a4 CactusTree -[setAvailableFood:]',
        selectors={},
        imports={},
        ivars={
                 0xb5579c: (17165916, 'OBJC_IVAR_$_CactusTree.availableFood', 148),
                 0xb557e8: (17165916, 'OBJC_IVAR_$_CactusTree.availableFood', 148),
        },
        classes={},
        instructions=[(11884380, 'sub sp, sp, 0xc'), (11884524, 'subseq sl, r0, r8, lsr 6')],
        calls=[],
        branches=[],
        semantics=('[CactusTree availableFood] (imp 0x00b5575c, 18w): the **dmb ish-fenced float read** (fffff368 cell; vldr from the slot @0xb5578c) - the cactus food is SMP-mirrored.\n'),
    ),
    dict(
        name='ct_setavailfood',
        method='CactusTree -[setAvailableFood:]',
        types='v12@0:4f8',
        start=11884452,
        end=11884528,
        disasm='disasm_worldtileloader_ct_setavailfood.txt',
        base_add=11884484,
        base_literal=11884524,
        boundary='ARM.exidx end 0x00b557f0 (listing bound); next ObjC IMP 0x00b55950 JetPackUI -[loadResources]',
        selectors={},
        imports={},
        ivars={
                 0xb557e8: (17165916, 'OBJC_IVAR_$_CactusTree.availableFood', 148),
        },
        classes={},
        instructions=[(11884452, 'sub sp, sp, 0xc'), (11884524, 'subseq sl, r0, r8, lsr 6')],
        calls=[],
        branches=[],
        semantics=('[CactusTree setAvailableFood:] (imp 0x00b557a4, 107w): the **dmb ish-fenced float write** (str r2, [r0, r1] between the barriers @0xb557d8-0xb557dc).\n'),
    ),
    dict(
        name='pt_objecttype',
        method='PineTree -[objectType]',
        types='i8@0:4',
        start=11944824,
        end=11944912,
        disasm='disasm_worldtileloader_pt_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b643d0 (listing bound); next ObjC IMP 0x00b64394 PineTree -[fruitItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11944824, 'sub sp, sp, 8'), (11944908, 'andeq r0, r0, r0')],
        calls=[],
        branches=[],
        semantics=("[PineTree objectType] (imp 0x00b64378, 22w): returns **0x1b (27)** - the PineTree's dynamic-object type code.\n"),
    ),
    dict(
        name='pt_fruititem',
        method='PineTree -[fruitItemType]',
        types='i8@0:4',
        start=11944852,
        end=11944912,
        disasm='disasm_worldtileloader_pt_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b643d0 (listing bound); next ObjC IMP 0x00b643b0 PineTree -[shouldAddFallenFruits]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11944852, 'sub sp, sp, 8'), (11944908, 'andeq r0, r0, r0')],
        calls=[],
        branches=[],
        semantics=('[PineTree fruitItemType] (imp 0x00b64394, 15w): returns **0x1b (27)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='pt_fallen',
        method='PineTree -[shouldAddFallenFruits]',
        types='c8@0:4',
        start=11944880,
        end=11944912,
        disasm='disasm_worldtileloader_pt_fallen.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b643d0 (listing bound); next ObjC IMP 0x00b643d0 PineTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11944880, 'sub sp, sp, 8'), (11944908, 'andeq r0, r0, r0')],
        calls=[],
        branches=[],
        semantics=('[PineTree shouldAddFallenFruits] (imp 0x00b643b0, 8w): returns **0** - the pine adds no fallen fruits.\n'),
    ),
    dict(
        name='pt_makedead',
        method='PineTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=11956032,
        end=11956136,
        disasm='disasm_worldtileloader_pt_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b66fa8 (listing bound); next ObjC IMP 0x00b66fa8 PineTree -[update:accurateDT:isSimulation:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11956032, 'sub sp, sp, 0xc'), (11956132, 'bx lr')],
        calls=[],
        branches=[(11956060, 'bne', 11956080), (11956076, 'b', 11956128), (11956092, 'beq', 11956112), (11956108, 'bne', 11956124), (11956124, 'b', 11956128)],
        semantics=('[PineTree makeTileDead:] (imp 0x00b66f40, 26w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (29/34) writes the DEAD markers (0x1d/0x22) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='pt_treetype',
        method='PineTree -[treeType]',
        types='i8@0:4',
        start=11958808,
        end=11958836,
        disasm='disasm_worldtileloader_pt_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b67a34 (listing bound); next ObjC IMP 0x00b67a34 PineTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11958808, 'sub sp, sp, 8'), (11958832, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[PineTree treeType] (imp 0x00b67a18, 7w): returns **0x4** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='pt_kindself',
        method='PineTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=11958836,
        end=11958992,
        disasm='disasm_worldtileloader_pt_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b67ad0 (listing bound); next ObjC IMP 0x00b67c30 CraftUI -[loadResources]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11958836, 'sub sp, sp, 0x10'), (11958988, 'bx lr')],
        calls=[],
        branches=[(11958872, 'beq', 11958972), (11958896, 'beq', 11958972), (11958920, 'beq', 11958972), (11958944, 'beq', 11958972)],
        semantics=("[PineTree tileIsKindOfSelf:] (imp 0x00b67a34, 39w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x1d/0x22 family) and the generic marker arm.\n"),
    ),
    dict(
        name='ch_objecttype',
        method='CherryTree -[objectType]',
        types='i8@0:4',
        start=13686276,
        end=13686332,
        disasm='disasm_worldtileloader_ch_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d0d63c (listing bound); next ObjC IMP 0x00d0d620 CherryTree -[fruitItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13686276, 'sub sp, sp, 8'), (13686328, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[CherryTree objectType] (imp 0x00d0d604, 14w): returns **0x4d (77)** - the CherryTree's dynamic-object type code.\n"),
    ),
    dict(
        name='ch_fruititem',
        method='CherryTree -[fruitItemType]',
        types='i8@0:4',
        start=13686304,
        end=13686332,
        disasm='disasm_worldtileloader_ch_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d0d63c (listing bound); next ObjC IMP 0x00d0d63c CherryTree -[fruitShouldFallInSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13686304, 'sub sp, sp, 8'), (13686328, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CherryTree fruitItemType] (imp 0x00d0d620, 7w): returns **0x4d (77)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='ch_fruitseason',
        method='CherryTree -[fruitShouldFallInSeason:]',
        types='c12@0:4i8',
        start=13686332,
        end=13686384,
        disasm='disasm_worldtileloader_ch_fruitseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d0d670 (listing bound); next ObjC IMP 0x00d0d670 CherryTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13686332, 'sub sp, sp, 0xc'), (13686380, 'andeq r0, r0, r0')],
        calls=[],
        branches=[],
        semantics=('[CherryTree fruitShouldFallInSeason:] (imp 0x00d0d63c, 13w): the season equality gate - `cmp r0, 3; moveq 1` (E85 read: the apple checks season 3); the patterned `cmp rN, k; movw r0, 0; moveq r0, 1; and; sxtb` shape returns the boolean.\n'),
    ),
    dict(
        name='ch_getsavedict',
        method='CherryTree -[getSaveDict]',
        types='@8@0:4',
        start=13688868,
        end=13688992,
        disasm='disasm_worldtileloader_ch_getsavedict.txt',
        base_add=13688884,
        base_literal=13688988,
        boundary='ARM.exidx end 0x00d0e0a0 (listing bound); next ObjC IMP 0x00d0e0a0 CherryTree -[updateGrowth:]',
        selectors={
                 0xd0e094: (15238284, 'getSaveDict'),
        },
        imports={
                 0xd0e090: (17151900, 'objc_msgSendSuper2'),
        },
        ivars={},
        classes={
                 0xd0e098: (15253256, 'OBJC_CLASS_$_CherryTree'),
        },
        instructions=[(13688868, 'push {r4, sl, fp, lr}'), (13688988, 'ldrhteq r1, [r5], -r8')],
        calls=[(13688948, 'blx ip')],
        branches=[],
        semantics=('[CherryTree getSaveDict] (imp 0x00d0e024, 31w): the save-dict forwarder - ffffbca8 super + the class chain (ffe28998/ffe2c414 family) builds the dict from the tree state.\n'),
    ),
    dict(
        name='ch_makedead',
        method='CherryTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=13696332,
        end=13696436,
        disasm='disasm_worldtileloader_ch_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d0fdb4 (listing bound); next ObjC IMP 0x00d0fdb4 CherryTree -[update:accurateDT:isSimulation:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13696332, 'sub sp, sp, 0xc'), (13696432, 'bx lr')],
        calls=[],
        branches=[(13696360, 'bne', 13696380), (13696376, 'b', 13696428), (13696392, 'beq', 13696412), (13696408, 'bne', 13696424), (13696424, 'b', 13696428)],
        semantics=('[CherryTree makeTileDead:] (imp 0x00d0fd4c, 26w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (21/22/23) writes the DEAD markers (0x27/0x28) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='ch_treetype',
        method='CherryTree -[treeType]',
        types='i8@0:4',
        start=13698188,
        end=13698216,
        disasm='disasm_worldtileloader_ch_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d104a8 (listing bound); next ObjC IMP 0x00d104a8 CherryTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13698188, 'sub sp, sp, 8'), (13698212, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CherryTree treeType] (imp 0x00d1048c, 7w): returns **0x4d** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='ch_kindself',
        method='CherryTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=13698216,
        end=13698372,
        disasm='disasm_worldtileloader_ch_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d10544 (listing bound); next ObjC IMP 0x00d10640 MJButton -[createTitleWithColor:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13698216, 'sub sp, sp, 0x10'), (13698368, 'bx lr')],
        calls=[],
        branches=[(13698252, 'beq', 13698352), (13698276, 'beq', 13698352), (13698300, 'beq', 13698352), (13698324, 'beq', 13698352)],
        semantics=("[CherryTree tileIsKindOfSelf:] (imp 0x00d104a8, 39w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x27/0x28 family) and the generic marker arm.\n"),
    ),
    dict(
        name='mg_objecttype',
        method='MangoTree -[objectType]',
        types='i8@0:4',
        start=13937360,
        end=13937416,
        disasm='disasm_worldtileloader_mg_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d4ab08 (listing bound); next ObjC IMP 0x00d4aaec MangoTree -[fruitItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13937360, 'sub sp, sp, 8'), (13937412, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[MangoTree objectType] (imp 0x00d4aad0, 14w): returns **0x16 (22)** - the MangoTree's dynamic-object type code.\n"),
    ),
    dict(
        name='mg_fruititem',
        method='MangoTree -[fruitItemType]',
        types='i8@0:4',
        start=13937388,
        end=13937416,
        disasm='disasm_worldtileloader_mg_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d4ab08 (listing bound); next ObjC IMP 0x00d4ab08 MangoTree -[fruitShouldFallInSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13937388, 'sub sp, sp, 8'), (13937412, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[MangoTree fruitItemType] (imp 0x00d4aaec, 7w): returns **0x16 (22)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='mg_fruitseason',
        method='MangoTree -[fruitShouldFallInSeason:]',
        types='c12@0:4i8',
        start=13937416,
        end=13937464,
        disasm='disasm_worldtileloader_mg_fruitseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d4ab38 (listing bound); next ObjC IMP 0x00d4ab38 MangoTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13937416, 'sub sp, sp, 0xc'), (13937460, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[MangoTree fruitShouldFallInSeason:] (imp 0x00d4ab08, 12w): the season equality gate - `cmp r0, 3; moveq 1` (E85 read: the apple checks season 3); the patterned `cmp rN, k; movw r0, 0; moveq r0, 1; and; sxtb` shape returns the boolean.\n'),
    ),
    dict(
        name='mg_getsavedict',
        method='MangoTree -[getSaveDict]',
        types='@8@0:4',
        start=13940204,
        end=13940328,
        disasm='disasm_worldtileloader_mg_getsavedict.txt',
        base_add=13940220,
        base_literal=13940324,
        boundary='ARM.exidx end 0x00d4b668 (listing bound); next ObjC IMP 0x00d4b668 MangoTree -[updateGrowth:]',
        selectors={
                 0xd4b65c: (15239740, 'getSaveDict'),
        },
        imports={
                 0xd4b658: (17151900, 'objc_msgSendSuper2'),
        },
        ivars={},
        classes={
                 0xd4b660: (15253280, 'OBJC_CLASS_$_MangoTree'),
        },
        instructions=[(13940204, 'push {r4, sl, fp, lr}'), (13940324, 'ldrshteq r4, [r1], -r0')],
        calls=[(13940284, 'blx ip')],
        branches=[],
        semantics=('[MangoTree getSaveDict] (imp 0x00d4b5ec, 31w): the save-dict forwarder - ffffbca8 super + the class chain (ffe28998/ffe2c414 family) builds the dict from the tree state.\n'),
    ),
    dict(
        name='mg_makedead',
        method='MangoTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=13949496,
        end=13949600,
        disasm='disasm_worldtileloader_mg_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d4daa0 (listing bound); next ObjC IMP 0x00d4daa0 MangoTree -[treeType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13949496, 'sub sp, sp, 0xc'), (13949596, 'bx lr')],
        calls=[],
        branches=[(13949524, 'bne', 13949544), (13949540, 'b', 13949592), (13949556, 'beq', 13949576), (13949572, 'bne', 13949588), (13949588, 'b', 13949592)],
        semantics=('[MangoTree makeTileDead:] (imp 0x00d4da38, 26w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (12/13/14) writes the DEAD markers (0x20/0x21) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='mg_treetype',
        method='MangoTree -[treeType]',
        types='i8@0:4',
        start=13949600,
        end=13949628,
        disasm='disasm_worldtileloader_mg_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d4dabc (listing bound); next ObjC IMP 0x00d4dabc MangoTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13949600, 'sub sp, sp, 8'), (13949624, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[MangoTree treeType] (imp 0x00d4daa0, 7w): returns **0x2** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='mg_kindself',
        method='MangoTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=13949628,
        end=13949784,
        disasm='disasm_worldtileloader_mg_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00d4db58 (listing bound); next ObjC IMP 0x00d4dcb8 Egg -[initSubDerivedItems]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(13949628, 'sub sp, sp, 0x10'), (13949780, 'bx lr')],
        calls=[],
        branches=[(13949664, 'beq', 13949764), (13949688, 'beq', 13949764), (13949712, 'beq', 13949764), (13949736, 'beq', 13949764)],
        semantics=("[MangoTree tileIsKindOfSelf:] (imp 0x00d4dabc, 39w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x20/0x21 family) and the generic marker arm.\n"),
    ),
    dict(
        name='mp_objecttype',
        method='MapleTree -[objectType]',
        types='i8@0:4',
        start=14374504,
        end=14374560,
        disasm='disasm_worldtileloader_mp_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00db56a0 (listing bound); next ObjC IMP 0x00db5684 MapleTree -[fruitItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(14374504, 'sub sp, sp, 8'), (14374556, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[MapleTree objectType] (imp 0x00db5668, 14w): returns **0x17 (23)** - the MapleTree's dynamic-object type code.\n"),
    ),
    dict(
        name='mp_fruititem',
        method='MapleTree -[fruitItemType]',
        types='i8@0:4',
        start=14374532,
        end=14374560,
        disasm='disasm_worldtileloader_mp_fruititem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00db56a0 (listing bound); next ObjC IMP 0x00db56a0 MapleTree -[fruitShouldFallInSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(14374532, 'sub sp, sp, 8'), (14374556, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[MapleTree fruitItemType] (imp 0x00db5684, 7w): returns **0x17 (23)** - the fruit item type (== the object type here).\n'),
    ),
    dict(
        name='mp_fruitseason',
        method='MapleTree -[fruitShouldFallInSeason:]',
        types='c12@0:4i8',
        start=14374560,
        end=14374608,
        disasm='disasm_worldtileloader_mp_fruitseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00db56d0 (listing bound); next ObjC IMP 0x00db56d0 MapleTree -[initWithWorld:dynamicWorld:atPosition:cache:maxHeight:growthRate:treeDensityNoiseFunction:seasonOffsetNoiseFunction:adultTree:adultMaxAge:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(14374560, 'sub sp, sp, 0xc'), (14374604, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[MapleTree fruitShouldFallInSeason:] (imp 0x00db56a0, 12w): the season equality gate - `cmp r0, 3; moveq 1` (E85 read: the apple checks season 3); the patterned `cmp rN, k; movw r0, 0; moveq r0, 1; and; sxtb` shape returns the boolean.\n'),
    ),
    dict(
        name='mp_getsavedict',
        method='MapleTree -[getSaveDict]',
        types='@8@0:4',
        start=14377132,
        end=14377256,
        disasm='disasm_worldtileloader_mp_getsavedict.txt',
        base_add=14377148,
        base_literal=14377252,
        boundary='ARM.exidx end 0x00db6128 (listing bound); next ObjC IMP 0x00db6128 MapleTree -[updateGrowth:]',
        selectors={
                 0xdb611c: (15241076, 'getSaveDict'),
        },
        imports={
                 0xdb6118: (17151900, 'objc_msgSendSuper2'),
        },
        ivars={},
        classes={
                 0xdb6120: (15253328, 'OBJC_CLASS_$_MapleTree'),
        },
        instructions=[(14377132, 'push {r4, sl, fp, lr}'), (14377252, 'eoreq sb, sl, r0, lsr sl')],
        calls=[(14377212, 'blx ip')],
        branches=[],
        semantics=('[MapleTree getSaveDict] (imp 0x00db60ac, 31w): the save-dict forwarder - ffffbca8 super + the class chain (ffe28998/ffe2c414 family) builds the dict from the tree state.\n'),
    ),
    dict(
        name='mp_makedead',
        method='MapleTree -[makeTileDead:]',
        types='v12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=14385168,
        end=14385272,
        disasm='disasm_worldtileloader_mp_makedead.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00db8078 (listing bound); next ObjC IMP 0x00db8078 MapleTree -[update:accurateDT:isSimulation:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(14385168, 'sub sp, sp, 0xc'), (14385268, 'bx lr')],
        calls=[],
        branches=[(14385196, 'bne', 14385216), (14385212, 'b', 14385264), (14385228, 'beq', 14385248), (14385244, 'bne', 14385260), (14385260, 'b', 14385264)],
        semantics=('[MapleTree makeTileDead:] (imp 0x00db8010, 26w): the stage->dead-marker machine - reads the tile byte [r0+3] and for the LIVE stages (10/11) writes the DEAD markers (0x1e/0x1f) via strb [r1, 3] (e.g. apple: stage 3 -> 0x1b, 4/5 -> 0x1c).\n'),
    ),
    dict(
        name='mp_treetype',
        method='MapleTree -[treeType]',
        types='i8@0:4',
        start=14387100,
        end=14387128,
        disasm='disasm_worldtileloader_mp_treetype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00db87b8 (listing bound); next ObjC IMP 0x00db87b8 MapleTree -[tileIsKindOfSelf:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(14387100, 'sub sp, sp, 8'), (14387124, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[MapleTree treeType] (imp 0x00db879c, 7w): returns **0x17** - the tree-type enumeration value.\n'),
    ),
    dict(
        name='mp_kindself',
        method='MapleTree -[tileIsKindOfSelf:]',
        types='c12@0:4^{Tile=CCCCCCCCCCCCCSSSsCISSSSSQ[8S]}8',
        start=14387128,
        end=14387284,
        disasm='disasm_worldtileloader_mp_kindself.txt',
        base_add=None,
        base_literal=None,
        boundary='last body',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(14387128, 'sub sp, sp, 0x10'), (14387280, 'bx lr')],
        calls=[],
        branches=[(14387164, 'beq', 14387264), (14387188, 'beq', 14387264), (14387212, 'beq', 14387264), (14387236, 'beq', 14387264)],
        semantics=("[MapleTree tileIsKindOfSelf:] (imp 0x00db87b8, 39w): the stage-set membership test over the tile byte [r0+3]/[r1+3] - accepts the class's live+dead stage codes (0x1e/0x1f family) and the generic marker arm.\n"),
    ),
]


def signed(v: int) -> int:
    return v - (1 << 32) if v & 0x80000000 else v


def bl_target(site: int, word: int) -> int:
    if word >> 24 != 0xEB:
        raise ValueError(f'{site:#x} is not ARM bl')
    imm = word & 0xFFFFFF
    if imm & 0x800000:
        imm -= 1 << 24
    return (site + 8 + (imm << 2)) & 0xffffffff


def recover(path: Path) -> dict:
    data = path.read_bytes()
    sha = hashlib.sha256(data).hexdigest()
    if sha != EXPECTED_SHA:
        raise ValueError('unsupported ELF SHA-256; fixed-IMP analysis requires pinned original')
    memory = ELFMemory(path)
    elf = ELFFile(io.BytesIO(data))

    def cstr(addr):
        off = memory.offset(addr, 1)
        if off is None:
            return None
        end = data.find(b'\0', off, off + 256)
        return data[off:end].decode('utf-8', 'replace') if end >= 0 else None

    dynsym = {}
    for sec in elf.iter_sections():
        if sec.name == '.dynsym':
            for s in sec.iter_symbols():
                if s['st_value']:
                    dynsym.setdefault(s['st_value'], s.name)
    relocs = {}
    for sec in elf.iter_sections():
        if not isinstance(sec, RelocationSection):
            continue
        syms = elf.get_section(sec['sh_link'])
        for r in sec.iter_relocations():
            if r['r_info_sym']:
                relocs[r['r_offset']] = syms.get_symbol(r['r_info_sym']).name

    methods = []
    for spec in SPECS:
        text = (NATIVE / spec['disasm']).read_text()
        words = verify_disassembly(memory, text, spec['start'], spec['end'])
        rows = {}
        for mm in re.finditer(r'\b(0x[0-9a-f]{8})\s+[0-9a-f]{8}\s+(.*)', text):
            rows[int(mm.group(1), 16)] = mm.group(2).split(';')[0].strip()

        base = None
        if spec['base_add'] is not None:
            base = (spec['base_add'] + 8 + signed(memory.word(spec['base_literal']))) & 0xffffffff
            if base != EXPECTED_BASE:
                raise ValueError(f"{spec['name']}: PIC base drift {base:#x}")

        selectors = {}
        for cell, (expected_slot, expected_name) in spec['selectors'].items():
            slot = (base + signed(memory.word(cell))) & 0xffffffff
            if slot != expected_slot:
                raise ValueError(f"{spec['name']}: selector cell {cell:#x} -> {slot:#x}")
            got = cstr(memory.word(slot))
            if got != expected_name:
                raise ValueError(f"{spec['name']}: selector drifted at {cell:#x}: {got!r}")
            selectors[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'selector': got}

        for cell, (expected_slot, expected_symbol) in spec.get('classes', {}).items():
            slot = (base + signed(memory.word(cell))) & 0xffffffff
            if slot != expected_slot:
                raise ValueError(f"{spec['name']}: class cell {cell:#x} -> {slot:#x}")
            entry = memory.word(slot)
            if entry is None:
                got = relocs.get(slot, '')
                if got != expected_symbol:
                    raise ValueError(f"{spec['name']}: class reloc drifted at {cell:#x}: {got!r}")
                selectors[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'class': got,
                                              'route': 'ABS32 relocation symbol'}
                continue
            got = dynsym.get(entry, '')
            if got != expected_symbol:
                raise ValueError(f"{spec['name']}: class drifted at {cell:#x}: {got!r}")
            selectors[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'class': got,
                                          'route': 'dynsym entry at slot word'}

        for cell, (expected_slot, expected_name) in spec['imports'].items():
            slot = (base + signed(memory.word(cell))) & 0xffffffff
            if slot != expected_slot:
                raise ValueError(f"{spec['name']}: import cell {cell:#x} -> {slot:#x}")
            got = memory.imports.get(slot)
            route = 'PLT/GOT relocation (R_ARM_JUMP_SLOT / GLOB_DAT)'
            if got is None:
                got = relocs.get(slot)
                route = 'ABS32 relocation symbol'
            if got != expected_name:
                raise ValueError(f"{spec['name']}: import drifted at {cell:#x}: {got!r} ({route})")
            selectors[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'import': got, 'route': route}

        ivars = {}
        for cell, (expected_slot, expected_symbol, expected_offset) in spec['ivars'].items():
            slot = (base + signed(memory.word(cell))) & 0xffffffff
            if slot != expected_slot:
                raise ValueError(f"{spec['name']}: ivar cell {cell:#x} -> {slot:#x}")
            entry = memory.word(slot)
            symbol = dynsym.get(entry, '')
            offset = memory.word(entry)
            if symbol != expected_symbol or offset != expected_offset:
                raise ValueError(f"{spec['name']}: ivar {cell:#x} drifted: {symbol!r}@{offset}")
            ivars[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'symbol': symbol, 'offset': offset}

        inrange = {a: ins for a, ins in rows.items() if spec['start'] <= a < spec['end']}
        listed = {a for a, ins in inrange.items() if re.match(r'^blx?\s', ins)}
        expected_sites = {site for site, _ in spec['calls']}
        if listed != expected_sites:
            raise ValueError(f"{spec['name']}: call set drifted: {sorted(listed ^ expected_sites)}")
        calls = []
        for site, route in spec['calls']:
            if rows[site] != route:
                raise ValueError(f"{spec['name']}: route drifted at {site:#x}: {rows[site]!r}")
            target = None
            if route.startswith('bl '):
                target = bl_target(site, memory.word(site))
                expected = ROUTE_TARGETS.get(route)
                if expected is None or target != expected:
                    raise ValueError(f"{spec['name']}: bl target drifted at {site:#x}: {target:#x}")
            calls.append({'site': f'0x{site:08x}', 'route': route,
                          'callee': f'0x{target:08x}' if target else None})

        listed_branches = set()
        disjoint = []
        for a, ins in inrange.items():
            m = re.match(r'^(b\w*)\s+(0x[0-9a-f]+)', ins)
            if not m or m.group(1) in ('bl', 'blx'):
                continue
            dest = int(m.group(2), 16)
            if spec['start'] <= dest < spec['end']:
                listed_branches.add((a, m.group(1), dest))
            else:
                disjoint.append({'address': f'0x{a:08x}', 'mnemonic': m.group(1),
                                 'destination': f'0x{dest:08x}'})
        expected_branches = {(a, mn, dest) for a, mn, dest in spec['branches']}
        if listed_branches != expected_branches:
            raise ValueError(f"{spec['name']}: branch set drifted: {sorted(listed_branches ^ expected_branches)}")

        for address, expected_text in spec['instructions']:
            if rows.get(address) != expected_text:
                raise ValueError(f"{spec['name']}: instruction drifted at {address:#x}: "
                                 f"{rows.get(address)!r} != {expected_text!r}")

        methods.append({
            'name': spec['name'],
            'method': spec['method'],
            'types': spec['types'],
            'imp': f"0x{spec['start']:08x}",
            'boundary_end': f"0x{spec['end']:08x}",
            'boundary': spec['boundary'],
            'verified_words': words,
            'pic_base': f'0x{base:08x}' if base else None,
            'selectors': selectors,
            'ivars': ivars,
            'calls': calls,
            'branches': [{'address': f'0x{a:08x}', 'mnemonic': mn,
                          'destination': f'0x{d:08x}'}
                         for a, mn, d in spec['branches']],
            'disjoint_branch_rows': disjoint,
            'semantics': spec['semantics'],
        })

    return {
        'schema': 1,
        'elf_sha256': sha,
        'batch': 'Plants line opener (E85): the ten fruit trees smalls sweep - stage codes, type pins, makeTileDead, kindself, soils; 73 bodies',
        'claim': ('a static bounded-body map with per-instruction anchors; the wire-format markers, the '
                  'NSLog key strings, the C++ container member layouts and the packet helper at 0x8b84c8 are '
                  'outside these bodies'),
        'classes': methods,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('elf', type=Path)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--output', type=Path,
                        default=NATIVE / 'tree_smalls.json')
    args = parser.parse_args()
    report = recover(args.elf)
    payload = json.dumps(report, indent=2, sort_keys=True) + '\n'
    if args.check:
        if args.output.read_text() != payload:
            raise SystemExit('stale tree_smalls.json')
    else:
        args.output.write_text(payload)
    total = sum(m['verified_words'] for m in report['classes'])
    print(f"classes={len(report['classes'])} words={total}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
