#!/usr/bin/env python3
"""Hash-gated recovery of the DynamicWorld block-load/accessor smalls (E35).

The plants line: the seven simple crops sweep: the repair removal, the client-
blockhead receive, the portal checks, the loaded-count, the gather pair, the
client/server booleans, the net/all-blockhead merges, the portal-positions and
blockheads getters and the connection-loss stub:
1 body, 1343 instruction words, from the pinned original libApplication.so
(1.7.6, armeabi-v7a).  Every instruction word is re-verified; tool refuses to
emit on drift.

Verification rules (each one is a claim this file makes about its own evidence):
  * coverage    - the checked-in listing must cover [start, end) exactly once per word,
                  and every word is re-read from the pinned ELF.
  * PIC base    - recomputed from the `add rX, pc, rY` anchor and its pool literal;
                  must equal 0x0105faf4.
  * cells       - selector cells: the slot is base + signed(pool value) and the C string
                  it points at must be the named selector.  Import cells: the slot must be
                  a PLT/GOT slot whose relocation names the import, or - for functions
                  reached through an ABS32 relocation - a relocation whose symbol names
                  it (the route used is recorded per cell).  Ivar cells: the slot
                  holds a pointer to OBJC_IVAR_$_<Class>.<name> in .dynsym plus the
                  offset word.  Class cells: the slot either holds the OBJC_CLASS_$_
                  symbol value (.dynsym) or - for classes imported from the system
                  frameworks - carries an ABS32 relocation whose symbol is the class;
                  both routes are checked, the relocation route is named when used.
  * calls       - the set of bl/blx rows inside the body must equal the spec's set, and
                  every `bl <name>` route's computed target must match ROUTE_TARGETS.
  * branches    - the set of conditional/unconditional b* rows whose destination lands
                  inside the body must equal the spec's set.  Rows outside the body are
                  literal-pool words that mask as branches; they are recorded in
                  `disjoint_branch_rows` instead of being silently dropped.
  * anchors     - the listed instruction texts must match the listing byte for byte.

Machine-generated spec tables + hand-written semantics; see
reconstruction/reverse-v3/native/CROP_SMALLS.md for the prose and boundaries.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import sys
from pathlib import Path

from elftools.elf.elffile import ELFFile
from elftools.elf.relocation import RelocationSection

sys.path.insert(0, str(Path(__file__).resolve().parent))
from trace_objc_dispatch import ELFMemory
from recover_drawframe_slices import verify_disassembly

ROOT = Path(__file__).resolve().parents[1]
NATIVE = ROOT / 'reconstruction/reverse-v3/native'
EXPECTED_SHA = '733d821027d69de329d0ba171df2e6013d612edf5a4d327badd001acc30b94c7'
EXPECTED_BASE = 0x0105FAF4

ROUTE_TARGETS = {
    'bl loc.imp.objc_msgSend': 0x001c281c,
    'bl method.Vector.Vector_float__float__float__float_': 0x004d0d08,
}

SPECS = [
    dict(
        name='cl_objecttype',
        method='ChilliPlant -[objectType]',
        types='i8@0:4',
        start=7052992,
        end=7053048,
        disasm='disasm_worldtileloader_cl_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006b9ef8 (listing bound); next ObjC IMP 0x006b9edc ChilliPlant -[emitsLight]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7052992, 'sub sp, sp, 8'), (7053044, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[ChilliPlant objectType] (imp 0x006b9ec0, 14w): returns **0x21 (33)** - the crop's object type (== another crop's seed item: the seed/item polarity).\n"),
    ),
    dict(
        name='cl_emitslight',
        method='ChilliPlant -[emitsLight]',
        types='c8@0:4',
        start=7053020,
        end=7053048,
        disasm='disasm_worldtileloader_cl_emitslight.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006b9ef8 (listing bound); next ObjC IMP 0x006b9ef8 ChilliPlant -[lightFactor]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7053020, 'sub sp, sp, 8'), (7053044, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[ChilliPlant emitsLight] (imp 0x006b9edc, 7w): the light-emission flag (the flowering light).\n'),
    ),
    dict(
        name='cl_lightfactor',
        method='ChilliPlant -[lightFactor]',
        types='f8@0:4',
        start=7053048,
        end=7053236,
        disasm='disasm_worldtileloader_cl_lightfactor.txt',
        base_add=7053080,
        base_literal=7053212,
        boundary='ARM.exidx end 0x006b9fb4 (listing bound); next ObjC IMP 0x006b9fb4 ChilliPlant -[lightColor]',
        selectors={
                 0x6b9fa0: (15203204, 'maxAgeBase'),
        },
        imports={},
        ivars={
                 0x6b9f98: (17155504, 'OBJC_IVAR_$_Plant.age', 72),
                 0x6b9fa8: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(7053048, 'push {fp, lr}'), (7053232, 'cdplo p12, 0xc, c12, c12, c13, 6')],
        calls=[(7053116, 'bl loc.imp.objc_msgSend')],
        branches=[],
        semantics=('[ChilliPlant lightFactor] (imp 0x006b9ef8, 47w): the light factor (the light arms (consts 0xff/0x4b, Vector build)).\n'),
    ),
    dict(
        name='cl_lightcolor',
        method='ChilliPlant -[lightColor]',
        types='{Vector=[4f]}8@0:4',
        start=7053236,
        end=7053672,
        disasm='disasm_worldtileloader_cl_lightcolor.txt',
        base_add=7053252,
        base_literal=7053668,
        boundary='ARM.exidx end 0x006ba168 (listing bound); next ObjC IMP 0x006ba168 ChilliPlant -[maxAgeBase]',
        selectors={
                 0x6ba158: (15203208, 'lightFactor'),
        },
        imports={
                 0x6ba154: (17151904, 'objc_msgSend'),
        },
        ivars={},
        classes={},
        instructions=[(7053236, 'push {r4, sl, fp, lr}'), (7053668, 'addseq r5, sl, r8, lsr 22')],
        calls=[(7053316, 'blx lr'), (7053632, 'bl method.Vector.Vector_float__float__float__float_')],
        branches=[(7053376, 'bpl', 7053392), (7053388, 'b', 7053408), (7053488, 'bpl', 7053504), (7053500, 'b', 7053520)],
        semantics=('[ChilliPlant lightColor] (imp 0x006b9fb4, 109w): the light color (the light arms (consts 0xff/0x4b, Vector build)); the Vector build packs the RGB.\n'),
    ),
    dict(
        name='cl_maxagebase',
        method='ChilliPlant -[maxAgeBase]',
        types='f8@0:4',
        start=7053672,
        end=7053720,
        disasm='disasm_worldtileloader_cl_maxagebase.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ba198 (listing bound); next ObjC IMP 0x006ba198 ChilliPlant -[seedItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7053672, 'sub sp, sp, 0x10'), (7053716, 'strbmi r0, [r1, 0]!')],
        calls=[],
        branches=[],
        semantics=('[ChilliPlant maxAgeBase] (imp 0x006ba168, 12w): returns **0x1c20 (7200)**.\n'),
    ),
    dict(
        name='cl_seeditem',
        method='ChilliPlant -[seedItemType]',
        types='i8@0:4',
        start=7053720,
        end=7053776,
        disasm='disasm_worldtileloader_cl_seeditem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ba1d0 (listing bound); next ObjC IMP 0x006ba1b4 ChilliPlant -[minAllowedTemperature]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7053720, 'sub sp, sp, 8'), (7053772, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[ChilliPlant seedItemType] (imp 0x006ba198, 14w): returns **0x70 (112)**.\n'),
    ),
    dict(
        name='cl_mintemp',
        method='ChilliPlant -[minAllowedTemperature]',
        types='i8@0:4',
        start=7053748,
        end=7053776,
        disasm='disasm_worldtileloader_cl_mintemp.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ba1d0 (listing bound); next ObjC IMP 0x006ba1d0 ChilliPlant -[floweringSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7053748, 'sub sp, sp, 8'), (7053772, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[ChilliPlant minAllowedTemperature] (imp 0x006ba1b4, 7w): the temperature gate constant.\n'),
    ),
    dict(
        name='cl_floweringseason',
        method='ChilliPlant -[floweringSeason:]',
        types='c12@0:4i8',
        start=7053776,
        end=7053852,
        disasm='disasm_worldtileloader_cl_floweringseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ba21c (listing bound); next ObjC IMP 0x006ba21c ChilliPlant -[canDieSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7053776, 'sub sp, sp, 0x10'), (7053848, 'bx lr')],
        calls=[],
        branches=[(7053808, 'beq', 7053832)],
        semantics=('[ChilliPlant floweringSeason:] (imp 0x006ba1d0, 19w): the flowering-season gate (cmp; moveq family).\n'),
    ),
    dict(
        name='cl_candie',
        method='ChilliPlant -[canDieSeason:]',
        types='c12@0:4i8',
        start=7053852,
        end=7053900,
        disasm='disasm_worldtileloader_cl_candie.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ba24c (listing bound); next ObjC IMP 0x006ba24c ChilliPlant -[plantType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7053852, 'sub sp, sp, 0xc'), (7053896, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[ChilliPlant canDieSeason:] (imp 0x006ba21c, 12w): the die-season gate.\n'),
    ),
    dict(
        name='cl_planttype',
        method='ChilliPlant -[plantType]',
        types='i8@0:4',
        start=7053900,
        end=7053928,
        disasm='disasm_worldtileloader_cl_planttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ba268 (listing bound); next ObjC IMP 0x006ba268 ChilliPlant -[isRequiredSoilType:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7053900, 'sub sp, sp, 8'), (7053924, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[ChilliPlant plantType] (imp 0x006ba24c, 7w): the plant-type constant.\n'),
    ),
    dict(
        name='cl_soiltype',
        method='ChilliPlant -[isRequiredSoilType:]',
        types='c12@0:4i8',
        start=7053928,
        end=7054044,
        disasm='disasm_worldtileloader_cl_soiltype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ba2dc (listing bound); next ObjC IMP 0x006ba2dc ChilliPlant -[renderImageType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7053928, 'sub sp, sp, 0x10'), (7054040, 'bx lr')],
        calls=[],
        branches=[(7053960, 'beq', 7054024), (7053980, 'beq', 7054024), (7054000, 'beq', 7054024)],
        semantics=('[ChilliPlant isRequiredSoilType:] (imp 0x006ba268, 29w): the soil membership - **{0x1b,0x30,0x31}** (the plant-base soil codes with per-crop deltas).\n'),
    ),
    dict(
        name='cl_renderimage',
        method='ChilliPlant -[renderImageType]',
        types='i8@0:4',
        start=7054044,
        end=7054136,
        disasm='disasm_worldtileloader_cl_renderimage.txt',
        base_add=7054052,
        base_literal=7054132,
        boundary='ARM.exidx end 0x006ba338 (listing bound); next ObjC IMP 0x006ba498 Donkey -[npcType]',
        selectors={},
        imports={},
        ivars={
                 0x6ba330: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(7054044, 'sub sp, sp, 0xc'), (7054132, 'addseq r5, sl, r8, lsl 16')],
        calls=[],
        branches=[(7054092, 'beq', 7054108), (7054104, 'b', 7054116)],
        semantics=('[ChilliPlant renderImageType] (imp 0x006ba2dc, 23w): the render-image pair **f7/f8** (the live/dead sprite indices; the state picks one).\n'),
    ),
    dict(
        name='wh_objecttype',
        method='WheatPlant -[objectType]',
        types='i8@0:4',
        start=7148500,
        end=7148528,
        disasm='disasm_worldtileloader_wh_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006d13f0 (listing bound); next ObjC IMP 0x006d13f0 WheatPlant -[maxAgeBase]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7148500, 'sub sp, sp, 8'), (7148524, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[WheatPlant objectType] (imp 0x006d13d4, 7w): returns **0x3d (61)** - the crop's object type (== another crop's seed item: the seed/item polarity).\n"),
    ),
    dict(
        name='wh_maxagebase',
        method='WheatPlant -[maxAgeBase]',
        types='f8@0:4',
        start=7148528,
        end=7148576,
        disasm='disasm_worldtileloader_wh_maxagebase.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006d1420 (listing bound); next ObjC IMP 0x006d1420 WheatPlant -[seedItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7148528, 'sub sp, sp, 0x10'), (7148572, 'strbmi r0, [r1, 0]!')],
        calls=[],
        branches=[],
        semantics=('[WheatPlant maxAgeBase] (imp 0x006d13f0, 12w): returns **0x1c20 (7200)**.\n'),
    ),
    dict(
        name='wh_seeditem',
        method='WheatPlant -[seedItemType]',
        types='i8@0:4',
        start=7148576,
        end=7148632,
        disasm='disasm_worldtileloader_wh_seeditem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006d1458 (listing bound); next ObjC IMP 0x006d143c WheatPlant -[minAllowedTemperature]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7148576, 'sub sp, sp, 8'), (7148628, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[WheatPlant seedItemType] (imp 0x006d1420, 14w): returns **0x136 (310)**.\n'),
    ),
    dict(
        name='wh_mintemp',
        method='WheatPlant -[minAllowedTemperature]',
        types='i8@0:4',
        start=7148604,
        end=7148632,
        disasm='disasm_worldtileloader_wh_mintemp.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006d1458 (listing bound); next ObjC IMP 0x006d1458 WheatPlant -[floweringSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7148604, 'sub sp, sp, 8'), (7148628, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[WheatPlant minAllowedTemperature] (imp 0x006d143c, 7w): the temperature gate constant.\n'),
    ),
    dict(
        name='wh_floweringseason',
        method='WheatPlant -[floweringSeason:]',
        types='c12@0:4i8',
        start=7148632,
        end=7148708,
        disasm='disasm_worldtileloader_wh_floweringseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006d14a4 (listing bound); next ObjC IMP 0x006d14a4 WheatPlant -[canDieSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7148632, 'sub sp, sp, 0x10'), (7148704, 'bx lr')],
        calls=[],
        branches=[(7148664, 'beq', 7148688)],
        semantics=('[WheatPlant floweringSeason:] (imp 0x006d1458, 19w): the flowering-season gate (cmp; moveq family).\n'),
    ),
    dict(
        name='wh_candie',
        method='WheatPlant -[canDieSeason:]',
        types='c12@0:4i8',
        start=7148708,
        end=7148756,
        disasm='disasm_worldtileloader_wh_candie.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006d14d4 (listing bound); next ObjC IMP 0x006d14d4 WheatPlant -[plantType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7148708, 'sub sp, sp, 0xc'), (7148752, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[WheatPlant canDieSeason:] (imp 0x006d14a4, 12w): the die-season gate.\n'),
    ),
    dict(
        name='wh_planttype',
        method='WheatPlant -[plantType]',
        types='i8@0:4',
        start=7148756,
        end=7148784,
        disasm='disasm_worldtileloader_wh_planttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006d14f0 (listing bound); next ObjC IMP 0x006d14f0 WheatPlant -[isRequiredSoilType:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7148756, 'sub sp, sp, 8'), (7148780, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[WheatPlant plantType] (imp 0x006d14d4, 7w): the plant-type constant.\n'),
    ),
    dict(
        name='wh_soiltype',
        method='WheatPlant -[isRequiredSoilType:]',
        types='c12@0:4i8',
        start=7148784,
        end=7148940,
        disasm='disasm_worldtileloader_wh_soiltype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006d158c (listing bound); next ObjC IMP 0x006d158c WheatPlant -[renderImageType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7148784, 'sub sp, sp, 0x10'), (7148936, 'bx lr')],
        calls=[],
        branches=[(7148816, 'beq', 7148920), (7148836, 'beq', 7148920), (7148856, 'beq', 7148920), (7148876, 'beq', 7148920), (7148896, 'beq', 7148920)],
        semantics=('[WheatPlant isRequiredSoilType:] (imp 0x006d14f0, 39w): the soil membership - **{0x1b,0x1c,0x30,0x31,0x32}** (the plant-base soil codes with per-crop deltas).\n'),
    ),
    dict(
        name='wh_renderimage',
        method='WheatPlant -[renderImageType]',
        types='i8@0:4',
        start=7148940,
        end=7149032,
        disasm='disasm_worldtileloader_wh_renderimage.txt',
        base_add=7148948,
        base_literal=7149028,
        boundary='ARM.exidx end 0x006d15e8 (listing bound); next ObjC IMP 0x006d15e8 WheatPlant -[npcSpawnType]',
        selectors={},
        imports={},
        ivars={
                 0x6d15e0: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(7148940, 'sub sp, sp, 0xc'), (7149028, 'addseq lr, r8, r8, asr r5')],
        calls=[],
        branches=[(7148988, 'beq', 7149004), (7149000, 'b', 7149012)],
        semantics=('[WheatPlant renderImageType] (imp 0x006d158c, 23w): the render-image pair **2f8/2f9** (the live/dead sprite indices; the state picks one).\n'),
    ),
    dict(
        name='wh_npcspawn',
        method='WheatPlant -[npcSpawnType]',
        types='i8@0:4',
        start=7149032,
        end=7149060,
        disasm='disasm_worldtileloader_wh_npcspawn.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006d1604 (listing bound); next ObjC IMP 0x006d1768 BlockheadAI -[initWithBlockhead:world:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7149032, 'sub sp, sp, 8'), (7149056, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[WheatPlant npcSpawnType] (imp 0x006d15e8, 7w): the NPC-spawn type derivation (the type-keyed helper).\n'),
    ),
    dict(
        name='tm_objecttype',
        method='TomatoPlant -[objectType]',
        types='i8@0:4',
        start=7338912,
        end=7338940,
        disasm='disasm_worldtileloader_tm_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ffbbc (listing bound); next ObjC IMP 0x006ffbbc TomatoPlant -[maxAgeBase]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7338912, 'sub sp, sp, 8'), (7338936, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[TomatoPlant objectType] (imp 0x006ffba0, 7w): returns **0x3e (62)** - the crop's object type (== another crop's seed item: the seed/item polarity).\n"),
    ),
    dict(
        name='tm_maxagebase',
        method='TomatoPlant -[maxAgeBase]',
        types='f8@0:4',
        start=7338940,
        end=7338988,
        disasm='disasm_worldtileloader_tm_maxagebase.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ffbec (listing bound); next ObjC IMP 0x006ffbec TomatoPlant -[seedItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7338940, 'sub sp, sp, 0x10'), (7338984, 'strbmi r0, [r1, 0]!')],
        calls=[],
        branches=[],
        semantics=('[TomatoPlant maxAgeBase] (imp 0x006ffbbc, 12w): returns **0x1c20 (7200)**.\n'),
    ),
    dict(
        name='tm_seeditem',
        method='TomatoPlant -[seedItemType]',
        types='i8@0:4',
        start=7338988,
        end=7339044,
        disasm='disasm_worldtileloader_tm_seeditem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ffc24 (listing bound); next ObjC IMP 0x006ffc08 TomatoPlant -[minAllowedTemperature]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7338988, 'sub sp, sp, 8'), (7339040, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[TomatoPlant seedItemType] (imp 0x006ffbec, 14w): returns **0x13c (316)**.\n'),
    ),
    dict(
        name='tm_mintemp',
        method='TomatoPlant -[minAllowedTemperature]',
        types='i8@0:4',
        start=7339016,
        end=7339044,
        disasm='disasm_worldtileloader_tm_mintemp.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ffc24 (listing bound); next ObjC IMP 0x006ffc24 TomatoPlant -[floweringSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7339016, 'sub sp, sp, 8'), (7339040, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[TomatoPlant minAllowedTemperature] (imp 0x006ffc08, 7w): the temperature gate constant.\n'),
    ),
    dict(
        name='tm_floweringseason',
        method='TomatoPlant -[floweringSeason:]',
        types='c12@0:4i8',
        start=7339044,
        end=7339120,
        disasm='disasm_worldtileloader_tm_floweringseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ffc70 (listing bound); next ObjC IMP 0x006ffc70 TomatoPlant -[canDieSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7339044, 'sub sp, sp, 0x10'), (7339116, 'bx lr')],
        calls=[],
        branches=[(7339076, 'beq', 7339100)],
        semantics=('[TomatoPlant floweringSeason:] (imp 0x006ffc24, 19w): the flowering-season gate (cmp; moveq family).\n'),
    ),
    dict(
        name='tm_candie',
        method='TomatoPlant -[canDieSeason:]',
        types='c12@0:4i8',
        start=7339120,
        end=7339168,
        disasm='disasm_worldtileloader_tm_candie.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ffca0 (listing bound); next ObjC IMP 0x006ffca0 TomatoPlant -[plantType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7339120, 'sub sp, sp, 0xc'), (7339164, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[TomatoPlant canDieSeason:] (imp 0x006ffc70, 12w): the die-season gate.\n'),
    ),
    dict(
        name='tm_planttype',
        method='TomatoPlant -[plantType]',
        types='i8@0:4',
        start=7339168,
        end=7339196,
        disasm='disasm_worldtileloader_tm_planttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ffcbc (listing bound); next ObjC IMP 0x006ffcbc TomatoPlant -[isRequiredSoilType:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7339168, 'sub sp, sp, 8'), (7339192, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[TomatoPlant plantType] (imp 0x006ffca0, 7w): returns **0x3e** (== objectType).\n'),
    ),
    dict(
        name='tm_soiltype',
        method='TomatoPlant -[isRequiredSoilType:]',
        types='c12@0:4i8',
        start=7339196,
        end=7339312,
        disasm='disasm_worldtileloader_tm_soiltype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x006ffd30 (listing bound); next ObjC IMP 0x006ffd30 TomatoPlant -[renderImageType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7339196, 'sub sp, sp, 0x10'), (7339308, 'bx lr')],
        calls=[],
        branches=[(7339228, 'beq', 7339292), (7339248, 'beq', 7339292), (7339268, 'beq', 7339292)],
        semantics=('[TomatoPlant isRequiredSoilType:] (imp 0x006ffcbc, 29w): the soil membership - **{0x1b,0x30,0x31}** (the plant-base soil codes with per-crop deltas).\n'),
    ),
    dict(
        name='tm_renderimage',
        method='TomatoPlant -[renderImageType]',
        types='i8@0:4',
        start=7339312,
        end=7339404,
        disasm='disasm_worldtileloader_tm_renderimage.txt',
        base_add=7339320,
        base_literal=7339400,
        boundary='ARM.exidx end 0x006ffd8c (listing bound); next ObjC IMP 0x006ffeec ElevatorMotor -[initSubDerivedItems]',
        selectors={},
        imports={},
        ivars={
                 0x6ffd84: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(7339312, 'sub sp, sp, 0xc'), (7339400, 'ldrheq pc, [r5], r4')],
        calls=[],
        branches=[(7339360, 'beq', 7339376), (7339372, 'b', 7339384)],
        semantics=('[TomatoPlant renderImageType] (imp 0x006ffd30, 23w): the render-image pair **2fa/2fb** (the live/dead sprite indices; the state picks one).\n'),
    ),
    dict(
        name='cr_objecttype',
        method='CarrotPlant -[objectType]',
        types='i8@0:4',
        start=7608544,
        end=7608572,
        disasm='disasm_worldtileloader_cr_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x007418fc (listing bound); next ObjC IMP 0x007418fc CarrotPlant -[maxAgeBase]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7608544, 'sub sp, sp, 8'), (7608568, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[CarrotPlant objectType] (imp 0x007418e0, 7w): returns **0x1b (27)** - the crop's object type (== another crop's seed item: the seed/item polarity).\n"),
    ),
    dict(
        name='cr_maxagebase',
        method='CarrotPlant -[maxAgeBase]',
        types='f8@0:4',
        start=7608572,
        end=7608620,
        disasm='disasm_worldtileloader_cr_maxagebase.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x0074192c (listing bound); next ObjC IMP 0x0074192c CarrotPlant -[seedItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7608572, 'sub sp, sp, 0x10'), (7608616, 'strbmi r0, [r1, 0]!')],
        calls=[],
        branches=[],
        semantics=('[CarrotPlant maxAgeBase] (imp 0x007418fc, 12w): returns **0x1c20 (7200)**.\n'),
    ),
    dict(
        name='cr_seeditem',
        method='CarrotPlant -[seedItemType]',
        types='i8@0:4',
        start=7608620,
        end=7608648,
        disasm='disasm_worldtileloader_cr_seeditem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00741948 (listing bound); next ObjC IMP 0x00741948 CarrotPlant -[foodToRemoveWhenSpawningNPC]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7608620, 'sub sp, sp, 8'), (7608644, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CarrotPlant seedItemType] (imp 0x0074192c, 7w): returns **0x47 (71)**.\n'),
    ),
    dict(
        name='cr_foodremove',
        method='CarrotPlant -[foodToRemoveWhenSpawningNPC]',
        types='f8@0:4',
        start=7608648,
        end=7608696,
        disasm='disasm_worldtileloader_cr_foodremove.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00741978 (listing bound); next ObjC IMP 0x00741978 CarrotPlant -[minAllowedTemperature]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7608648, 'sub sp, sp, 0x10'), (7608692, 'strbtmi r0, [r1], 0')],
        calls=[],
        branches=[],
        semantics=('[CarrotPlant foodToRemoveWhenSpawningNPC] (imp 0x00741948, 12w): returns **0x708 (1800)** - the NPC-spawn food cost.\n'),
    ),
    dict(
        name='cr_mintemp',
        method='CarrotPlant -[minAllowedTemperature]',
        types='i8@0:4',
        start=7608696,
        end=7608724,
        disasm='disasm_worldtileloader_cr_mintemp.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00741994 (listing bound); next ObjC IMP 0x00741994 CarrotPlant -[floweringSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7608696, 'sub sp, sp, 8'), (7608720, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CarrotPlant minAllowedTemperature] (imp 0x00741978, 7w): the temperature gate constant.\n'),
    ),
    dict(
        name='cr_floweringseason',
        method='CarrotPlant -[floweringSeason:]',
        types='c12@0:4i8',
        start=7608724,
        end=7608800,
        disasm='disasm_worldtileloader_cr_floweringseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x007419e0 (listing bound); next ObjC IMP 0x007419e0 CarrotPlant -[canDieSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7608724, 'sub sp, sp, 0x10'), (7608796, 'bx lr')],
        calls=[],
        branches=[(7608756, 'beq', 7608780)],
        semantics=('[CarrotPlant floweringSeason:] (imp 0x00741994, 19w): the flowering-season gate (cmp; moveq family).\n'),
    ),
    dict(
        name='cr_candie',
        method='CarrotPlant -[canDieSeason:]',
        types='c12@0:4i8',
        start=7608800,
        end=7608848,
        disasm='disasm_worldtileloader_cr_candie.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00741a10 (listing bound); next ObjC IMP 0x00741a10 CarrotPlant -[plantType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7608800, 'sub sp, sp, 0xc'), (7608844, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CarrotPlant canDieSeason:] (imp 0x007419e0, 12w): the die-season gate.\n'),
    ),
    dict(
        name='cr_planttype',
        method='CarrotPlant -[plantType]',
        types='i8@0:4',
        start=7608848,
        end=7608876,
        disasm='disasm_worldtileloader_cr_planttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00741a2c (listing bound); next ObjC IMP 0x00741a2c CarrotPlant -[isRequiredSoilType:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7608848, 'sub sp, sp, 8'), (7608872, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CarrotPlant plantType] (imp 0x00741a10, 7w): the plant-type constant.\n'),
    ),
    dict(
        name='cr_soiltype',
        method='CarrotPlant -[isRequiredSoilType:]',
        types='c12@0:4i8',
        start=7608876,
        end=7609032,
        disasm='disasm_worldtileloader_cr_soiltype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00741ac8 (listing bound); next ObjC IMP 0x00741ac8 CarrotPlant -[renderImageType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7608876, 'sub sp, sp, 0x10'), (7609028, 'bx lr')],
        calls=[],
        branches=[(7608908, 'beq', 7609012), (7608928, 'beq', 7609012), (7608948, 'beq', 7609012), (7608968, 'beq', 7609012), (7608988, 'beq', 7609012)],
        semantics=('[CarrotPlant isRequiredSoilType:] (imp 0x00741a2c, 39w): the soil membership - **{0x1b,0x1c,0x30,0x31,0x32}** (the plant-base soil codes with per-crop deltas).\n'),
    ),
    dict(
        name='cr_renderimage',
        method='CarrotPlant -[renderImageType]',
        types='i8@0:4',
        start=7609032,
        end=7609124,
        disasm='disasm_worldtileloader_cr_renderimage.txt',
        base_add=7609040,
        base_literal=7609120,
        boundary='ARM.exidx end 0x00741b24 (listing bound); next ObjC IMP 0x00741b24 CarrotPlant -[npcSpawnType]',
        selectors={},
        imports={},
        ivars={
                 0x741b1c: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(7609032, 'sub sp, sp, 0xc'), (7609120, 'addseq lr, r1, ip, lsl r0')],
        calls=[],
        branches=[(7609080, 'beq', 7609096), (7609092, 'b', 7609104)],
        semantics=('[CarrotPlant renderImageType] (imp 0x00741ac8, 23w): the render-image pair **f5/f6** (the live/dead sprite indices; the state picks one).\n'),
    ),
    dict(
        name='cr_npcspawn',
        method='CarrotPlant -[npcSpawnType]',
        types='i8@0:4',
        start=7609124,
        end=7609152,
        disasm='disasm_worldtileloader_cr_npcspawn.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00741b40 (listing bound); next ObjC IMP 0x00741c3c PaintingCraftableItemObject -[initWithCraftableItem:imageData:outputImageData:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7609124, 'sub sp, sp, 8'), (7609148, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CarrotPlant npcSpawnType] (imp 0x00741b24, 7w): the NPC-spawn type derivation (the type-keyed helper).\n'),
    ),
    dict(
        name='fx_objecttype',
        method='FlaxPlant -[objectType]',
        types='i8@0:4',
        start=7802024,
        end=7802052,
        disasm='disasm_worldtileloader_fx_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00770cc4 (listing bound); next ObjC IMP 0x00770cc4 FlaxPlant -[maxAgeBase]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7802024, 'sub sp, sp, 8'), (7802048, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[FlaxPlant objectType] (imp 0x00770ca8, 7w): returns **0xa (10)** - the crop's object type (== another crop's seed item: the seed/item polarity).\n"),
    ),
    dict(
        name='fx_maxagebase',
        method='FlaxPlant -[maxAgeBase]',
        types='f8@0:4',
        start=7802052,
        end=7802100,
        disasm='disasm_worldtileloader_fx_maxagebase.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00770cf4 (listing bound); next ObjC IMP 0x00770cf4 FlaxPlant -[seedItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7802052, 'sub sp, sp, 0x10'), (7802096, 'strbtmi r0, [r1], -r0')],
        calls=[],
        branches=[],
        semantics=('[FlaxPlant maxAgeBase] (imp 0x00770cc4, 12w): returns **0x3840 (14400)** (the double of the standard 0x1c20!).\n'),
    ),
    dict(
        name='fx_seeditem',
        method='FlaxPlant -[seedItemType]',
        types='i8@0:4',
        start=7802100,
        end=7802184,
        disasm='disasm_worldtileloader_fx_seeditem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00770d48 (listing bound); next ObjC IMP 0x00770d10 FlaxPlant -[folliageItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7802100, 'sub sp, sp, 8'), (7802180, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[FlaxPlant seedItemType] (imp 0x00770cf4, 21w): returns **0x36 (54)**.\n'),
    ),
    dict(
        name='fx_folliageitem',
        method='FlaxPlant -[folliageItemType]',
        types='i8@0:4',
        start=7802128,
        end=7802184,
        disasm='disasm_worldtileloader_fx_folliageitem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00770d48 (listing bound); next ObjC IMP 0x00770d2c FlaxPlant -[minAllowedTemperature]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7802128, 'sub sp, sp, 8'), (7802180, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[FlaxPlant folliageItemType] (imp 0x00770d10, 14w): returns **0x37 (55)** - the foliage item (the flax's extra product).\n"),
    ),
    dict(
        name='fx_mintemp',
        method='FlaxPlant -[minAllowedTemperature]',
        types='i8@0:4',
        start=7802156,
        end=7802184,
        disasm='disasm_worldtileloader_fx_mintemp.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00770d48 (listing bound); next ObjC IMP 0x00770d48 FlaxPlant -[floweringSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7802156, 'sub sp, sp, 8'), (7802180, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[FlaxPlant minAllowedTemperature] (imp 0x00770d2c, 7w): the temperature gate constant.\n'),
    ),
    dict(
        name='fx_floweringseason',
        method='FlaxPlant -[floweringSeason:]',
        types='c12@0:4i8',
        start=7802184,
        end=7802260,
        disasm='disasm_worldtileloader_fx_floweringseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00770d94 (listing bound); next ObjC IMP 0x00770d94 FlaxPlant -[canDieSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7802184, 'sub sp, sp, 0x10'), (7802256, 'bx lr')],
        calls=[],
        branches=[(7802216, 'beq', 7802240)],
        semantics=('[FlaxPlant floweringSeason:] (imp 0x00770d48, 19w): the flowering-season gate (cmp; moveq family).\n'),
    ),
    dict(
        name='fx_candie',
        method='FlaxPlant -[canDieSeason:]',
        types='c12@0:4i8',
        start=7802260,
        end=7802292,
        disasm='disasm_worldtileloader_fx_candie.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00770db4 (listing bound); next ObjC IMP 0x00770db4 FlaxPlant -[plantType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7802260, 'sub sp, sp, 0xc'), (7802288, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[FlaxPlant canDieSeason:] (imp 0x00770d94, 8w): the die-season gate.\n'),
    ),
    dict(
        name='fx_planttype',
        method='FlaxPlant -[plantType]',
        types='i8@0:4',
        start=7802292,
        end=7802320,
        disasm='disasm_worldtileloader_fx_planttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00770dd0 (listing bound); next ObjC IMP 0x00770dd0 FlaxPlant -[isRequiredSoilType:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7802292, 'sub sp, sp, 8'), (7802316, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[FlaxPlant plantType] (imp 0x00770db4, 7w): the plant-type constant.\n'),
    ),
    dict(
        name='fx_soiltype',
        method='FlaxPlant -[isRequiredSoilType:]',
        types='c12@0:4i8',
        start=7802320,
        end=7802536,
        disasm='disasm_worldtileloader_fx_soiltype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00770ea8 (listing bound); next ObjC IMP 0x00770ea8 FlaxPlant -[renderImageType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(7802320, 'sub sp, sp, 0x10'), (7802532, 'bx lr')],
        calls=[],
        branches=[(7802352, 'beq', 7802516), (7802372, 'beq', 7802516), (7802392, 'beq', 7802516), (7802412, 'beq', 7802516), (7802432, 'beq', 7802516), (7802452, 'beq', 7802516), (7802472, 'beq', 7802516), (7802492, 'beq', 7802516)],
        semantics=('[FlaxPlant isRequiredSoilType:] (imp 0x00770dd0, 54w): the soil membership - **{0x1b,0x1c,0x3a,0x30,0x31,0x32}** (the plant-base soil codes with per-crop deltas).\n'),
    ),
    dict(
        name='fx_renderimage',
        method='FlaxPlant -[renderImageType]',
        types='i8@0:4',
        start=7802536,
        end=7802628,
        disasm='disasm_worldtileloader_fx_renderimage.txt',
        base_add=7802544,
        base_literal=7802624,
        boundary='ARM.exidx end 0x00770f04 (listing bound); next ObjC IMP 0x00771064 OwnershipSignUI -[loadResources]',
        selectors={},
        imports={},
        ivars={
                 0x770efc: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(7802536, 'sub sp, sp, 0xc'), (7802624, 'addeq lr, lr, ip, lsr ip')],
        calls=[],
        branches=[(7802584, 'beq', 7802600), (7802596, 'b', 7802608)],
        semantics=('[FlaxPlant renderImageType] (imp 0x00770ea8, 23w): the render-image pair **ef/f0** (the live/dead sprite indices; the state picks one).\n'),
    ),
    dict(
        name='sf_objecttype',
        method='SunflowerPlant -[objectType]',
        types='i8@0:4',
        start=10208060,
        end=10208148,
        disasm='disasm_worldtileloader_sf_objecttype.txt',
        base_add=10208096,
        base_literal=10208144,
        boundary='ARM.exidx end 0x009bc394 (listing bound); next ObjC IMP 0x009bc358 SunflowerPlant -[emitsLight]',
        selectors={},
        imports={},
        ivars={
                 0x9bc38c: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(10208060, 'sub sp, sp, 8'), (10208144, 'rsbeq r3, sl, ip, lsl 15')],
        calls=[],
        branches=[],
        semantics=("[SunflowerPlant objectType] (imp 0x009bc33c, 22w): returns **0xb (11)** - the crop's object type (== another crop's seed item: the seed/item polarity).\n"),
    ),
    dict(
        name='sf_emitslight',
        method='SunflowerPlant -[emitsLight]',
        types='c8@0:4',
        start=10208088,
        end=10208148,
        disasm='disasm_worldtileloader_sf_emitslight.txt',
        base_add=10208096,
        base_literal=10208144,
        boundary='ARM.exidx end 0x009bc394 (listing bound); next ObjC IMP 0x009bc394 SunflowerPlant -[lightFactor]',
        selectors={},
        imports={},
        ivars={
                 0x9bc38c: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(10208088, 'sub sp, sp, 8'), (10208144, 'rsbeq r3, sl, ip, lsl 15')],
        calls=[],
        branches=[],
        semantics=('[SunflowerPlant emitsLight] (imp 0x009bc358, 15w): the light-emission flag (the flowering light).\n'),
    ),
    dict(
        name='sf_lightfactor',
        method='SunflowerPlant -[lightFactor]',
        types='f8@0:4',
        start=10208148,
        end=10208336,
        disasm='disasm_worldtileloader_sf_lightfactor.txt',
        base_add=10208180,
        base_literal=10208312,
        boundary='ARM.exidx end 0x009bc450 (listing bound); next ObjC IMP 0x009bc450 SunflowerPlant -[lightColor]',
        selectors={
                 0x9bc43c: (15221080, 'maxAgeBase'),
        },
        imports={},
        ivars={
                 0x9bc434: (17155504, 'OBJC_IVAR_$_Plant.age', 72),
                 0x9bc444: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(10208148, 'push {fp, lr}'), (10208332, 'cdplo p12, 0xc, c12, c12, c13, 6')],
        calls=[(10208216, 'bl loc.imp.objc_msgSend')],
        branches=[],
        semantics=('[SunflowerPlant lightFactor] (imp 0x009bc394, 47w): the light factor (the light arms (Vector build)).\n'),
    ),
    dict(
        name='sf_lightcolor',
        method='SunflowerPlant -[lightColor]',
        types='{Vector=[4f]}8@0:4',
        start=10208336,
        end=10208676,
        disasm='disasm_worldtileloader_sf_lightcolor.txt',
        base_add=10208352,
        base_literal=10208672,
        boundary='ARM.exidx end 0x009bc5a4 (listing bound); next ObjC IMP 0x009bc5a4 SunflowerPlant -[maxAgeBase]',
        selectors={
                 0x9bc598: (15221084, 'lightFactor'),
        },
        imports={
                 0x9bc594: (17151904, 'objc_msgSend'),
        },
        ivars={},
        classes={},
        instructions=[(10208336, 'push {r4, sl, fp, lr}'), (10208672, 'rsbeq r3, sl, ip, lsl 13')],
        calls=[(10208416, 'blx lr'), (10208640, 'bl method.Vector.Vector_float__float__float__float_')],
        branches=[(10208476, 'bpl', 10208492), (10208488, 'b', 10208508)],
        semantics=('[SunflowerPlant lightColor] (imp 0x009bc450, 85w): the light color (the light arms (Vector build)); the Vector build packs the RGB.\n'),
    ),
    dict(
        name='sf_maxagebase',
        method='SunflowerPlant -[maxAgeBase]',
        types='f8@0:4',
        start=10208676,
        end=10208724,
        disasm='disasm_worldtileloader_sf_maxagebase.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bc5d4 (listing bound); next ObjC IMP 0x009bc5d4 SunflowerPlant -[seedItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10208676, 'sub sp, sp, 0x10'), (10208720, 'strbmi r0, [r1, 0]!')],
        calls=[],
        branches=[],
        semantics=('[SunflowerPlant maxAgeBase] (imp 0x009bc5a4, 12w): returns **0x1c20 (7200)**.\n'),
    ),
    dict(
        name='sf_seeditem',
        method='SunflowerPlant -[seedItemType]',
        types='i8@0:4',
        start=10208724,
        end=10208780,
        disasm='disasm_worldtileloader_sf_seeditem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bc60c (listing bound); next ObjC IMP 0x009bc5f0 SunflowerPlant -[minAllowedTemperature]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10208724, 'sub sp, sp, 8'), (10208776, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[SunflowerPlant seedItemType] (imp 0x009bc5d4, 14w): returns **0x3d (61)**.\n'),
    ),
    dict(
        name='sf_mintemp',
        method='SunflowerPlant -[minAllowedTemperature]',
        types='i8@0:4',
        start=10208752,
        end=10208780,
        disasm='disasm_worldtileloader_sf_mintemp.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bc60c (listing bound); next ObjC IMP 0x009bc60c SunflowerPlant -[floweringSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10208752, 'sub sp, sp, 8'), (10208776, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[SunflowerPlant minAllowedTemperature] (imp 0x009bc5f0, 7w): the temperature gate constant.\n'),
    ),
    dict(
        name='sf_floweringseason',
        method='SunflowerPlant -[floweringSeason:]',
        types='c12@0:4i8',
        start=10208780,
        end=10208856,
        disasm='disasm_worldtileloader_sf_floweringseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bc658 (listing bound); next ObjC IMP 0x009bc658 SunflowerPlant -[canDieSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10208780, 'sub sp, sp, 0x10'), (10208852, 'bx lr')],
        calls=[],
        branches=[(10208812, 'beq', 10208836)],
        semantics=('[SunflowerPlant floweringSeason:] (imp 0x009bc60c, 19w): the flowering-season gate (cmp; moveq family).\n'),
    ),
    dict(
        name='sf_candie',
        method='SunflowerPlant -[canDieSeason:]',
        types='c12@0:4i8',
        start=10208856,
        end=10208904,
        disasm='disasm_worldtileloader_sf_candie.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bc688 (listing bound); next ObjC IMP 0x009bc688 SunflowerPlant -[plantType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10208856, 'sub sp, sp, 0xc'), (10208900, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[SunflowerPlant canDieSeason:] (imp 0x009bc658, 12w): the die-season gate.\n'),
    ),
    dict(
        name='sf_planttype',
        method='SunflowerPlant -[plantType]',
        types='i8@0:4',
        start=10208904,
        end=10208932,
        disasm='disasm_worldtileloader_sf_planttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bc6a4 (listing bound); next ObjC IMP 0x009bc6a4 SunflowerPlant -[isRequiredSoilType:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10208904, 'sub sp, sp, 8'), (10208928, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[SunflowerPlant plantType] (imp 0x009bc688, 7w): the plant-type constant.\n'),
    ),
    dict(
        name='sf_soiltype',
        method='SunflowerPlant -[isRequiredSoilType:]',
        types='c12@0:4i8',
        start=10208932,
        end=10209088,
        disasm='disasm_worldtileloader_sf_soiltype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x009bc740 (listing bound); next ObjC IMP 0x009bc740 SunflowerPlant -[renderImageType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(10208932, 'sub sp, sp, 0x10'), (10209084, 'bx lr')],
        calls=[],
        branches=[(10208964, 'beq', 10209068), (10208984, 'beq', 10209068), (10209004, 'beq', 10209068), (10209024, 'beq', 10209068), (10209044, 'beq', 10209068)],
        semantics=('[SunflowerPlant isRequiredSoilType:] (imp 0x009bc6a4, 39w): the soil membership - **{0x1b,0x1c,0x30,0x31,0x32}** (the plant-base soil codes with per-crop deltas).\n'),
    ),
    dict(
        name='sf_renderimage',
        method='SunflowerPlant -[renderImageType]',
        types='i8@0:4',
        start=10209088,
        end=10209180,
        disasm='disasm_worldtileloader_sf_renderimage.txt',
        base_add=10209096,
        base_literal=10209176,
        boundary='ARM.exidx end 0x009bc79c (listing bound); next ObjC IMP 0x009bc8fc AppleTree -[availableFood]',
        selectors={},
        imports={},
        ivars={
                 0x9bc794: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(10209088, 'sub sp, sp, 0xc'), (10209176, 'rsbeq r3, sl, r4, lsr 7')],
        calls=[],
        branches=[(10209136, 'beq', 10209152), (10209148, 'b', 10209160)],
        semantics=('[SunflowerPlant renderImageType] (imp 0x009bc740, 23w): the render-image pair **f1/f2** (the live/dead sprite indices; the state picks one).\n'),
    ),
    dict(
        name='co_objecttype',
        method='CornPlant -[objectType]',
        types='i8@0:4',
        start=11862496,
        end=11862524,
        disasm='disasm_worldtileloader_co_objecttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b501fc (listing bound); next ObjC IMP 0x00b501fc CornPlant -[maxAgeBase]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11862496, 'sub sp, sp, 8'), (11862520, 'bx lr')],
        calls=[],
        branches=[],
        semantics=("[CornPlant objectType] (imp 0x00b501e0, 7w): returns **0xc (12)** - the crop's object type (== another crop's seed item: the seed/item polarity).\n"),
    ),
    dict(
        name='co_maxagebase',
        method='CornPlant -[maxAgeBase]',
        types='f8@0:4',
        start=11862524,
        end=11862572,
        disasm='disasm_worldtileloader_co_maxagebase.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b5022c (listing bound); next ObjC IMP 0x00b5022c CornPlant -[seedItemType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11862524, 'sub sp, sp, 0x10'), (11862568, 'strbmi r0, [r1, 0]!')],
        calls=[],
        branches=[],
        semantics=('[CornPlant maxAgeBase] (imp 0x00b501fc, 12w): returns **0x1c20 (7200)**.\n'),
    ),
    dict(
        name='co_seeditem',
        method='CornPlant -[seedItemType]',
        types='i8@0:4',
        start=11862572,
        end=11862628,
        disasm='disasm_worldtileloader_co_seeditem.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b50264 (listing bound); next ObjC IMP 0x00b50248 CornPlant -[minAllowedTemperature]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11862572, 'sub sp, sp, 8'), (11862624, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CornPlant seedItemType] (imp 0x00b5022c, 14w): returns **0x3e (62)**.\n'),
    ),
    dict(
        name='co_mintemp',
        method='CornPlant -[minAllowedTemperature]',
        types='i8@0:4',
        start=11862600,
        end=11862628,
        disasm='disasm_worldtileloader_co_mintemp.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b50264 (listing bound); next ObjC IMP 0x00b50264 CornPlant -[floweringSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11862600, 'sub sp, sp, 8'), (11862624, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CornPlant minAllowedTemperature] (imp 0x00b50248, 7w): the temperature gate constant.\n'),
    ),
    dict(
        name='co_floweringseason',
        method='CornPlant -[floweringSeason:]',
        types='c12@0:4i8',
        start=11862628,
        end=11862704,
        disasm='disasm_worldtileloader_co_floweringseason.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b502b0 (listing bound); next ObjC IMP 0x00b502b0 CornPlant -[canDieSeason:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11862628, 'sub sp, sp, 0x10'), (11862700, 'bx lr')],
        calls=[],
        branches=[(11862660, 'beq', 11862684)],
        semantics=('[CornPlant floweringSeason:] (imp 0x00b50264, 19w): the flowering-season gate (cmp; moveq family).\n'),
    ),
    dict(
        name='co_candie',
        method='CornPlant -[canDieSeason:]',
        types='c12@0:4i8',
        start=11862704,
        end=11862752,
        disasm='disasm_worldtileloader_co_candie.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b502e0 (listing bound); next ObjC IMP 0x00b502e0 CornPlant -[plantType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11862704, 'sub sp, sp, 0xc'), (11862748, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CornPlant canDieSeason:] (imp 0x00b502b0, 12w): the die-season gate.\n'),
    ),
    dict(
        name='co_planttype',
        method='CornPlant -[plantType]',
        types='i8@0:4',
        start=11862752,
        end=11862780,
        disasm='disasm_worldtileloader_co_planttype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b502fc (listing bound); next ObjC IMP 0x00b502fc CornPlant -[isRequiredSoilType:]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11862752, 'sub sp, sp, 8'), (11862776, 'bx lr')],
        calls=[],
        branches=[],
        semantics=('[CornPlant plantType] (imp 0x00b502e0, 7w): the plant-type constant.\n'),
    ),
    dict(
        name='co_soiltype',
        method='CornPlant -[isRequiredSoilType:]',
        types='c12@0:4i8',
        start=11862780,
        end=11862936,
        disasm='disasm_worldtileloader_co_soiltype.txt',
        base_add=None,
        base_literal=None,
        boundary='ARM.exidx end 0x00b50398 (listing bound); next ObjC IMP 0x00b50398 CornPlant -[renderImageType]',
        selectors={},
        imports={},
        ivars={},
        classes={},
        instructions=[(11862780, 'sub sp, sp, 0x10'), (11862932, 'bx lr')],
        calls=[],
        branches=[(11862812, 'beq', 11862916), (11862832, 'beq', 11862916), (11862852, 'beq', 11862916), (11862872, 'beq', 11862916), (11862892, 'beq', 11862916)],
        semantics=('[CornPlant isRequiredSoilType:] (imp 0x00b502fc, 39w): the soil membership - **{0x1b,0x1c,0x30,0x31,0x32}** (the plant-base soil codes with per-crop deltas).\n'),
    ),
    dict(
        name='co_renderimage',
        method='CornPlant -[renderImageType]',
        types='i8@0:4',
        start=11862936,
        end=11863028,
        disasm='disasm_worldtileloader_co_renderimage.txt',
        base_add=11862944,
        base_literal=11863024,
        boundary='ARM.exidx end 0x00b503f4 (listing bound); next ObjC IMP 0x00b50520 GKCropBorderView -[initWithFrame:]',
        selectors={},
        imports={},
        ivars={
                 0xb503ec: (17155528, 'OBJC_IVAR_$_Plant.flowering', 85),
        },
        classes={},
        instructions=[(11862936, 'sub sp, sp, 0xc'), (11863024, 'subseq pc, r0, ip, asr 14')],
        calls=[],
        branches=[(11862984, 'beq', 11863000), (11862996, 'b', 11863008)],
        semantics=('[CornPlant renderImageType] (imp 0x00b50398, 23w): the render-image pair **f3/f4** (the live/dead sprite indices; the state picks one).\n'),
    ),
]


def signed(v: int) -> int:
    return v - (1 << 32) if v & 0x80000000 else v


def bl_target(site: int, word: int) -> int:
    if word >> 24 != 0xEB:
        raise ValueError(f'{site:#x} is not ARM bl')
    imm = word & 0xFFFFFF
    if imm & 0x800000:
        imm -= 1 << 24
    return (site + 8 + (imm << 2)) & 0xffffffff


def recover(path: Path) -> dict:
    data = path.read_bytes()
    sha = hashlib.sha256(data).hexdigest()
    if sha != EXPECTED_SHA:
        raise ValueError('unsupported ELF SHA-256; fixed-IMP analysis requires pinned original')
    memory = ELFMemory(path)
    elf = ELFFile(io.BytesIO(data))

    def cstr(addr):
        off = memory.offset(addr, 1)
        if off is None:
            return None
        end = data.find(b'\0', off, off + 256)
        return data[off:end].decode('utf-8', 'replace') if end >= 0 else None

    dynsym = {}
    for sec in elf.iter_sections():
        if sec.name == '.dynsym':
            for s in sec.iter_symbols():
                if s['st_value']:
                    dynsym.setdefault(s['st_value'], s.name)
    relocs = {}
    for sec in elf.iter_sections():
        if not isinstance(sec, RelocationSection):
            continue
        syms = elf.get_section(sec['sh_link'])
        for r in sec.iter_relocations():
            if r['r_info_sym']:
                relocs[r['r_offset']] = syms.get_symbol(r['r_info_sym']).name

    methods = []
    for spec in SPECS:
        text = (NATIVE / spec['disasm']).read_text()
        words = verify_disassembly(memory, text, spec['start'], spec['end'])
        rows = {}
        for mm in re.finditer(r'\b(0x[0-9a-f]{8})\s+[0-9a-f]{8}\s+(.*)', text):
            rows[int(mm.group(1), 16)] = mm.group(2).split(';')[0].strip()

        base = None
        if spec['base_add'] is not None:
            base = (spec['base_add'] + 8 + signed(memory.word(spec['base_literal']))) & 0xffffffff
            if base != EXPECTED_BASE:
                raise ValueError(f"{spec['name']}: PIC base drift {base:#x}")

        selectors = {}
        for cell, (expected_slot, expected_name) in spec['selectors'].items():
            slot = (base + signed(memory.word(cell))) & 0xffffffff
            if slot != expected_slot:
                raise ValueError(f"{spec['name']}: selector cell {cell:#x} -> {slot:#x}")
            got = cstr(memory.word(slot))
            if got != expected_name:
                raise ValueError(f"{spec['name']}: selector drifted at {cell:#x}: {got!r}")
            selectors[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'selector': got}

        for cell, (expected_slot, expected_symbol) in spec.get('classes', {}).items():
            slot = (base + signed(memory.word(cell))) & 0xffffffff
            if slot != expected_slot:
                raise ValueError(f"{spec['name']}: class cell {cell:#x} -> {slot:#x}")
            entry = memory.word(slot)
            if entry is None:
                got = relocs.get(slot, '')
                if got != expected_symbol:
                    raise ValueError(f"{spec['name']}: class reloc drifted at {cell:#x}: {got!r}")
                selectors[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'class': got,
                                              'route': 'ABS32 relocation symbol'}
                continue
            got = dynsym.get(entry, '')
            if got != expected_symbol:
                raise ValueError(f"{spec['name']}: class drifted at {cell:#x}: {got!r}")
            selectors[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'class': got,
                                          'route': 'dynsym entry at slot word'}

        for cell, (expected_slot, expected_name) in spec['imports'].items():
            slot = (base + signed(memory.word(cell))) & 0xffffffff
            if slot != expected_slot:
                raise ValueError(f"{spec['name']}: import cell {cell:#x} -> {slot:#x}")
            got = memory.imports.get(slot)
            route = 'PLT/GOT relocation (R_ARM_JUMP_SLOT / GLOB_DAT)'
            if got is None:
                got = relocs.get(slot)
                route = 'ABS32 relocation symbol'
            if got != expected_name:
                raise ValueError(f"{spec['name']}: import drifted at {cell:#x}: {got!r} ({route})")
            selectors[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'import': got, 'route': route}

        ivars = {}
        for cell, (expected_slot, expected_symbol, expected_offset) in spec['ivars'].items():
            slot = (base + signed(memory.word(cell))) & 0xffffffff
            if slot != expected_slot:
                raise ValueError(f"{spec['name']}: ivar cell {cell:#x} -> {slot:#x}")
            entry = memory.word(slot)
            symbol = dynsym.get(entry, '')
            offset = memory.word(entry)
            if symbol != expected_symbol or offset != expected_offset:
                raise ValueError(f"{spec['name']}: ivar {cell:#x} drifted: {symbol!r}@{offset}")
            ivars[f'0x{cell:08x}'] = {'slot': f'0x{slot:08x}', 'symbol': symbol, 'offset': offset}

        inrange = {a: ins for a, ins in rows.items() if spec['start'] <= a < spec['end']}
        listed = {a for a, ins in inrange.items() if re.match(r'^blx?\s', ins)}
        expected_sites = {site for site, _ in spec['calls']}
        if listed != expected_sites:
            raise ValueError(f"{spec['name']}: call set drifted: {sorted(listed ^ expected_sites)}")
        calls = []
        for site, route in spec['calls']:
            if rows[site] != route:
                raise ValueError(f"{spec['name']}: route drifted at {site:#x}: {rows[site]!r}")
            target = None
            if route.startswith('bl '):
                target = bl_target(site, memory.word(site))
                expected = ROUTE_TARGETS.get(route)
                if expected is None or target != expected:
                    raise ValueError(f"{spec['name']}: bl target drifted at {site:#x}: {target:#x}")
            calls.append({'site': f'0x{site:08x}', 'route': route,
                          'callee': f'0x{target:08x}' if target else None})

        listed_branches = set()
        disjoint = []
        for a, ins in inrange.items():
            m = re.match(r'^(b\w*)\s+(0x[0-9a-f]+)', ins)
            if not m or m.group(1) in ('bl', 'blx'):
                continue
            dest = int(m.group(2), 16)
            if spec['start'] <= dest < spec['end']:
                listed_branches.add((a, m.group(1), dest))
            else:
                disjoint.append({'address': f'0x{a:08x}', 'mnemonic': m.group(1),
                                 'destination': f'0x{dest:08x}'})
        expected_branches = {(a, mn, dest) for a, mn, dest in spec['branches']}
        if listed_branches != expected_branches:
            raise ValueError(f"{spec['name']}: branch set drifted: {sorted(listed_branches ^ expected_branches)}")

        for address, expected_text in spec['instructions']:
            if rows.get(address) != expected_text:
                raise ValueError(f"{spec['name']}: instruction drifted at {address:#x}: "
                                 f"{rows.get(address)!r} != {expected_text!r}")

        methods.append({
            'name': spec['name'],
            'method': spec['method'],
            'types': spec['types'],
            'imp': f"0x{spec['start']:08x}",
            'boundary_end': f"0x{spec['end']:08x}",
            'boundary': spec['boundary'],
            'verified_words': words,
            'pic_base': f'0x{base:08x}' if base else None,
            'selectors': selectors,
            'ivars': ivars,
            'calls': calls,
            'branches': [{'address': f'0x{a:08x}', 'mnemonic': mn,
                          'destination': f'0x{d:08x}'}
                         for a, mn, d in spec['branches']],
            'disjoint_branch_rows': disjoint,
            'semantics': spec['semantics'],
        })

    return {
        'schema': 1,
        'elf_sha256': sha,
        'batch': 'Crop smalls sweep (E91): the seven simple crops - type/seed/soil/render tables; 73 bodies',
        'claim': ('a static bounded-body map with per-instruction anchors; the wire-format markers, the '
                  'NSLog key strings, the C++ container member layouts and the packet helper at 0x8b84c8 are '
                  'outside these bodies'),
        'classes': methods,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('elf', type=Path)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--output', type=Path,
                        default=NATIVE / 'crop_smalls.json')
    args = parser.parse_args()
    report = recover(args.elf)
    payload = json.dumps(report, indent=2, sort_keys=True) + '\n'
    if args.check:
        if args.output.read_text() != payload:
            raise SystemExit('stale crop_smalls.json')
    else:
        args.output.write_text(payload)
    total = sum(m['verified_words'] for m in report['classes'])
    print(f"classes={len(report['classes'])} words={total}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
