# GENERATED by tools/gen_trace_codes.py from
# reconstruction/reverse-v3/native/trace_schemas.json -- do not edit.
# Single source of truth for LEVEL-B differential trace codes (the b4f
# collision bug: a hand-maintained Python enumerate drifted from the C++
# enum because two tables encoded the same semantics).

TREE_GROW_CODES = {
    "IsStaticTree": 0,
    "WorldTime": 1,
    "IncrementHeight": 2,
    "UpdateGrowthAdult": 3,
    "UpdateGrowthNo": 4,
    "IsGrowingInCompost": 5,
    "SowTreeNearParent": 6,
    "RemoveAllOwnedTiles": 7
}
NPC_LOADVALUES_CODES = {
    "ObjectForKeyFullness": 0,
    "ObjectForKeyLayTimer": 1,
    "ObjectForKeyDamage": 2,
    "ObjectForKeyAge": 3,
    "ObjectForKeyLayCooldownTimer": 4,
    "ObjectForKeyTameCooldownTimer": 5,
    "ObjectForKeyMateCooldownTimer": 6,
    "ObjectForKeyHasBred": 7,
    "ObjectForKeyHasBeenFedByBlockheadOrChest": 8,
    "ObjectForKeyMateBreed": 9,
    "ObjectForKeyBreed": 10,
    "ObjectForKeyTamedClientID": 11,
    "Retain": 12,
    "Autorelease": 13,
    "ObjectForKeyName": 14,
    "ObjectForKeyTameCountsByClientID": 15,
    "DictionaryWithDictionary": 16,
    "ObjectForKeyCurrentBlockheadIndex": 17,
    "FloatValue": 18,
    "IntValue": 19,
    "BoolValue": 20,
    "UnsignedIntegerValue": 21
}
FREIGHT_CAR_INIT_CODES = {
    "MsgSendSuper": 0,
    "ChestAlloc": 1,
    "ChestInitWithWorld": 2,
    "ChestSetProxyObjectOwner": 3,
    "ChestSetFloatPosAndUpdatePosition": 4
}
TRADE_PORTAL_PRICE_OFFSETS_CODES = {
    "FastEnumeration": 0,
    "ObjectForKey": 1,
    "DoubleValue": 2,
    "NumberWithDouble": 3,
    "SetObjectForKey": 4
}
TRADING_POST_INIT_SLOTS_CODES = {
    "AllocNSMutableArray": 0,
    "InitNSMutableArray": 1,
    "ObjectForKey": 2,
    "FastEnumeration": 3,
    "AllocInventoryItem": 4,
    "InitWithSaveData": 5,
    "AutoreleaseItem": 6,
    "ItemType": 7,
    "AddObject": 8
}
TABLES = {    'tree_grow': TREE_GROW_CODES,    'npc_loadvalues': NPC_LOADVALUES_CODES,    'freight_car_init': FREIGHT_CAR_INIT_CODES,    'trade_portal_price_offsets': TRADE_PORTAL_PRICE_OFFSETS_CODES,    'trading_post_init_slots': TRADING_POST_INIT_SLOTS_CODES,}

def self_test():
    for table, codes in TABLES.items():
        values = list(codes.values())
        assert len(values) == len(set(values)), table
    return True
