# GENERATED by tools/gen_trace_codes.py from
# reconstruction/reverse-v3/native/trace_schemas.json -- do not edit.
# Single source of truth for LEVEL-B differential trace codes (the b4f
# collision bug: a hand-maintained Python enumerate drifted from the C++
# enum because two tables encoded the same semantics).

TREE_GROW_CODES = {
    "IsStaticTree": 0,
    "WorldTime": 1,
    "IncrementHeight": 2,
    "UpdateGrowthAdult": 3,
    "UpdateGrowthNo": 4,
    "IsGrowingInCompost": 5,
    "SowTreeNearParent": 6,
    "RemoveAllOwnedTiles": 7
}
NPC_LOADVALUES_CODES = {
    "ObjectForKeyFullness": 0,
    "ObjectForKeyLayTimer": 1,
    "ObjectForKeyDamage": 2,
    "ObjectForKeyAge": 3,
    "ObjectForKeyLayCooldownTimer": 4,
    "ObjectForKeyTameCooldownTimer": 5,
    "ObjectForKeyMateCooldownTimer": 6,
    "ObjectForKeyHasBred": 7,
    "ObjectForKeyHasBeenFedByBlockheadOrChest": 8,
    "ObjectForKeyMateBreed": 9,
    "ObjectForKeyBreed": 10,
    "ObjectForKeyTamedClientID": 11,
    "Retain": 12,
    "Autorelease": 13,
    "ObjectForKeyName": 14,
    "ObjectForKeyTameCountsByClientID": 15,
    "DictionaryWithDictionary": 16,
    "ObjectForKeyCurrentBlockheadIndex": 17,
    "FloatValue": 18,
    "IntValue": 19,
    "BoolValue": 20,
    "UnsignedIntegerValue": 21
}
FREIGHT_CAR_INIT_CODES = {
    "MsgSendSuper": 0,
    "ChestAlloc": 1,
    "ChestInitWithWorld": 2,
    "ChestSetProxyObjectOwner": 3,
    "ChestSetFloatPosAndUpdatePosition": 4
}
TRADE_PORTAL_PRICE_OFFSETS_CODES = {
    "FastEnumeration": 0,
    "ObjectForKey": 1,
    "DoubleValue": 2,
    "NumberWithDouble": 3,
    "SetObjectForKey": 4
}
TRADING_POST_INIT_SLOTS_CODES = {
    "AllocNSMutableArray": 0,
    "InitNSMutableArray": 1,
    "ObjectForKey": 2,
    "FastEnumeration": 3,
    "AllocInventoryItem": 4,
    "InitWithSaveData": 5,
    "AutoreleaseItem": 6,
    "ItemType": 7,
    "AddObject": 8
}
DYNAMIC_OBJECT_INIT_DERIVED_STUFF_CODES = {
    "WorldMacroTiles": 0,
    "LoadPhysicalBlock": 1,
    "ShouldAddToMacroBlock": 2,
    "LoadDynamicObjects": 3,
    "AddObject": 4,
    "ObjectType": 5,
    "DynamicWorldChanged": 6
}
CHEST_INIT_CODES = {
    "MsgSendSuper": 0,
    "ObjectForKeyChestType": 1,
    "IntValueChestType": 2,
    "CustomRulesStret": 3,
    "CustomRulesMemset": 4,
    "ObjectForKeySafeClientID": 5,
    "RetainSafeClientID": 6,
    "ObjectType": 7,
    "DynamicWorldChangedAtPos": 8,
    "ObjectForKeySaveItemSlots": 9,
    "AllocNSMutableArray": 10,
    "InitWithCapacity": 11,
    "CountSaveItemSlots": 12,
    "ArrayNSMutableArray": 13,
    "AddObjectSlotArray": 14,
    "ObjectAtIndex": 15,
    "StateMemset": 16,
    "FastEnumeration": 17,
    "EnumerationMutation": 18,
    "AllocInventoryItem": 19,
    "InitWithSaveData": 20,
    "AutoreleaseItem": 21,
    "ItemType": 22,
    "AddObjectItem": 23,
    "StringWithFormatShelfRenderItems": 24,
    "ObjectForKeyShelfRenderItems": 25,
    "IntValueShelfRenderItems": 26,
    "StringWithFormatShelfItemDataBs": 27,
    "ObjectForKeyShelfItemDataBs": 28,
    "IntValueShelfItemDataBs": 29,
    "InitSubDerivedItems": 30
}
TABLES = {    'tree_grow': TREE_GROW_CODES,    'npc_loadvalues': NPC_LOADVALUES_CODES,    'freight_car_init': FREIGHT_CAR_INIT_CODES,    'trade_portal_price_offsets': TRADE_PORTAL_PRICE_OFFSETS_CODES,    'trading_post_init_slots': TRADING_POST_INIT_SLOTS_CODES,    'dynamic_object_init_derived_stuff': DYNAMIC_OBJECT_INIT_DERIVED_STUFF_CODES,    'chest_init': CHEST_INIT_CODES,}

def self_test():
    for table, codes in TABLES.items():
        values = list(codes.values())
        assert len(values) == len(set(values)), table
    return True
